#!/usr/bin/env python3
"""Generator for the P4 (multimodule thin-link ~24k assignments) repro.

Usage:
    python3 p4_gen_fixture.py <n_functions> <leaf_path>

Writes a leaf module with <n_functions> pub functions, each containing
exactly 200 `x = x + 1` assignments (kept under the per-function silent
truncation cap, LIMITATION P1, so every function is individually correct).
Total assignment statements = 200 * n_functions.

The matching main module is static (p4_thinlink_main.sio /
p4_thinlink_control_main.sio) and imports f0/f1 by name.
"""


def gen_leaf(n_fn, path):
    lines = [
        "// GENERATED by p4_gen_fixture.py -- do not edit by hand.",
        f"// {n_fn} functions x 200 assignments = {200 * n_fn} assignment statements.",
    ]
    for k in range(n_fn):
        lines.append(f"pub fn f{k}() -> i64 {{")
        lines.append("    var x: i64 = 0")
        for _ in range(200):
            lines.append("    x = x + 1")
        lines.append("    return x")
        lines.append("}")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    import sys

    gen_leaf(int(sys.argv[1]), sys.argv[2])
