apiVersion: v1
kind: Pod
metadata:
  name: data-uploader
  namespace: axolotl-sounio
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: workspace
      mountPath: /data
  tolerations:
  - { effect: NoSchedule, key: sounio.dev/pool, operator: Exists }
  - { effect: NoSchedule, key: sounio.dev/compute, operator: Exists }
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: axolotl-workspace
