apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cilium",
          "interface": "eth0",
          "ips": [
              "10.0.4.28"
          ],
          "mac": "4e:c3:9e:05:a2:d5",
          "default": true,
          "dns": {},
          "gateway": [
              "10.0.4.61"
          ]
      }]
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"darwin-atlas-u250-null-draw"},"name":"darwin-atlas-u250-null-draw","namespace":"default"},"spec":{"containers":[{"command":["/bin/bash","-lc","sleep infinity"],"image":"debian:trixie-slim","name":"null-draw","resources":{"limits":{"sounio.dev/u250":"1"},"requests":{"sounio.dev/u250":"1"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsUser":0,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":[{"mountPath":"/opt/xilinx/xrt","name":"host-xrt","readOnly":true},{"mountPath":"/opt/dl380-libs","name":"host-libs","readOnly":true}]}],"nodeSelector":{"sounio.dev/fpga":"u250"},"restartPolicy":"Never","volumes":[{"hostPath":{"path":"/opt/xilinx/xrt","type":"Directory"},"name":"host-xrt"},{"hostPath":{"path":"/usr/lib/x86_64-linux-gnu","type":"Directory"},"name":"host-libs"}]}}
  creationTimestamp: "2026-08-03T11:46:25Z"
  generation: 1
  labels:
    app.kubernetes.io/name: darwin-atlas-u250-null-draw
  name: darwin-atlas-u250-null-draw
  namespace: default
  resourceVersion: "89256657"
  uid: 81229be4-203c-48ff-9dff-1ce048b35bef
spec:
  containers:
  - command:
    - /bin/bash
    - -lc
    - sleep infinity
    image: debian:trixie-slim
    imagePullPolicy: IfNotPresent
    name: null-draw
    resources:
      limits:
        sounio.dev/u250: "1"
      requests:
        sounio.dev/u250: "1"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/xilinx/xrt
      name: host-xrt
      readOnly: true
    - mountPath: /opt/dl380-libs
      name: host-libs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8mtls
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: dl380-proxmox
  nodeSelector:
    sounio.dev/fpga: u250
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /opt/xilinx/xrt
      type: Directory
    name: host-xrt
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu
      type: Directory
    name: host-libs
  - name: kube-api-access-8mtls
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-08-03T11:46:27Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-08-03T11:46:25Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-08-03T11:46:27Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-08-03T11:46:27Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-08-03T11:46:25Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      sounio.dev/u250: "1"
    containerID: containerd://d2d77ab843c667bd7c3be80505b541dd23c5f907d81e7526e38cc3f342c733a0
    image: docker.io/library/debian:trixie-slim
    imageID: docker.io/library/debian@sha256:020c0d20b9880058cbe785a9db107156c3c75c2ac944a6aa7ab59f2add76a7bd
    lastState: {}
    name: null-draw
    ready: true
    resources:
      limits:
        sounio.dev/u250: "1"
      requests:
        sounio.dev/u250: "1"
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-08-03T11:46:26Z"
    volumeMounts:
    - mountPath: /opt/xilinx/xrt
      name: host-xrt
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /opt/dl380-libs
      name: host-libs
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8mtls
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.100.100.5
  hostIPs:
  - ip: 10.100.100.5
  observedGeneration: 1
  phase: Running
  podIP: 10.0.4.28
  podIPs:
  - ip: 10.0.4.28
  qosClass: BestEffort
  startTime: "2026-08-03T11:46:25Z"
