import SounioNaturalityG2

-- AUTO-GENERATED by tools/ocssm/generate_naturality_obligations.py
-- DO NOT EDIT BY HAND. To regenerate, run the script.
--
-- This file collects one obligation theorem per Sounio runtime function
-- declaring `with NaturalityG2`. Each theorem discharges the effect's
-- contract by appealing to the load-bearing discrete-G_2 naturality
-- aggregate `Sounio.NaturalityG2.naturality_basis_all` proved by
-- native_decide on the canonical-basis embed × the 8-element discrete
-- G_2 sub-skeleton (id + 7 Fano transpositions).
--
-- Closing the witnesses against the *continuous* runtime
-- Halton-Box-Muller embed (rather than the canonical basis embed) is
-- M5 work; the parametric witnesses here record the effect-flow
-- invariant in the meantime.

namespace Sounio.Obligations

open Sounio.NaturalityG2

/-- embed_row_into (declared in stdlib/dialogue/embed.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem embed_row_into_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- embed_into (declared in stdlib/dialogue/embed.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem embed_into_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f1_alt_stat_sq (declared in tools/ocssm/f1_moufang.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f1_alt_stat_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f1_compute_sq (declared in tools/ocssm/f1_moufang.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f1_compute_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- main (declared in tools/ocssm/f1_moufang.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem main_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f2_pair_residual_sq (declared in tools/ocssm/f2_conjugation.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f2_pair_residual_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f2_paired_dist_sq (declared in tools/ocssm/f2_conjugation.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f2_paired_dist_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f2_random_dist_sq (declared in tools/ocssm/f2_conjugation.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f2_random_dist_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f2_ratio (declared in tools/ocssm/f2_conjugation.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f2_ratio_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- rp_pair_residual_sq (declared in tests/run-pass/m5_held_out_replication.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem rp_pair_residual_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- rp_paired_dist_sq_fold (declared in tests/run-pass/m5_held_out_replication.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem rp_paired_dist_sq_fold_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- rp_random_dist_sq_fold (declared in tests/run-pass/m5_held_out_replication.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem rp_random_dist_sq_fold_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- rp_alt_stat_sq (declared in tests/run-pass/f1_moufang_synthetic.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem rp_alt_stat_sq_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f_const_one (declared in tests/run-pass/naturality_g2_effect.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f_const_one_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f_double (declared in tests/run-pass/naturality_g2_effect.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f_double_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

/-- f_mixed (declared in tests/run-pass/naturality_g2_effect.sio) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem f_mixed_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

end Sounio.Obligations
