import SounioPireusOperatorOrbitAdmissionReconstruction

open SounioPireusOperatorOrbitAdmissionReconstruction

#print axioms concrete_admission_reconstruction_matches_declared_frozen_summary
#print axioms coefficient_toggle_trace_has_one_collapse_and_32_admissions
#print axioms every_admission_has_exact_noncollision_separators
#print axioms bounded_admission_census_does_not_prove_global_novelty
