import SounioPireusGL4AnalyticCensus

open SounioPireusGL4AnalyticCensus

#print axioms eraseMany
#print axioms eraseMany_nil
#print axioms eraseMany_cons
#print axioms eraseMany_subset
#print axioms nodup_not_mem_erase_self
#print axioms mem_eraseMany_not_mem_forbidden
#print axioms eraseMany_length_eq_sub
#print axioms lane_xor_zero
#print axioms lane_zero_xor
#print axioms lane_xor_self
#print axioms lane_xor_assoc
#print axioms lane_xor_right_injective
#print axioms lane_xor_swap_middle
#print axioms lane_xor_cancel_coset
#print axioms nodup_map_of_injective
#print axioms spanZero
#print axioms spanOne
#print axioms spanTwo
#print axioms spanThree
#print axioms spanZero_nodup
#print axioms spanOne_closed
#print axioms nodup_append_xor_coset
#print axioms spanOne_nodup_of_not_zero
#print axioms spanTwo_nodup_of_outside
#print axioms spanTwo_closed
#print axioms spanThree_nodup_of_outside
#print axioms laneUniverse
#print axioms choicesOutside
#print axioms choicesOutside_length
#print axioms mem_choicesOutside_not_mem_span
#print axioms firstChoices
#print axioms secondChoices
#print axioms thirdChoices
#print axioms fourthChoices
#print axioms first_choices_length
#print axioms spanOne_nodup_of_first_choice
#print axioms second_choices_length
#print axioms spanTwo_nodup_of_second_choice
#print axioms third_choices_length
#print axioms spanThree_nodup_of_third_choice
#print axioms fourth_choices_length
#print axioms length_flatMap_of_constant
#print axioms OrderedBasis4
#print axioms fourthCompletions
#print axioms thirdCompletions
#print axioms secondCompletions
#print axioms analyticOrderedBases
#print axioms fourth_completions_length
#print axioms third_completions_length
#print axioms second_completions_length
#print axioms analytic_ordered_basis_census_is_20160
#print axioms GL4AnalyticCensusBoundary
#print axioms gl4AnalyticCensusBoundary
#print axioms analytic_census_does_not_close_frozen_scan_or_target03
