//! C-Compatible Epistemic Runtime Functions for Knowledge<T>
//!
//! This module provides C-compatible Rust functions for Knowledge<T> propagation
//! that can be called from assembly code generated by the native backend.
//!
//! Implements GUM (Guide to the Expression of Uncertainty in Measurement)
//! propagation rules for epistemic confidence intervals and provenance tracking.

/// Full epistemic knowledge structure with all metadata
/// Layout: [value, confidence, conf_lower, conf_upper, provenance_id, timestamp, revisable]
#[repr(C)]
pub struct KnowledgeFull {
    pub value: f64,
    pub confidence: f64,
    pub conf_lower: f64,
    pub conf_upper: f64,
    pub provenance_id: u32,
    pub timestamp: u64,
    pub revisable: u8,
}

impl KnowledgeFull {
    pub fn new(
        value: f64,
        confidence: f64,
        conf_lower: f64,
        conf_upper: f64,
        provenance_id: u32,
        timestamp: u64,
        revisable: bool,
    ) -> Self {
        Self {
            value,
            confidence,
            conf_lower,
            conf_upper,
            provenance_id,
            timestamp,
            revisable: if revisable { 1 } else { 0 },
        }
    }

    pub fn constant(value: f64) -> Self {
        Self {
            value,
            confidence: 1.0,
            conf_lower: value,
            conf_upper: value,
            provenance_id: 0,
            timestamp: 0,
            revisable: 0,
        }
    }
}

/// Compact epistemic knowledge structure for space efficiency
/// Layout: [value, quantized_conf, provenance_hash]
#[repr(C)]
pub struct KnowledgeCompact {
    pub value: f64,
    pub quantized_conf: u16, // 0-65535 maps to 0.0-1.0
    pub provenance_hash: u32,
}

impl KnowledgeCompact {
    pub fn new(value: f64, confidence: f64, provenance_hash: u32) -> Self {
        Self {
            value,
            quantized_conf: (confidence * 65535.0).clamp(0.0, 65535.0) as u16,
            provenance_hash,
        }
    }

    pub fn confidence(&self) -> f64 {
        self.quantized_conf as f64 / 65535.0
    }
}

/// Epistemic propagation: addition (full layout)
/// For independent variables with confidence intervals:
/// - Value: a + b
/// - Confidence interval width: sqrt(w_a² + w_b²) where w = (upper - lower)/2
/// - Confidence: geometric mean of inputs
///
/// C signature: void sounio_epistemic_add_full(
///     const KnowledgeFull* a,    // RDI: first knowledge value
///     const KnowledgeFull* b,    // RSI: second knowledge value
///     KnowledgeFull* result       // RDX: result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_add_full(
    a: *const KnowledgeFull,
    b: *const KnowledgeFull,
    result: *mut KnowledgeFull,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence;
        let a_lower = (*a).conf_lower;
        let a_upper = (*a).conf_upper;
        let b_val = (*b).value;
        let b_conf = (*b).confidence;
        let b_lower = (*b).conf_lower;
        let b_upper = (*b).conf_upper;

        // Value: a + b
        (*result).value = a_val + b_val;

        // Confidence: geometric mean (more conservative than arithmetic mean)
        (*result).confidence = (a_conf * b_conf).sqrt();

        // Confidence interval widths (half-widths)
        let a_half_width = (a_upper - a_lower) / 2.0;
        let b_half_width = (b_upper - b_lower) / 2.0;

        // GUM propagation: combined width = sqrt(w_a² + w_b²)
        let combined_half_width = (a_half_width * a_half_width + b_half_width * b_half_width).sqrt();

        (*result).conf_lower = (*result).value - combined_half_width;
        (*result).conf_upper = (*result).value + combined_half_width;

        // Provenance: combine IDs (XOR for simple mixing)
        (*result).provenance_id = (*a).provenance_id ^ (*b).provenance_id;

        // Timestamp: use most recent
        (*result).timestamp = (*a).timestamp.max((*b).timestamp);

        // Revisable if either input is revisable
        (*result).revisable = (*a).revisable | (*b).revisable;
    }
}

/// Epistemic propagation: addition (compact layout)
///
/// C signature: void sounio_epistemic_add_compact(
///     const KnowledgeCompact* a,
///     const KnowledgeCompact* b,
///     KnowledgeCompact* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_add_compact(
    a: *const KnowledgeCompact,
    b: *const KnowledgeCompact,
    result: *mut KnowledgeCompact,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence();
        let b_val = (*b).value;
        let b_conf = (*b).confidence();

        // Value: a + b
        (*result).value = a_val + b_val;

        // Confidence: geometric mean
        let combined_conf = (a_conf * b_conf).sqrt();
        (*result).quantized_conf = (combined_conf * 65535.0).clamp(0.0, 65535.0) as u16;

        // Provenance: XOR hash
        (*result).provenance_hash = (*a).provenance_hash ^ (*b).provenance_hash;
    }
}

/// Epistemic propagation: subtraction (full layout)
/// For independent variables: same propagation as addition
///
/// C signature: void sounio_epistemic_sub_full(
///     const KnowledgeFull* a,
///     const KnowledgeFull* b,
///     KnowledgeFull* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_sub_full(
    a: *const KnowledgeFull,
    b: *const KnowledgeFull,
    result: *mut KnowledgeFull,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence;
        let a_lower = (*a).conf_lower;
        let a_upper = (*a).conf_upper;
        let b_val = (*b).value;
        let b_conf = (*b).confidence;
        let b_lower = (*b).conf_lower;
        let b_upper = (*b).conf_upper;

        // Value: a - b
        (*result).value = a_val - b_val;

        // Confidence: geometric mean
        (*result).confidence = (a_conf * b_conf).sqrt();

        // Confidence interval widths
        let a_half_width = (a_upper - a_lower) / 2.0;
        let b_half_width = (b_upper - b_lower) / 2.0;

        // GUM propagation: sqrt(w_a² + w_b²)
        let combined_half_width = (a_half_width * a_half_width + b_half_width * b_half_width).sqrt();

        (*result).conf_lower = (*result).value - combined_half_width;
        (*result).conf_upper = (*result).value + combined_half_width;

        // Provenance: combine IDs
        (*result).provenance_id = (*a).provenance_id ^ (*b).provenance_id;

        // Timestamp: most recent
        (*result).timestamp = (*a).timestamp.max((*b).timestamp);

        // Revisable if either input is revisable
        (*result).revisable = (*a).revisable | (*b).revisable;
    }
}

/// Epistemic propagation: subtraction (compact layout)
///
/// C signature: void sounio_epistemic_sub_compact(
///     const KnowledgeCompact* a,
///     const KnowledgeCompact* b,
///     KnowledgeCompact* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_sub_compact(
    a: *const KnowledgeCompact,
    b: *const KnowledgeCompact,
    result: *mut KnowledgeCompact,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence();
        let b_val = (*b).value;
        let b_conf = (*b).confidence();

        // Value: a - b
        (*result).value = a_val - b_val;

        // Confidence: geometric mean
        let combined_conf = (a_conf * b_conf).sqrt();
        (*result).quantized_conf = (combined_conf * 65535.0).clamp(0.0, 65535.0) as u16;

        // Provenance: XOR hash
        (*result).provenance_hash = (*a).provenance_hash ^ (*b).provenance_hash;
    }
}

/// Epistemic propagation: multiplication (full layout)
/// Relative uncertainty propagation: sqrt((wa/a)² + (wb/b)²) * |result|
///
/// C signature: void sounio_epistemic_mul_full(
///     const KnowledgeFull* a,
///     const KnowledgeFull* b,
///     KnowledgeFull* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_mul_full(
    a: *const KnowledgeFull,
    b: *const KnowledgeFull,
    result: *mut KnowledgeFull,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence;
        let a_lower = (*a).conf_lower;
        let a_upper = (*a).conf_upper;
        let b_val = (*b).value;
        let b_conf = (*b).confidence;
        let b_lower = (*b).conf_lower;
        let b_upper = (*b).conf_upper;

        // Value: a * b
        let result_val = a_val * b_val;
        (*result).value = result_val;

        // Confidence: geometric mean
        (*result).confidence = (a_conf * b_conf).sqrt();

        // Relative uncertainty propagation
        let a_half_width = (a_upper - a_lower) / 2.0;
        let b_half_width = (b_upper - b_lower) / 2.0;

        // Handle division by zero
        let combined_half_width = if a_val == 0.0 && b_val == 0.0 {
            0.0
        } else if a_val == 0.0 {
            a_half_width * b_val.abs()
        } else if b_val == 0.0 {
            b_half_width * a_val.abs()
        } else {
            let rel_width_a = a_half_width / a_val.abs();
            let rel_width_b = b_half_width / b_val.abs();
            result_val.abs() * (rel_width_a * rel_width_a + rel_width_b * rel_width_b).sqrt()
        };

        (*result).conf_lower = result_val - combined_half_width;
        (*result).conf_upper = result_val + combined_half_width;

        // Provenance: combine IDs
        (*result).provenance_id = (*a).provenance_id ^ (*b).provenance_id;

        // Timestamp: most recent
        (*result).timestamp = (*a).timestamp.max((*b).timestamp);

        // Revisable if either input is revisable
        (*result).revisable = (*a).revisable | (*b).revisable;
    }
}

/// Epistemic propagation: multiplication (compact layout)
///
/// C signature: void sounio_epistemic_mul_compact(
///     const KnowledgeCompact* a,
///     const KnowledgeCompact* b,
///     KnowledgeCompact* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_mul_compact(
    a: *const KnowledgeCompact,
    b: *const KnowledgeCompact,
    result: *mut KnowledgeCompact,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence();
        let b_val = (*b).value;
        let b_conf = (*b).confidence();

        // Value: a * b
        (*result).value = a_val * b_val;

        // Confidence: geometric mean
        let combined_conf = (a_conf * b_conf).sqrt();
        (*result).quantized_conf = (combined_conf * 65535.0).clamp(0.0, 65535.0) as u16;

        // Provenance: XOR hash
        (*result).provenance_hash = (*a).provenance_hash ^ (*b).provenance_hash;
    }
}

/// Epistemic propagation: division (full layout)
/// Relative uncertainty propagation: same as multiplication
///
/// C signature: void sounio_epistemic_div_full(
///     const KnowledgeFull* a,
///     const KnowledgeFull* b,
///     KnowledgeFull* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_div_full(
    a: *const KnowledgeFull,
    b: *const KnowledgeFull,
    result: *mut KnowledgeFull,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence;
        let a_lower = (*a).conf_lower;
        let a_upper = (*a).conf_upper;
        let b_val = (*b).value;
        let b_conf = (*b).confidence;
        let b_lower = (*b).conf_lower;
        let b_upper = (*b).conf_upper;

        if b_val == 0.0 {
            (*result).value = f64::NAN;
            (*result).confidence = 0.0;
            (*result).conf_lower = f64::NAN;
            (*result).conf_upper = f64::NAN;
            (*result).provenance_id = (*a).provenance_id ^ (*b).provenance_id;
            (*result).timestamp = (*a).timestamp.max((*b).timestamp);
            (*result).revisable = (*a).revisable | (*b).revisable;
            return;
        }

        // Value: a / b
        let result_val = a_val / b_val;
        (*result).value = result_val;

        // Confidence: geometric mean
        (*result).confidence = (a_conf * b_conf).sqrt();

        // Relative uncertainty propagation
        let a_half_width = (a_upper - a_lower) / 2.0;
        let b_half_width = (b_upper - b_lower) / 2.0;

        let combined_half_width = if a_val == 0.0 {
            a_half_width / b_val.abs()
        } else {
            let rel_width_a = a_half_width / a_val.abs();
            let rel_width_b = b_half_width / b_val.abs();
            result_val.abs() * (rel_width_a * rel_width_a + rel_width_b * rel_width_b).sqrt()
        };

        (*result).conf_lower = result_val - combined_half_width;
        (*result).conf_upper = result_val + combined_half_width;

        // Provenance: combine IDs
        (*result).provenance_id = (*a).provenance_id ^ (*b).provenance_id;

        // Timestamp: most recent
        (*result).timestamp = (*a).timestamp.max((*b).timestamp);

        // Revisable if either input is revisable
        (*result).revisable = (*a).revisable | (*b).revisable;
    }
}

/// Epistemic propagation: division (compact layout)
///
/// C signature: void sounio_epistemic_div_compact(
///     const KnowledgeCompact* a,
///     const KnowledgeCompact* b,
///     KnowledgeCompact* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_div_compact(
    a: *const KnowledgeCompact,
    b: *const KnowledgeCompact,
    result: *mut KnowledgeCompact,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence();
        let b_val = (*b).value;
        let b_conf = (*b).confidence();

        if b_val == 0.0 {
            (*result).value = f64::NAN;
            (*result).quantized_conf = 0;
            (*result).provenance_hash = (*a).provenance_hash ^ (*b).provenance_hash;
            return;
        }

        // Value: a / b
        (*result).value = a_val / b_val;

        // Confidence: geometric mean
        let combined_conf = (a_conf * b_conf).sqrt();
        (*result).quantized_conf = (combined_conf * 65535.0).clamp(0.0, 65535.0) as u16;

        // Provenance: XOR hash
        (*result).provenance_hash = (*a).provenance_hash ^ (*b).provenance_hash;
    }
}

/// Epistemic meet operation: take minimum confidence
/// Used for skeptical combination (most conservative estimate)
///
/// C signature: void sounio_epistemic_meet(
///     const KnowledgeFull* a,
///     const KnowledgeFull* b,
///     KnowledgeFull* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_meet(
    a: *const KnowledgeFull,
    b: *const KnowledgeFull,
    result: *mut KnowledgeFull,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        // Take value with lower confidence (more skeptical)
        if (*a).confidence < (*b).confidence {
            *result = *a;
        } else {
            *result = *b;
        }
    }
}

/// Epistemic join operation: weighted average by inverse variance
/// Used for credulous combination (averaging independent measurements)
///
/// C signature: void sounio_epistemic_join(
///     const KnowledgeFull* a,
///     const KnowledgeFull* b,
///     KnowledgeFull* result
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_join(
    a: *const KnowledgeFull,
    b: *const KnowledgeFull,
    result: *mut KnowledgeFull,
) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_conf = (*a).confidence;
        let a_lower = (*a).conf_lower;
        let a_upper = (*a).conf_upper;
        let b_val = (*b).value;
        let b_conf = (*b).confidence;
        let b_lower = (*b).conf_lower;
        let b_upper = (*b).conf_upper;

        // Use inverse-variance weighting
        // w_i = 1 / variance_i, where variance ≈ (width/2)²
        let a_half_width = (a_upper - a_lower) / 2.0;
        let b_half_width = (b_upper - b_lower) / 2.0;

        let a_variance = a_half_width * a_half_width;
        let b_variance = b_half_width * b_half_width;

        // Handle exact values (zero variance)
        if a_variance == 0.0 {
            *result = *a;
            return;
        }
        if b_variance == 0.0 {
            *result = *b;
            return;
        }

        let a_weight = 1.0 / a_variance;
        let b_weight = 1.0 / b_variance;
        let sum_weights = a_weight + b_weight;

        // Weighted average of values
        (*result).value = (a_weight * a_val + b_weight * b_val) / sum_weights;

        // Combined confidence: average weighted by inverse variance
        (*result).confidence = (a_weight * a_conf + b_weight * b_conf) / sum_weights;

        // Combined variance: 1 / (w_a + w_b)
        let combined_variance = 1.0 / sum_weights;
        let combined_half_width = combined_variance.sqrt();

        (*result).conf_lower = (*result).value - combined_half_width;
        (*result).conf_upper = (*result).value + combined_half_width;

        // Provenance: combine IDs
        (*result).provenance_id = (*a).provenance_id ^ (*b).provenance_id;

        // Timestamp: most recent
        (*result).timestamp = (*a).timestamp.max((*b).timestamp);

        // Revisable if either input is revisable
        (*result).revisable = (*a).revisable | (*b).revisable;
    }
}

/// Extract confidence value from Knowledge<T>
///
/// C signature: double sounio_epistemic_extract_confidence(
///     const KnowledgeFull* knowledge
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_epistemic_extract_confidence(
    knowledge: *const KnowledgeFull,
) -> f64 {
    if knowledge.is_null() {
        return 0.0;
    }

    unsafe { (*knowledge).confidence }
}
