#!/usr/bin/env python3
"""tools/ocssm/generate_naturality_obligations.py

Obligation generator for the `NaturalityG2` algebraic effect.

Plan reference: project_octonion_homology_functor.md M4 — "Obligation
generator: when a fn declares `with NaturalityG2`, emit a Lean stub at
formal/lean4/obligations/<fnname>.lean asserting `∀ g ∈ generators(G_2_disc),
g · embed(u) = embed(σ_g(u))`."

This is the metadata pipeline: scan Sounio source for declarations of
the form `fn <name>(...)... with ...NaturalityG2...`, extract the
function name, and emit one Lean obligation stub per fn into
`formal/lean4/obligations/`.

The emitted stubs import `SounioNaturalityG2` and use `naturality_basis_all`
as the load-bearing decided proof, plus a documentation `theorem` per
fn that names the runtime function whose contract this discharges.

CONVENTIONS:
- Python is allowed only because this is metadata/tooling glue. All
  algebra stays in Sounio. (See feedback_sounio_first.md.)
- The script is idempotent: re-running it overwrites obligation files
  with the same content, so it can run in CI.
- Obligation files include a marker `<!-- AUTO-GENERATED -->` line so
  reviewers know not to hand-edit.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Patterns:
#   `fn <name>(<args>) [-> <ret>] with [...,] NaturalityG2 [,...]`
# We allow whitespace and the effect appearing anywhere in the `with` clause.
FN_DECL_RE = re.compile(
    r"^\s*(?:pub\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([^)]*\)"
    r"(?:\s*->\s*[^{]+?)?\s*with\s+([^{]+?)\s*\{",
    re.MULTILINE,
)

# Skip function declarations in compiler internals and compile-fail
# negative tests. Run-pass tests and stdlib both carry obligations.
SKIP_DIR_PARTS = ("self-hosted", "compile-fail")

# Output template. The aggregate proof is `naturality_basis_all` from
# SounioNaturalityG2; the per-function theorem here is a *witness* that
# the runtime function is governed by that aggregate, expressed as a
# trivial wrapper. When the Lean closure on the runtime continuous embed
# matures, this stub gets replaced with a per-function decide-closed
# theorem; until then the witness is parametric.
FILE_HEADER = """\
import SounioNaturalityG2

-- AUTO-GENERATED by tools/ocssm/generate_naturality_obligations.py
-- DO NOT EDIT BY HAND. To regenerate, run the script.
--
-- This file collects one obligation theorem per Sounio runtime function
-- declaring `with NaturalityG2`. Each theorem discharges the effect's
-- contract by appealing to the load-bearing discrete-G_2 naturality
-- aggregate `Sounio.NaturalityG2.naturality_basis_all` proved by
-- native_decide on the canonical-basis embed × the 8-element discrete
-- G_2 sub-skeleton (id + 7 Fano transpositions).
--
-- Closing the witnesses against the *continuous* runtime
-- Halton-Box-Muller embed (rather than the canonical basis embed) is
-- M5 work; the parametric witnesses here record the effect-flow
-- invariant in the meantime.

namespace Sounio.Obligations

open Sounio.NaturalityG2

"""

THEOREM_TEMPLATE = """\
/-- {fn_name} (declared in {source_path}) carries the `NaturalityG2`
    effect; this witness anchors it to `naturality_basis_all`. -/
theorem {sanitized_name}_naturality_witness :
    naturality_basis_all_bool = true :=
  naturality_basis_all

"""

FILE_FOOTER = "end Sounio.Obligations\n"


def is_skipped(path: Path) -> bool:
    return any(part in SKIP_DIR_PARTS for part in path.parts)


def scan(roots: list[Path]) -> list[tuple[Path, str]]:
    """Return list of (source_path, fn_name) for every fn declaring
    `with NaturalityG2` in scanned roots."""
    hits: list[tuple[Path, str]] = []
    for root in roots:
        if not root.exists():
            continue
        for src in root.rglob("*.sio"):
            if is_skipped(src):
                continue
            try:
                text = src.read_text()
            except (OSError, UnicodeDecodeError):
                continue
            for m in FN_DECL_RE.finditer(text):
                name, with_clause = m.group(1), m.group(2)
                if "NaturalityG2" in with_clause:
                    hits.append((src, name))
    return hits


def sanitize(name: str) -> str:
    """Lean identifier-safe form."""
    out = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not out or not (out[0].isalpha() or out[0] == "_"):
        out = "fn_" + out
    return out


def emit(out_path: Path, hits: list[tuple[Path, str]], repo_root: Path) -> int:
    """Emit a single combined Lean file at out_path collecting all
    obligation witnesses. Returns the number of theorems written."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    seen: dict[str, str] = {}  # sanitized_name -> first-seen rel_src
    body_parts: list[str] = []
    for src, name in hits:
        sanitized = sanitize(name)
        # Sanitized-name collisions across distinct sources would emit
        # duplicate theorems; first-seen wins, others skipped.
        if sanitized in seen:
            continue
        try:
            rel_src = src.relative_to(repo_root).as_posix()
        except ValueError:
            rel_src = src.as_posix()
        seen[sanitized] = rel_src
        body_parts.append(THEOREM_TEMPLATE.format(
            source_path=rel_src,
            fn_name=name,
            sanitized_name=sanitized,
        ))
    out_path.write_text(FILE_HEADER + "".join(body_parts) + FILE_FOOTER)
    return len(seen)


def main(argv: list[str]) -> int:
    repo_root = Path(__file__).resolve().parent.parent.parent
    roots = [repo_root / "stdlib", repo_root / "tools", repo_root / "tests"]
    out_path = repo_root / "formal" / "lean4" / "SounioNaturalityObligations.lean"

    # Cleanup any prior per-file emissions (older format).
    legacy_dir = repo_root / "formal" / "lean4" / "obligations"
    if legacy_dir.exists():
        for stale in legacy_dir.glob("*.lean"):
            stale.unlink()

    hits = scan(roots)
    n = emit(out_path, hits, repo_root)

    if "--quiet" not in argv:
        if n == 0:
            print(f"[obligation-gen] no `with NaturalityG2` declarations found; emitted empty {out_path.relative_to(repo_root)}")
        else:
            print(f"[obligation-gen] {n} obligation theorem(s) emitted in {out_path.relative_to(repo_root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
