<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>F# interop library for calling Sounio native functions via IPC</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Protocol.fs" />
    <Compile Include="NativeKernel.fs" />
    <Compile Include="SounioProcess.fs" />
  </ItemGroup>

</Project>
