#!/usr/bin/env bash
# fano_kernel_provenance_gate.sh -- the committed AVX-512 Fano octonion kernel
# must be exactly what the compiler's own lowering emits.
#
#   tests/run-pass/fano_raw_kernel.bin          186 bytes, 31 EVEX instructions
#   tests/self-hosted/gen_fano_raw_kernel.sio   calls native::lower_ir::
#                                               lower_hyper_mul_o_fano and prints
#                                               the emitted bytes as hex
#   tests/run-pass/hyper_octonion_silicon_exec.cpp
#                                               loads a kernel file and runs it
#                                               (e6*e4, a full product,
#                                               |ab|^2 = |a|^2|b|^2 = 756, left
#                                               and right alternativity)
#
# Steps:
#   P1  generate the bytes from current source (lean_single engine; see the
#       generator's header for why not Madaros) and require byte equality with
#       the committed .bin. A difference fails: either the blob or the lowering
#       is wrong, and which one must be decided, not papered over by
#       regenerating the blob.
#   P2  if this host has AVX-512F and a C++23 g++, run the silicon harness on
#       the GENERATED bytes. Otherwise print SILICON-SKIP and say why: GitHub
#       runners are not guaranteed to have AVX-512.
#
# --selftest: flip one byte of a copy of the blob and require P1's comparator
# to reject it (the comparator is not vacuous).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
BIN="tests/run-pass/fano_raw_kernel.bin"
GEN="tests/self-hosted/gen_fano_raw_kernel.sio"
CPP="tests/run-pass/hyper_octonion_silicon_exec.cpp"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

fail() { echo "FANO_PROVENANCE_FAIL: $*" >&2; exit 1; }

compare() {  # compare <generated> <committed>
  if cmp -s "$1" "$2"; then return 0; fi
  echo "byte differences (offset, generated octal, committed octal):" >&2
  cmp -l "$1" "$2" | head -20 >&2 || true
  return 1
}

[[ -f "$BIN" ]] || fail "missing $BIN"
[[ "$(wc -c <"$BIN" | tr -d ' ')" == 186 ]] || fail "$BIN is not 186 bytes"

if [[ "${1:-}" == "--selftest" ]]; then
  cp "$BIN" "$WORK/mut.bin"
  python3 - "$WORK/mut.bin" <<'PY'
import sys
p = sys.argv[1]
b = bytearray(open(p, "rb").read())
b[25] ^= 0x40            # the EVEX.X bit of the first sign-mask VXORPD
open(p, "wb").write(bytes(b))
PY
  if compare "$WORK/mut.bin" "$BIN" 2>/dev/null; then
    fail "selftest: a one-bit mutation of the blob was accepted"
  fi
  echo "FANO_PROVENANCE_SELFTEST_OK: one-bit mutation rejected"
  exit 0
fi

# ---- P1: bytes from the compiler's lowering == committed blob ---------------
export SOUNIO_STDLIB_PATH="$ROOT/stdlib"
SOUNIO_SOUC_ENGINE=lean_single timeout 600 ./bin/souc run "$GEN" >"$WORK/gen.log" 2>&1 \
  || { tail -20 "$WORK/gen.log" >&2; fail "generator did not run"; }
hex="$(sed -n 's/^RAW_KERNEL_HEX://p' "$WORK/gen.log" | tail -1)"
[[ -n "$hex" ]] || { tail -20 "$WORK/gen.log" >&2; fail "generator printed no RAW_KERNEL_HEX line"; }
python3 -c 'import sys; open(sys.argv[2], "wb").write(bytes.fromhex(sys.argv[1]))' "$hex" "$WORK/gen.bin"
if ! compare "$WORK/gen.bin" "$BIN"; then
  fail "lower_hyper_mul_o_fano no longer emits $BIN. Decide which side is wrong (disassemble both: objdump -D -b binary -m i386:x86-64 FILE); do not regenerate the blob to make this pass."
fi
echo "P1 PASS: lower_hyper_mul_o_fano emits $BIN byte for byte (186 bytes, sha256 $(sha256sum "$BIN" | cut -c1-16))"

# ---- P2: execute the generated bytes on silicon --------------------------------
if ! grep -qw avx512f /proc/cpuinfo 2>/dev/null; then
  echo "SILICON-SKIP: this host has no AVX-512F"
  exit 0
fi
if ! command -v g++ >/dev/null 2>&1; then
  echo "SILICON-SKIP: no g++ on this host"
  exit 0
fi
g++ -std=c++23 -O2 -mavx512f -o "$WORK/silicon" "$CPP" 2>"$WORK/cxx.log" \
  || { cat "$WORK/cxx.log" >&2; fail "silicon harness did not compile"; }
"$WORK/silicon" "$WORK/gen.bin" | tee "$WORK/silicon.log" || fail "silicon harness failed on the generated bytes"
grep -q "ALL 5 HARDWARE SILICON TESTS PASSED" "$WORK/silicon.log" || fail "silicon harness did not report success"
echo "P2 PASS: generated bytes execute correctly on AVX-512 silicon"
