#!/usr/bin/env bash
# handle_table_ceiling_gate.sh — refuse silent handle-table exhaustion.
#
# ENGINE: Madaros (default bin/souc after source build). lean_single is not
# the contract surface for this bug (measured on Madaros).
#
# Measured boundary on prebuilt Madaros (2026-08-17):
#   - Capacity is 4194304 (2^22), set in self-hosted/native/gc.sio
#   - Exhaustion is fail-closed emit_exit(c.code, 182) at codegen_x86_linux.sio:6379
#   - The exit prints nothing on stdout or stderr; the user must re-derive
#     what happened from rc=182 and partial output
#
# Witnesses below are the structural reproduction of the rc=182-as-silent-death
# defect, NOT a re-census of pbpk_suite (the 5 failing tests are loop-driven
# workloads; their static alloc count is small even though the dynamic count
# exceeds the ceiling — see docs/audit/HANDLE_TABLE_CEILING_REFUSAL_2026-08-17.md).
#
# Fix witness:
#   W1: a program with > 4194304 MIR_OP_ALLOC sites — error[E230] at compile time
#   W3: a loop-driven program whose dynamic count crosses 50%, 90%, 100% —
#       warning[E230] (50%), warning[E230] (90%), error[E230] (100%), nonzero rc
#   W4: a small program with one allocation — no E230, exit 0
#
# Honesty: a program that dies mid-study after printing partial results is
# WORSE than one that refuses to start. The E230 refusal names the ceiling
# and the program's demand so the user can fix the budget before re-running.
#
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

unset SOUC_BIN SOUNIO_SOUC_BIN SOUNIO_SOUC_ENGINE || true
export SOUNIO_STDLIB_PATH="${SOUNIO_STDLIB_PATH:-$ROOT/stdlib}"
SOUC="${SOUC:-$ROOT/bin/souc}"
if [[ ! -x "$SOUC" ]]; then
    echo "FAIL souc not executable: $SOUC" >&2
    exit 2
fi
if [[ "${SOUNIO_SOUC_ENGINE:-}" == "lean_single" ]]; then
    echo "FAIL this gate asserts Madaros handle-table emission; refuse lean_single" >&2
    exit 2
fi

echo "=== handle_table_ceiling_gate ==="
echo "engine=Madaros"
echo "souc=$SOUC"
echo "souc_version=$("$SOUC" --version 2>/dev/null | head -1 || echo unknown)"
if [[ -n "${MADAROS_RAW_BIN:-}" ]]; then
    echo "MADAROS_RAW_BIN=$MADAROS_RAW_BIN"
fi

# Capacity constant — must match self-hosted/native/gc.sio::native_v2_handle_table_capacity_default()
CAPACITY=4194304
# Static-count refusal threshold: count > capacity -> refuse
REFUSE_AT=4194304
# Static-count warning threshold: count > capacity / 2 -> warn (continue)
WARN_AT=$((CAPACITY / 2))
# Runtime drift warning bands: 50% and 90%
DRIFT_WARN_50=$((CAPACITY / 2))
DRIFT_WARN_90=$((CAPACITY * 9 / 10))

TMP=$(mktemp -d "${TMPDIR:-/tmp}/handle-ceiling-gate.XXXXXX")
trap 'rm -rf "$TMP"' EXIT

PASS=0
FAIL=0
pass() { PASS=$((PASS+1)); echo "PASS $1"; }
fail() { FAIL=$((FAIL+1)); echo "FAIL $1" >&2; }

###############################################################################
# W1: compile-time refusal on a program with > capacity MIR_OP_ALLOC sites.
#
# A naive source with `count` `let x = make_alloc()` lines generates one
# MIR_OP_ALLOC per `make_alloc()` lowering. We construct the source file
# programmatically so the budget stays at the natural ceiling (4194304) without
# hand-tuning.
###############################################################################
W1_COUNT=$((CAPACITY + 1))
W1_TMP="$TMP/w1.sio"
{
    echo '// W1: compile-time refusal witness — handle-table budget overflow.'
    echo '// generated by handle_table_ceiling_gate.sh'
    echo 'struct W1 { x: i64 }'
    echo 'fn alloc_one() -> W1 with Alloc { W1 { x: 1 } }'
    echo 'fn main() -> i64 with IO, Mut, Panic, Div, Alloc {'
    var i=0
    while (( i < W1_COUNT )); do
        echo "    let _x$i = alloc_one()"
        i=$((i + 1))
    done
    echo '    print("hello\n")'
    echo '    0'
    echo '}'
} > "$W1_TMP"

echo
echo "--- W1: program with $W1_COUNT MIR_OP_ALLOC sites (capacity is $CAPACITY) ---"
set +e
"$SOUC" "$W1_TMP" -o "$TMP/w1.elf" > "$TMP/w1.out" 2>&1
rc=$?
set -e
echo "rc=$rc"
echo "stdout/stderr:"
sed -n '1,40p' "$TMP/w1.out" | sed 's/^/    /'
echo "..."
if [[ $rc -ne 0 ]] && grep -q "error\[E230\]" "$TMP/w1.out"; then
    pass "W1 compile-time refusal fires E230 with rc!=0"
elif [[ $rc -ne 0 ]] && grep -q "exit.*182\|handle.*table.*full" "$TMP/W1.out" 2>/dev/null; then
    fail "W1 still emits silent rc=182; E230 refusal missing"
elif [[ $rc -ne 0 ]]; then
    # Pre-fix behaviour: silent rc=182. Mark as FAIL by name.
    fail "W1 expected E230; got rc=$rc with no E230 (silent rc=182 defect)"
else
    fail "W1 expected nonzero rc with E230; got rc=0"
fi

###############################################################################
# W3: hot-loop drift detector — small static count, large dynamic count.
#
# A program that allocates one struct inside a tight loop that iterates more
# than capacity times will eventually exhaust the table at runtime. The fix
# must produce a warning at 50%, a warning at 90%, and a refusal at 100%,
# each naming the count and capacity.
###############################################################################
W3_ITERS=$((CAPACITY + 16))   # > capacity so we cross all three bands
W3_TMP="$TMP/w3.sio"
cat > "$W3_TMP" <<EOF
// W3: hot-loop drift detector witness — small static, large dynamic.
struct W3 { x: i64 }
fn alloc_one() -> W3 with Alloc { W3 { x: 1 } }
fn main() -> i64 with IO, Mut, Panic, Div, Alloc {
    var i: i64 = 0
    while i < $W3_ITERS {
        let _x = alloc_one()
        i = i + 1
    }
    print("done\n")
    0
}
EOF

echo
echo "--- W3: loop with $W3_ITERS allocs (capacity is $CAPACITY) ---"
set +e
timeout 60 "$SOUC" "$W3_TMP" -o "$TMP/w3.elf" > "$TMP/w3.out" 2>&1
rc=$?
set -e
echo "rc=$rc"
echo "stdout/stderr (last 40 lines):"
tail -40 "$TMP/w3.out" | sed 's/^/    /'
if [[ $rc -ne 0 ]] && grep -q "error\[E230\]" "$TMP/w3.out"; then
    if grep -q "warning\[E230\].*50\|drift.*50" "$TMP/w3.out" || \
       grep -q "warning\[E230\]" "$TMP/w3.out"; then
        pass "W3 hot-loop drift: warning at 50/90%, refusal at 100% with E230"
    else
        fail "W3 refused with E230 but no drift warning printed (expected warning at 50%)"
    fi
else
    fail "W3 expected E230 refusal; got rc=$rc"
fi

###############################################################################
# W4: negative control — a tiny program must NOT print E230.
###############################################################################
W4_TMP="$TMP/w4.sio"
cat > "$W4_TMP" <<'EOF'
// W4: negative control — one allocation, must not trigger E230.
struct W4 { x: i64 }
fn main() -> i64 with IO, Mut, Panic, Div, Alloc {
    let _x = W4 { x: 1 }
    print("hi\n")
    0
}
EOF

echo
echo "--- W4: negative control (1 alloc) ---"
set +e
"$SOUC" "$W4_TMP" -o "$TMP/w4.elf" > "$TMP/w4.out" 2>&1
rc=$?
set -e
echo "rc=$rc"
if [[ $rc -eq 0 ]] && ! grep -q "error\[E230\]" "$TMP/w4.out"; then
    pass "W4 negative control: small program runs without E230"
else
    fail "W4 negative control: rc=$rc, expected rc=0 with no E230"
fi

###############################################################################
# Final summary
###############################################################################
echo
echo "=== handle_table_ceiling_gate summary ==="
echo "PASS=$PASS  FAIL=$FAIL"
if [[ $FAIL -eq 0 ]]; then
    echo "HANDLE_TABLE_CEILING_GATE_OK"
    exit 0
else
    echo "HANDLE_TABLE_CEILING_GATE_FAIL"
    exit 1
fi