#!/usr/bin/env bash
# CUDA runtime gate for Kretikos cross-backend PTX-side artifacts.
#
# This gate launches the CUBINs generated by kretikos_cross_backend_semantic_gate.sh
# through the CUDA Driver API and checks real device outputs against CPU oracles.
# It is intentionally narrower than cross-backend runtime equivalence: Metal and
# SPIR-V runtime execution are not claimed here.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

OUT_DIR="${SOUNIO_KRETIKOS_CROSS_BACKEND_CUDA_RUNTIME_DIR:-$ROOT_DIR/artifacts/omega/kretikos_cross_backend_cuda_runtime}"
REPORT_JSON="${SOUNIO_KRETIKOS_CROSS_BACKEND_CUDA_RUNTIME_JSON:-$OUT_DIR/kretikos_cross_backend_cuda_runtime.v1.json}"
SEMANTIC_DIR="${SOUNIO_KRETIKOS_CROSS_BACKEND_DIR:-$ROOT_DIR/artifacts/omega/kretikos_cross_backend_semantic}"
RUNNER_SRC="$ROOT_DIR/scripts/gpu/kretikos_cross_backend_cuda_runner.c"
RUNNER_BIN="$OUT_DIR/kretikos_cross_backend_cuda_runner"
VEC_CUBIN="$SEMANTIC_DIR/vec_add.cubin"
EPI_CUBIN="$SEMANTIC_DIR/epistemic_dual_output_f32.cubin"
VEC_STDOUT="$OUT_DIR/vec_add.runtime.txt"
EPI_STDOUT="$OUT_DIR/epistemic_dual_output_f32.runtime.txt"

mkdir -p "$OUT_DIR"

rel_path() {
  local p="$1"
  if [[ "$p" == "$ROOT_DIR/"* ]]; then
    printf '%s' "${p#$ROOT_DIR/}"
  else
    printf '%s' "$p"
  fi
}

sha_file() {
  sha256sum "$1" | awk '{print $1}'
}

size_file() {
  stat -c%s "$1" 2>/dev/null || stat -f%z "$1"
}

if [[ ! -s "$RUNNER_SRC" ]]; then
  echo "kretikos_cross_backend_cuda_runtime_gate: FAIL missing runner source: $RUNNER_SRC" >&2
  exit 1
fi

bash scripts/ci/kretikos_cross_backend_semantic_gate.sh >/dev/null

cc -O2 "$RUNNER_SRC" -ldl -lm -o "$RUNNER_BIN"

"$RUNNER_BIN" "$VEC_CUBIN" vec_add vec_add_f32 > "$VEC_STDOUT"
"$RUNNER_BIN" "$EPI_CUBIN" epistemic_dual_output_f32 epistemic_dual_output_f32 > "$EPI_STDOUT"

vec_runtime_pass=false
epi_runtime_pass=false
epi_value_runtime_pass=false
epi_eps_runtime_pass=false
epi_valid_runtime_pass=false
epi_provenance_runtime_pass=false
if grep -q 'status=pass' "$VEC_STDOUT" && grep -q 'max_abs_err=0' "$VEC_STDOUT"; then vec_runtime_pass=true; fi
if grep -q 'status=pass' "$EPI_STDOUT" && grep -q 'value_max_abs_err=0' "$EPI_STDOUT"; then epi_value_runtime_pass=true; fi
if grep -q 'status=pass' "$EPI_STDOUT" && grep -q 'eps_max_abs_err=0' "$EPI_STDOUT"; then epi_eps_runtime_pass=true; fi
if grep -q 'status=pass' "$EPI_STDOUT" && grep -q 'valid_mismatch=0' "$EPI_STDOUT"; then epi_valid_runtime_pass=true; fi
if grep -q 'status=pass' "$EPI_STDOUT" && grep -q 'prov_mismatch=0' "$EPI_STDOUT"; then epi_provenance_runtime_pass=true; fi
if [[ "$epi_value_runtime_pass" == true &&
      "$epi_eps_runtime_pass" == true &&
      "$epi_valid_runtime_pass" == true &&
      "$epi_provenance_runtime_pass" == true ]]; then
  epi_runtime_pass=true
fi

if [[ "$vec_runtime_pass" == true && "$epi_runtime_pass" == true ]]; then
  status="pass"
else
  status="fail"
fi

device_name="$(grep -m1 -o 'device_name=[^ ]*' "$VEC_STDOUT" | cut -d= -f2-)"
driver_version="$(grep -m1 -o 'driver_version=[0-9]*' "$VEC_STDOUT" | cut -d= -f2-)"
compute_capability="$(grep -m1 -o 'cc=[0-9][0-9]*\.[0-9][0-9]*' "$VEC_STDOUT" | cut -d= -f2-)"
epi_device_name="$(grep -m1 -o 'device_name=[^ ]*' "$EPI_STDOUT" | cut -d= -f2-)"
epi_driver_version="$(grep -m1 -o 'driver_version=[0-9]*' "$EPI_STDOUT" | cut -d= -f2-)"
epi_compute_capability="$(grep -m1 -o 'cc=[0-9][0-9]*\.[0-9][0-9]*' "$EPI_STDOUT" | cut -d= -f2-)"

if [[ -z "$device_name" || -z "$driver_version" || -z "$compute_capability" ||
      "$device_name" != "$epi_device_name" ||
      "$driver_version" != "$epi_driver_version" ||
      "$compute_capability" != "$epi_compute_capability" ]]; then
  echo "kretikos_cross_backend_cuda_runtime_gate: FAIL runtime device identity missing or inconsistent" >&2
  exit 1
fi

generated_at_utc="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

./bin/kretikos json-emit \
  --raw-json "artifacts={\"epistemic_dual_output_f32\":{\"cubin\":{\"bytes\":$(size_file "$EPI_CUBIN"),\"path\":\"$(rel_path "$EPI_CUBIN")\",\"sha256\":\"$(sha_file "$EPI_CUBIN")\"},\"stdout\":{\"bytes\":$(size_file "$EPI_STDOUT"),\"path\":\"$(rel_path "$EPI_STDOUT")\",\"sha256\":\"$(sha_file "$EPI_STDOUT")\"}},\"vec_add_f32\":{\"cubin\":{\"bytes\":$(size_file "$VEC_CUBIN"),\"path\":\"$(rel_path "$VEC_CUBIN")\",\"sha256\":\"$(sha_file "$VEC_CUBIN")\"},\"stdout\":{\"bytes\":$(size_file "$VEC_STDOUT"),\"path\":\"$(rel_path "$VEC_STDOUT")\",\"sha256\":\"$(sha_file "$VEC_STDOUT")\"}},\"runner\":{\"binary\":{\"bytes\":$(size_file "$RUNNER_BIN"),\"path\":\"$(rel_path "$RUNNER_BIN")\",\"sha256\":\"$(sha_file "$RUNNER_BIN")\"},\"source\":{\"bytes\":$(size_file "$RUNNER_SRC"),\"path\":\"$(rel_path "$RUNNER_SRC")\",\"sha256\":\"$(sha_file "$RUNNER_SRC")\"}}}" \
  --array-strings "boundaries=cuda_runtime_gate_for_ptx_side_only|does_not_claim_metal_runtime|does_not_claim_spirv_runtime|does_not_claim_general_backend_equivalence|runtime_oracles_are_vec_add_and_epistemic_value_eps_valid_provenance" \
  --bool "checks.epistemic_dual_output_f32_eps_runtime_pass=$epi_eps_runtime_pass" \
  --bool "checks.epistemic_dual_output_f32_provenance_runtime_pass=$epi_provenance_runtime_pass" \
  --bool "checks.epistemic_dual_output_f32_runtime_pass=$epi_runtime_pass" \
  --bool "checks.epistemic_dual_output_f32_valid_runtime_pass=$epi_valid_runtime_pass" \
  --bool "checks.epistemic_dual_output_f32_value_runtime_pass=$epi_value_runtime_pass" \
  --bool "checks.vec_add_f32_runtime_pass=$vec_runtime_pass" \
  --string "generated_at_utc=$generated_at_utc" \
  --string "runtime.compute_capability=$compute_capability" \
  --string "runtime.device_name=$device_name" \
  --string "runtime.driver_version=$driver_version" \
  --string "schema=sounio.kretikos.cross-backend-cuda-runtime.v1" \
  --array-strings "semantics=vec_add_f32|epistemic_dual_output_f32" \
  --string "status=$status" \
  > "$REPORT_JSON"

./bin/kretikos kaxi-validate-evidence "$REPORT_JSON" \
  --expect "status=pass" \
  --expect "checks.vec_add_f32_runtime_pass=true" \
  --expect "checks.epistemic_dual_output_f32_value_runtime_pass=true" \
  --expect "checks.epistemic_dual_output_f32_eps_runtime_pass=true" \
  --expect "checks.epistemic_dual_output_f32_valid_runtime_pass=true" \
  --expect "checks.epistemic_dual_output_f32_provenance_runtime_pass=true" \
  --expect "checks.epistemic_dual_output_f32_runtime_pass=true" >/dev/null

echo "kretikos_cross_backend_cuda_runtime_gate: PASS report=$(rel_path "$REPORT_JSON")"
