#!/usr/bin/env bash
# scripts/ci/ontology_multi_ontology_gate.sh
#
# CI gate for the round-13 multi-ontology EL+ role-aware closure drivers
# (artifacts/ontology-frontiers/multi-ontology/). Same protocol as
# scripts/ci/ontology_frontiers_gate.sh: for each driver this gate
#   (a) runs `./bin/souc check <file>` and requires `check: OK` in the output
#       (and no `parse error`),
#   (b) runs `./bin/souc run <file>` and requires an exact `ALL PASS`
#       output line.
#
# Kept SEPARATE from ontology_frontiers_gate.sh because that file (and the
# real-data/ tree it covers) was under an active claim of another lane
# when round 13 landed; this gate covers only the round-13 drivers.
#
# souc's process exit code is unreliable for both subcommands, so all
# verdicts are derived from captured stdout/stderr, never from $?.
# A per-file OK/FAIL line is printed; the gate exits 1 if any file fails.
#
# Runs from any cwd (all paths anchored at ROOT_DIR). Each `souc run`
# takes ~1-5 min (three GO cones resp. CL+UBERON, each with a full
# fixpoint and two ablation re-runs); a per-file timeout guards against
# hangs.
#
# Env overrides:
#   SOUC_BIN                          compiler wrapper (default: bin/souc)
#   ONTOLOGY_MULTI_RUN_TIMEOUT        per-file `souc run` timeout, seconds
#                                     (default: 900; ChEBI+PATO needs headroom)
#   ONTOLOGY_MULTI_REGENERATE=1       regenerate the packed data before running,
#                                     and assert it comes back byte-identical
#   ONTOLOGY_MULTI_NO_FETCH=1         never touch the network; a driver whose data
#                                     is missing is skipped instead of regenerated
#
# DATA.  Each driver read_file()s packed .txt files under artifacts/
# ontology-frontiers/multi-ontology/.  Those are GENERATED by gen_multi_data.py
# from the .owl inputs in downloads/, which fetch_downloads.sh obtains.  This gate
# now ensures its own data: if a driver's packed files are missing it regenerates
# them, so the generated artifacts need not be committed.
#
# Two of them cannot be regenerated.  chebi_packed.txt and pato_packed.txt come
# from gen_chebi_data.py, which needs downloads/chebi.owl and downloads/pato.owl,
# and no release of either is recorded anywhere in this repository for
# fetch_downloads.sh to pin (see its header).  When their data is absent the
# dependent drivers are SKIPPED with that reason, never silently passed.
#
# Exit 0 = all drivers pass. Exit 1 = at least one driver failed.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

SOUC_BIN="${SOUC_BIN:-$ROOT_DIR/bin/souc}"
RUN_TIMEOUT="${ONTOLOGY_MULTI_RUN_TIMEOUT:-900}"

# chebi_pato_elplus_driver.sio is deliberately ABSENT from this list and from
# the tree. Its inputs cannot be reconstructed: ChEBI's versionIRI names
# release 254, obo/chebi/254/chebi.owl returns 404, and the undated purl now
# serves a different release (measured 2026-08-24, recorded in
# artifacts/ontology-frontiers/multi-ontology/fetch_downloads.sh). The
# committed chebi_* artifacts came from an older, unrecorded release.
#
# It was carried here briefly and the gate SKIPped it and exited 1 -- correctly:
# a driver in the list that cannot run is a check that reports on nothing. The
# results it produced remain in CHEBI_PATO_RESULTS.md, labelled there as
# unreproducible, which is the honest place for them.
DRIVERS=(
    "artifacts/ontology-frontiers/multi-ontology/go_roots_elplus_driver.sio"
    "artifacts/ontology-frontiers/multi-ontology/obo_elplus_driver.sio"
    "artifacts/ontology-frontiers/multi-ontology/open_fillers_elplus_driver.sio"
    "artifacts/ontology-frontiers/multi-ontology/uberon_open_elplus_driver.sio"
)

DATA_DIR="$ROOT_DIR/artifacts/ontology-frontiers/multi-ontology"
REGENERATE="${ONTOLOGY_MULTI_REGENERATE:-0}"
NO_FETCH="${ONTOLOGY_MULTI_NO_FETCH:-0}"

# driver basename | packed files it reads | how to regenerate them
#   go / obo -> gen_multi_data.py --go-only / --obo-only
#   none     -> not regenerable from this repository (see the header)
DATA_FOR=(
    "go_roots_elplus_driver|go_bp_packed.txt go_cc_packed.txt go_mf_packed.txt|go"
    "obo_elplus_driver|cl_packed.txt uberon_packed.txt|obo"
    "chebi_pato_elplus_driver|chebi_packed.txt pato_packed.txt|none"
    "open_fillers_elplus_driver|cl_open_packed.txt pato_open_packed.txt|none"
    "uberon_open_elplus_driver|uberon_open_packed.txt|none"
)

TMP_DIR="$(mktemp -d /tmp/ontology-multi-gate.XXXXXX)"
trap 'rm -rf "$TMP_DIR"' EXIT

PASS=0
FAIL=0
SKIP=0

recipe_for() {   # driver basename -> "files|recipe", or non-zero if unlisted
    local want="$1" e n f r
    for e in "${DATA_FOR[@]}"; do
        IFS='|' read -r n f r <<<"$e"
        [[ "$n" == "$want" ]] && { printf '%s|%s' "$f" "$r"; return 0; }
    done
    return 1
}

run_generator() {   # recipe -> fetch inputs if needed, regenerate in place
    local recipe="$1" log="$TMP_DIR/gen.$1.log"
    if [[ "$NO_FETCH" != 1 ]]; then
        if ! ( cd "$DATA_DIR" && ./fetch_downloads.sh ) >"$TMP_DIR/fetch.log" 2>&1; then
            printf '[ontology-multi]   fetch failed (see %s)\n' "$TMP_DIR/fetch.log" >&2
            return 1
        fi
    fi
    printf '[ontology-multi]   regenerating (%s) ...\n' "$recipe"
    if ! ( cd "$DATA_DIR" && python3 gen_multi_data.py "--${recipe}-only" ) >"$log" 2>&1; then
        printf '[ontology-multi]   generator failed (see %s)\n' "$log" >&2
        return 1
    fi
    return 0
}

# 0 = data ready, 1 = unavailable (skip this driver), 2 = hard failure.
ensure_data() {
    local name="$1" spec files recipe f missing=0 before after
    spec="$(recipe_for "$name")" || return 0
    IFS='|' read -r files recipe <<<"$spec"

    for f in $files; do [[ -f "$DATA_DIR/$f" ]] || missing=1; done

    if [[ "$missing" == 1 ]]; then
        if [[ "$recipe" == none ]]; then
            # Name what is actually missing and how it is produced. This block
            # used to print the ChEBI explanation for EVERY driver: it told a
            # reader whose open_fillers run had lost cl_open_packed.txt that
            # gen_chebi_data.py needed downloads/chebi.owl, an ontology that
            # driver does not use. Three separate drivers were reported that
            # way, and the wrong explanation is why the data looked
            # irrecoverable when two of the three were a mechanical
            # regeneration away.
            printf '[ontology-multi] SKIP: %s — missing input data\n' "$name" >&2
            printf '[ontology-multi]   needs: %s\n' "$files" >&2
            local _m
            for _m in $files; do
                case "$_m" in
                    *_open_packed.txt)
                        printf '[ontology-multi]   %s: regenerate with\n' "$_m" >&2
                        printf '[ontology-multi]     python3 %s/gen_open_fillers_data.py %s\n' \
                            "$DATA_DIR" "${_m%_open_packed.txt}" >&2
                        ;;
                    chebi_*)
                        printf '[ontology-multi]   %s: NOT regenerable. ChEBI release 254 is a 404 and\n' "$_m" >&2
                        printf '[ontology-multi]     the undated purl serves a different release; the committed\n' >&2
                        printf '[ontology-multi]     artifacts came from an older, unrecorded one (fetch_downloads.sh).\n' >&2
                        ;;
                    *)
                        printf '[ontology-multi]   %s: no generator recorded for this input.\n' "$_m" >&2
                        ;;
                esac
            done
            return 1
        fi
        if [[ "$NO_FETCH" == 1 ]]; then
            printf '[ontology-multi] SKIP: %s — data missing, ONTOLOGY_MULTI_NO_FETCH=1\n' "$name" >&2
            return 1
        fi
        run_generator "$recipe" || return 2
        for f in $files; do
            if [[ ! -f "$DATA_DIR/$f" ]]; then
                printf '[ontology-multi] FAIL: %s — generator produced no %s\n' "$name" "$f" >&2
                return 2
            fi
        done
        return 0
    fi

    # Present. Optionally prove it is what the generator produces today.
    [[ "$REGENERATE" == 1 && "$recipe" != none ]] || return 0
    before="$TMP_DIR/$name.before"; after="$TMP_DIR/$name.after"
    ( cd "$DATA_DIR" && sha256sum $files ) >"$before" 2>/dev/null || return 0
    run_generator "$recipe" || return 2
    ( cd "$DATA_DIR" && sha256sum $files ) >"$after" 2>/dev/null || return 2
    if diff -q "$before" "$after" >/dev/null; then
        printf '[ontology-multi]   regenerated byte-identical: %s\n' "$files"
        return 0
    fi
    printf '[ontology-multi] FAIL: %s — regenerated data differs from the committed copy\n' "$name" >&2
    diff "$before" "$after" | sed 's/^/[ontology-multi]   /' >&2
    return 2
}

gate_file() {
    local rel="$1"
    local src="$ROOT_DIR/$rel"
    local name
    name="$(basename "$rel" .sio)"
    local problems=0

    if [[ ! -f "$src" ]]; then
        printf '[ontology-multi] FAIL: %s (missing file: %s)\n' "$name" "$rel" >&2
        FAIL=$((FAIL + 1))
        return
    fi

    ensure_data "$name"
    case $? in
        1) SKIP=$((SKIP + 1)); return ;;
        2) FAIL=$((FAIL + 1)); return ;;
    esac

    # (a) souc check — exit code unreliable, grep stdout.
    local check_log="$TMP_DIR/$name.check.log"
    "$SOUC_BIN" check "$src" >"$check_log" 2>&1 || true
    if grep -Fq 'parse error' "$check_log"; then
        printf '[ontology-multi]   check: parse error (see %s)\n' "$check_log" >&2
        problems=$((problems + 1))
    elif ! grep -Fq 'check: OK' "$check_log"; then
        printf '[ontology-multi]   check: missing "check: OK" (see %s)\n' "$check_log" >&2
        problems=$((problems + 1))
    fi

    # (b) souc run — exit code unreliable, require an exact ALL PASS line.
    local run_log="$TMP_DIR/$name.run.log"
    timeout "$RUN_TIMEOUT" "$SOUC_BIN" run "$src" >"$run_log" 2>&1 || true
    if ! grep -Fxq 'ALL PASS' "$run_log"; then
        printf '[ontology-multi]   run: missing exact "ALL PASS" line (see %s)\n' "$run_log" >&2
        problems=$((problems + 1))
    fi

    if [[ "$problems" -eq 0 ]]; then
        PASS=$((PASS + 1))
        printf '[ontology-multi] OK:   %s\n' "$rel"
    else
        FAIL=$((FAIL + 1))
        printf '[ontology-multi] FAIL: %s (%d problem(s))\n' "$rel" "$problems" >&2
    fi
}

echo "[ontology-multi] souc=$SOUC_BIN"
echo "[ontology-multi] drivers=${#DRIVERS[@]} run_timeout=${RUN_TIMEOUT}s"

if [[ ! -x "$SOUC_BIN" ]]; then
    echo "[ontology-multi] ERROR: souc wrapper not executable: $SOUC_BIN" >&2
    exit 1
fi

for rel in "${DRIVERS[@]}"; do
    gate_file "$rel"
done

printf '[ontology-multi] results: %d passed, %d failed, %d skipped\n' "$PASS" "$FAIL" "$SKIP"

if [[ "$FAIL" -gt 0 ]]; then
    exit 1
fi
exit 0
