// AUTO-GENERATED by scripts/sync-artifact-status.mjs
// Do not edit manually. Regenerate with: npm run sync:artifacts
// Generated at: 2026-10-06T11:53:41.066Z

export type EpistemicLevel = "verified" | "beta" | "active" | "stub" | "blocked" | "unknown";

export interface ArtifactStatusEntry {
  label: string;
  level: EpistemicLevel;
  reason: string;
  artifact: string;
}

export interface LaneEntry {
  id: string;
  label: string;
  level: EpistemicLevel;
  reason?: string;
  metrics?: Record<string, number>;
  blockers?: string[];
}

export interface HonestStatusItem {
  title: string;
  detail: string;
}

export interface PublicContract {
  sources: Record<string, string>;
  versions: {
    checkedArtifact: string;
    readmeBadge: string | null;
    lspRelease: string;
  };
  defaultWorkflow: {
    launcher: string;
    backend: string;
    summary: string;
  };
  bootstrap: {
    stage0Lines: number | null;
    stage0Path: string;
    fixedPointChain: string;
    historicalNote: string;
    recordedSha256: string | null;
    recordedSizeKb: number | null;
    cycleParity: boolean | null;
    artifact: string;
  };
  metrics: {
    stdlibReliabilityGate: {
      pass: number;
      fail: number;
      skip: number;
      total: number;
      label: string;
      artifact: string;
    };
    fullTestSuite: {
      pass: number;
      total: number;
      label: string;
      artifact: string;
    } | null;
    stdlibInventoryFiles: number | null;
    selfHostedSourceFiles: number | null;
    selfHostedSourceLines: number | null;
    scienceLanes: number;
    hyperLanes: number;
  };
  honestStatus: {
    works: HonestStatusItem[];
    scaffolding: HonestStatusItem[];
    missing: HonestStatusItem[];
  };
}

export interface ArtifactStatus {
  generatedAt: string;
  repoPath: string;
  publicContract: PublicContract;
  compiler: Record<string, ArtifactStatusEntry & { lanes?: LaneEntry[]; totals?: Record<string, number> }>;
  stdlib: Record<string, ArtifactStatusEntry & { lanes?: LaneEntry[]; totals?: Record<string, number> }>;
}

export const artifactStatus: ArtifactStatus = {
  "generatedAt": "2026-10-06T11:53:41.066Z",
  "repoPath": "artifacts/",
  "publicContract": {
    "sources": {
      "readme": "README.md#honest-status",
      "limitations": "docs/compiler/KNOWN_LIMITATIONS.md",
      "minimumViable": "docs/guide/MINIMUM_VIABLE_SOUNIO.md"
    },
    "versions": {
      "checkedArtifact": "Madaros v0.80.0",
      "readmeBadge": "2.1.0",
      "lspRelease": "sounio-lsp-v0.3.0-r1"
    },
    "defaultWorkflow": {
      "launcher": "bin/souc",
      "backend": "self-hosted native x86-64 ELF (Linux only)",
      "summary": "The public onboarding path is the checked self-hosted launcher. It type-checks and compiles to host binaries — no Rust/Cargo build step required for the default workflow."
    },
    "bootstrap": {
      "stage0Lines": 2792,
      "stage0Path": "bootstrap/stage0.c",
      "fixedPointChain": "checked bin/souc-linux-x86_64 → gen1 → gen2 → gen3 (gen2 == gen3)",
      "historicalNote": "stage0.c is the original C bootstrap; the reproducible fixed-point ceremony uses the checked self-hosted binary.",
      "recordedSha256": "7b588877f870e0011a9ace62eb12c7cd",
      "recordedSizeKb": 741,
      "cycleParity": true,
      "artifact": "CHANGELOG.md + artifacts/omega/selfhost_verification_report.v1.json"
    },
    "metrics": {
      "stdlibReliabilityGate": {
        "pass": 196,
        "fail": 165,
        "skip": 172,
        "total": 533,
        "label": "Stdlib end-to-end",
        "artifact": "artifacts/stdlib/stdlib_e2e_result.v1.json"
      },
      "fullTestSuite": null,
      "stdlibInventoryFiles": 927,
      "selfHostedSourceFiles": 172,
      "selfHostedSourceLines": 105058,
      "scienceLanes": 2,
      "hyperLanes": 7
    },
    "honestStatus": {
      "works": [
        {
          "title": "Epistemic core",
          "detail": "Knowledge[T] with GUM propagation, provenance tracking, and compile-time confidence gates (vancomycin fixtures)"
        },
        {
          "title": "Self-hosted compiler",
          "detail": "Fixed-point verified (cycle parity=true); 172 self-hosted source files"
        },
        {
          "title": "Algebra",
          "detail": "Clifford, Cayley-Dickson, octonions — 168 theorem verified computationally"
        },
        {
          "title": "Native codegen",
          "detail": "Linux x86-64 static ELF only (TOUR.md section 6); no macOS, Windows or AArch64 target ships"
        },
        {
          "title": "Core stdlib gate",
          "detail": "Stdlib end-to-end: 196 of 533 test programs pass (165 fail, 172 skipped), measured 2026-10-06 with `bash scripts/stdlib/run_stdlib_e2e.sh`; result in `artifacts/stdlib/stdlib_e2e_result.v1.json`"
        },
        {
          "title": "Optimizer",
          "detail": "1,000+ e-graph rewrite rules with FAIL=0 in optimizer tests"
        },
        {
          "title": "Language server",
          "detail": "LSP smoke gate pass; hover, defs, refs, rename, formatting, semantic tokens"
        },
        {
          "title": "Closure literals",
          "detail": "Named function refs and closure tests in tests/run-pass/ (see README resolved list)"
        }
      ],
      "scaffolding": [
        {
          "title": "Theorem prover",
          "detail": "Large arena and data structures; full inference logic not complete"
        },
        {
          "title": "Epistemic modules",
          "detail": "Many modules are signatures with minimal bodies (~70% scaffolding)"
        },
        {
          "title": "Neural networks",
          "detail": "Quaternion/octonion NN lanes exist but are not all end-to-end stable"
        },
        {
          "title": "Genomics",
          "detail": "Several files are stubs disabled on parser limitations"
        },
        {
          "title": "Async runtime",
          "detail": "Self-hosted async tests pass per KNOWN_LIMITATIONS.md; broader runtime integration still partial"
        },
        {
          "title": "Geometry engine",
          "detail": "Extended geometry paths disabled; core engine partial"
        }
      ],
      "missing": [
        {
          "title": "Epistemic ODE solver (general RHS)",
          "detail": "Exponential decay works; general RHS needed for full PBPK epistemic integration"
        },
        {
          "title": "Ontology federation",
          "detail": "Local ontology work exists; 15M-term federated query not implemented"
        },
        {
          "title": "General GPU backend",
          "detail": "`souc build --backend gpu` emits PTX for a skeleton of named kernel patterns (empty bodies), not a general GPU backend (TOUR.md section 6)"
        },
        {
          "title": "Windows, macOS and AArch64",
          "detail": "Not targeted: the compiler emits Linux x86-64 static ELF only"
        },
        {
          "title": "WASM backend",
          "detail": "Blocked draft (#2237); not shipped"
        },
        {
          "title": "Checked launcher REPL",
          "detail": "README Known Limitations: bin/souc does not expose repl; separate REPL beta exists outside default lane"
        }
      ]
    }
  },
  "compiler": {
    "core": {
      "label": "Lexer / Parser / Type Checker",
      "level": "verified",
      "reason": "Production-grade per KNOWN_LIMITATIONS.md; no active known bugs",
      "artifact": "docs/compiler/KNOWN_LIMITATIONS.md"
    },
    "nativeBackend": {
      "label": "Native Backend (x86-64 ELF)",
      "level": "verified",
      "reason": "selftest_passed=true, scalar_smoke_present=true, fail_closed=true",
      "artifact": "artifacts/omega/native_backend_v2_gate.v1.json"
    },
    "selfHosted": {
      "label": "Self-Hosted Compiler (default path)",
      "level": "verified",
      "reason": "172 files, 105058 lines, cycle parity=true",
      "artifact": "artifacts/omega/selfhost_verification_report.v1.json"
    },
    "cranelift": {
      "label": "Cranelift JIT (retired)",
      "level": "stub",
      "reason": "No longer shipped since 2.1.0 (CHANGELOG.md). Madaros native x86-64 is the only shipped engine.",
      "artifact": "CHANGELOG.md"
    },
    "lsp": {
      "label": "LSP Server",
      "level": "verified",
      "reason": "smoke status=pass, strict_no_rust=true",
      "artifact": "artifacts/omega/lsp_smoke_status.v1.json"
    },
    "gpu": {
      "label": "GPU Codegen (PTX)",
      "level": "blocked",
      "reason": "status=fail, blockers=[remote_env_missing]",
      "artifact": "artifacts/omega/gpu_runtime_attest_gate.v1.json"
    },
    "bootstrap": {
      "label": "Bootstrap Chain",
      "level": "unknown",
      "reason": "full_concat=pass, knowledge_bootstrap=pass",
      "artifact": "artifacts/omega/bootstrap_full_gate_status.v1.json"
    }
  },
  "stdlib": {
    "reliability": {
      "label": "Core Standard Library",
      "level": "unknown",
      "totals": {
        "pass": 196,
        "fail": 165,
        "skip": 172,
        "total": 533
      },
      "reason": "Stdlib end-to-end: 196 of 533 test programs pass (165 fail, 172 skipped), measured 2026-10-06 with `bash scripts/stdlib/run_stdlib_e2e.sh`; result in `artifacts/stdlib/stdlib_e2e_result.v1.json`",
      "artifact": "artifacts/stdlib/stdlib_e2e_result.v1.json"
    },
    "scienceLanes": {
      "label": "Scientific Pipelines",
      "level": "verified",
      "reason": "lanes=2, status_summary=pass",
      "lanes": [
        {
          "id": "fmri",
          "label": "fmri",
          "level": "verified",
          "metrics": {
            "nifti1_status": 1,
            "nifti2_status": 1,
            "qc_fd_mean": 0.236667,
            "qc_fd_max": 0.3,
            "qc_scrub_fraction": 0.5,
            "qc_tsnr_median": 2.469027,
            "qc_dvars_median": 8,
            "fc_r": 0.664038,
            "fc_ci_width": 1.813059,
            "atlas_coverage_ratio": 0.068966,
            "uncertainty_score": 1.669525
          },
          "reason": "golden comparison pass"
        },
        {
          "id": "darwin_pbpk",
          "label": "darwin_pbpk",
          "level": "verified",
          "metrics": {
            "cmax": 1,
            "auc": 0.011137,
            "half_life": 0.571306,
            "clearance": 89.787087,
            "vdss": 74.02,
            "invariants_ok": 1
          },
          "reason": "golden comparison pass"
        }
      ],
      "artifact": "artifacts/stdlib/stdlib_science_pipeline_status.v1.json"
    },
    "hyperLanes": {
      "label": "Hyper-Execution Neural Lanes",
      "level": "verified",
      "reason": "lanes=7, status_summary=pass",
      "lanes": [
        {
          "id": "nn",
          "label": "nn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "onn",
          "label": "onn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "qnn",
          "label": "qnn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "snn",
          "label": "snn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "spnn",
          "label": "spnn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "quantnn",
          "label": "quantnn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "math",
          "label": "math",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        }
      ],
      "artifact": "artifacts/stdlib/stdlib_hyper_execution_status.v1.json"
    }
  }
};

export const publicContract = artifactStatus.publicContract;

export function levelColor(level: EpistemicLevel): string {
  switch (level) {
    case "verified": return "var(--color-accent-gold)";
    case "beta": return "var(--color-accent-teal)";
    case "active": return "var(--color-accent-orange)";
    case "stub": return "var(--color-accent-purple)";
    case "blocked": return "var(--color-accent-red)";
    case "unknown": default: return "var(--color-text-tertiary)";
  }
}

export function levelLabel(level: EpistemicLevel): string {
  switch (level) {
    case "verified": return "Verified";
    case "beta": return "Beta";
    case "active": return "In Progress";
    case "stub": return "Stub";
    case "blocked": return "Blocked";
    case "unknown": default: return "Unknown";
  }
}

export function levelIcon(level: EpistemicLevel): string {
  switch (level) {
    case "verified": return "✓";
    case "beta": return "β";
    case "active": return "◐";
    case "stub": return "⊘";
    case "blocked": return "✕";
    case "unknown": default: return "?";
  }
}
