// AUTO-GENERATED by scripts/sync-artifact-status.mjs
// Do not edit manually. Regenerate with: npm run sync:artifacts
// Generated at: 2026-05-07T19:10:05.543Z

export type EpistemicLevel = "verified" | "beta" | "active" | "stub" | "blocked" | "unknown";

export interface ArtifactStatusEntry {
  label: string;
  level: EpistemicLevel;
  reason: string;
  artifact: string;
}

export interface LaneEntry {
  id: string;
  label: string;
  level: EpistemicLevel;
  reason?: string;
  metrics?: Record<string, number>;
  blockers?: string[];
}

export interface ArtifactStatus {
  generatedAt: string;
  repoPath: string;
  compiler: Record<string, ArtifactStatusEntry & { lanes?: LaneEntry[]; totals?: Record<string, number> }>;
  stdlib: Record<string, ArtifactStatusEntry & { lanes?: LaneEntry[]; totals?: Record<string, number> }>;
}

export const artifactStatus: ArtifactStatus = {
  "generatedAt": "2026-05-07T19:10:05.543Z",
  "repoPath": "artifacts/",
  "compiler": {
    "core": {
      "label": "Lexer / Parser / Type Checker",
      "level": "verified",
      "reason": "Production-grade per KNOWN_LIMITATIONS.md; no active known bugs",
      "artifact": "docs/compiler/KNOWN_LIMITATIONS.md"
    },
    "nativeBackend": {
      "label": "Native Backend (ELF/Mach-O/PE)",
      "level": "verified",
      "reason": "selftest_passed=true, scalar_smoke_present=true, fail_closed=true",
      "artifact": "artifacts/omega/native_backend_v2_gate.v1.json"
    },
    "cranelift": {
      "label": "Cranelift JIT",
      "level": "verified",
      "reason": "Enabled in checked artifact; 81/86 stdlib reliability tests pass",
      "artifact": "artifacts/stdlib/stdlib_reliability_status.v1.json"
    },
    "llvm": {
      "label": "LLVM Backend",
      "level": "verified",
      "reason": "Production per KNOWN_LIMITATIONS.md; wired via `--backend llvm`",
      "artifact": "docs/compiler/KNOWN_LIMITATIONS.md"
    },
    "selfHosted": {
      "label": "Self-Hosted Compiler",
      "level": "verified",
      "reason": "172 files, 105058 lines, cycle parity=true",
      "artifact": "artifacts/omega/selfhost_verification_report.v1.json"
    },
    "lsp": {
      "label": "LSP Server",
      "level": "verified",
      "reason": "smoke status=pass, strict_no_rust=true",
      "artifact": "artifacts/omega/lsp_smoke_status.v1.json"
    },
    "gpu": {
      "label": "GPU Codegen (PTX)",
      "level": "blocked",
      "reason": "status=fail, blockers=[remote_env_missing]",
      "artifact": "artifacts/omega/gpu_runtime_attest_gate.v1.json"
    },
    "bootstrap": {
      "label": "Bootstrap Chain",
      "level": "unknown",
      "reason": "full_concat=pass, knowledge_bootstrap=pass",
      "artifact": "artifacts/omega/bootstrap_full_gate_status.v1.json"
    }
  },
  "stdlib": {
    "reliability": {
      "label": "Core Standard Library",
      "level": "verified",
      "totals": {
        "pass": 224,
        "fail": 0,
        "skip": 24,
        "total": 248
      },
      "reason": "224/248 tests pass, 24 skipped",
      "artifact": "artifacts/stdlib/stdlib_reliability_status.v1.json"
    },
    "scienceLanes": {
      "label": "Scientific Pipelines",
      "level": "verified",
      "reason": "lanes=2, status_summary=pass",
      "lanes": [
        {
          "id": "fmri",
          "label": "fmri",
          "level": "verified",
          "metrics": {
            "nifti1_status": 1,
            "nifti2_status": 1,
            "qc_fd_mean": 0.236667,
            "qc_fd_max": 0.3,
            "qc_scrub_fraction": 0.5,
            "qc_tsnr_median": 2.469027,
            "qc_dvars_median": 8,
            "fc_r": 0.664038,
            "fc_ci_width": 1.813059,
            "atlas_coverage_ratio": 0.068966,
            "uncertainty_score": 1.669525
          },
          "reason": "golden comparison pass"
        },
        {
          "id": "darwin_pbpk",
          "label": "darwin_pbpk",
          "level": "verified",
          "metrics": {
            "cmax": 1,
            "auc": 0.011137,
            "half_life": 0.571306,
            "clearance": 89.787087,
            "vdss": 74.02,
            "invariants_ok": 1
          },
          "reason": "golden comparison pass"
        }
      ],
      "artifact": "artifacts/stdlib/stdlib_science_pipeline_status.v1.json"
    },
    "hyperLanes": {
      "label": "Hyper-Execution Neural Lanes",
      "level": "verified",
      "reason": "lanes=7, status_summary=pass",
      "lanes": [
        {
          "id": "nn",
          "label": "nn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "onn",
          "label": "onn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "qnn",
          "label": "qnn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "snn",
          "label": "snn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "spnn",
          "label": "spnn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "quantnn",
          "label": "quantnn",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        },
        {
          "id": "math",
          "label": "math",
          "level": "verified",
          "reason": "ok",
          "blockers": []
        }
      ],
      "artifact": "artifacts/stdlib/stdlib_hyper_execution_status.v1.json"
    }
  }
};

export function levelColor(level: EpistemicLevel): string {
  switch (level) {
    case "verified": return "var(--color-accent-gold)";
    case "beta": return "var(--color-accent-teal)";
    case "active": return "var(--color-accent-orange)";
    case "stub": return "var(--color-accent-purple)";
    case "blocked": return "var(--color-accent-red)";
    case "unknown": default: return "var(--color-text-tertiary)";
  }
}

export function levelLabel(level: EpistemicLevel): string {
  switch (level) {
    case "verified": return "Verified";
    case "beta": return "Beta";
    case "active": return "In Progress";
    case "stub": return "Stub";
    case "blocked": return "Blocked";
    case "unknown": default: return "Unknown";
  }
}

export function levelIcon(level: EpistemicLevel): string {
  switch (level) {
    case "verified": return "✓";
    case "beta": return "β";
    case "active": return "◐";
    case "stub": return "⊘";
    case "blocked": return "✕";
    case "unknown": default: return "?";
  }
}
