//! QIR Shim + Quantum Conformance Telemetry for Sounio Omega Sprint 1.
//!
//! This module emits a lightweight QIR-compatible textual shim from existing
//! `QuantumCircuit` structures and evaluates statistical conformance for
//! quantum runs using KS-test p-values + 95% interval coverage.

use super::circuit::QuantumCircuit;
use super::gates::GateType;
use serde::{Deserialize, Serialize};

const QIR_SHIM_SCHEMA: &str = "sounio.quantum.qir-shim.v1";
const QIR_TELEMETRY_SCHEMA: &str = "sounio.quantum.conformance.v1";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QirShimArtifact {
    pub schema: String,
    pub qubit_count: usize,
    pub gate_count: usize,
    pub calibration_digest: String,
    pub circuit_digest: String,
    pub qir: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuantumConformanceThresholds {
    pub ks_pvalue_min: f64,
    pub coverage_range: (f64, f64),
    pub min_shots: u32,
}

impl Default for QuantumConformanceThresholds {
    fn default() -> Self {
        Self {
            ks_pvalue_min: 0.05,
            coverage_range: (0.90, 0.98),
            min_shots: 50,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuantumConformanceTelemetry {
    pub schema: String,
    pub shots: u32,
    pub ks_pvalue: f64,
    pub coverage_95: f64,
    pub calibration_digest: String,
    pub circuit_digest: String,
    pub conformant: bool,
}

/// Emit a minimal QIR-compatible shim from an in-memory quantum circuit.
///
/// The result is intentionally conservative and backend-agnostic: it captures
/// operations and metadata so the pipeline can record provenance + conformance
/// without committing to a specific vendor runtime.
pub fn emit_qir_shim(
    circuit: &QuantumCircuit,
    calibration_digest: &str,
    circuit_digest: &str,
) -> QirShimArtifact {
    let mut lines = Vec::new();
    lines.push("; QIR shim generated by Sounio Omega".to_string());
    lines.push("; module flags: qir_profile=base".to_string());
    lines.push(format!("; qubits={}", circuit.num_qubits));
    lines.push("define void @sounio__qir__entry() {".to_string());

    for (idx, gate) in circuit.gates.iter().enumerate() {
        let opname = gate_name(gate.gate_type);
        let mut args = Vec::new();
        for q in &gate.controls {
            args.push(format!("%ctrl{}", q));
        }
        for q in &gate.targets {
            args.push(format!("%q{}", q));
        }
        for p in &gate.params {
            args.push(format!("{:.17}", p));
        }
        lines.push(format!(
            "  ; gate#{}\n  call void @qir__qis__{}__body({})",
            idx,
            opname,
            args.join(", ")
        ));
    }

    lines.push("  ret void".to_string());
    lines.push("}".to_string());

    QirShimArtifact {
        schema: QIR_SHIM_SCHEMA.to_string(),
        qubit_count: circuit.num_qubits,
        gate_count: circuit.gates.len(),
        calibration_digest: calibration_digest.to_string(),
        circuit_digest: circuit_digest.to_string(),
        qir: lines.join("\n"),
    }
}

fn gate_name(g: GateType) -> &'static str {
    match g {
        GateType::Identity => "id",
        GateType::PauliX => "x",
        GateType::PauliY => "y",
        GateType::PauliZ => "z",
        GateType::Hadamard => "h",
        GateType::S => "s",
        GateType::Sdg => "sdg",
        GateType::T => "t",
        GateType::Tdg => "tdg",
        GateType::SqrtX => "sx",
        GateType::RX => "rx",
        GateType::RY => "ry",
        GateType::RZ => "rz",
        GateType::Phase => "phase",
        GateType::U1 => "u1",
        GateType::U2 => "u2",
        GateType::U3 => "u3",
        GateType::CNOT => "cnot",
        GateType::CZ => "cz",
        GateType::SWAP => "swap",
        GateType::ISwap => "iswap",
        GateType::CRX => "crx",
        GateType::CRY => "cry",
        GateType::CRZ => "crz",
        GateType::CPhase => "cphase",
        GateType::Toffoli => "ccx",
        GateType::Fredkin => "cswap",
    }
}

pub fn evaluate_quantum_conformance(
    reference: &[f64],
    candidate: &[f64],
    shots: u32,
    thresholds: &QuantumConformanceThresholds,
    calibration_digest: &str,
    circuit_digest: &str,
) -> QuantumConformanceTelemetry {
    let ks_pvalue = ks_two_sample_pvalue(reference, candidate);
    let coverage_95 = interval_coverage_95(reference, candidate);
    let (cov_lo, cov_hi) = thresholds.coverage_range;

    let conformant = shots >= thresholds.min_shots
        && ks_pvalue >= thresholds.ks_pvalue_min
        && coverage_95 >= cov_lo
        && coverage_95 <= cov_hi;

    QuantumConformanceTelemetry {
        schema: QIR_TELEMETRY_SCHEMA.to_string(),
        shots,
        ks_pvalue,
        coverage_95,
        calibration_digest: calibration_digest.to_string(),
        circuit_digest: circuit_digest.to_string(),
        conformant,
    }
}

/// Two-sample Kolmogorov-Smirnov test p-value approximation.
///
/// Uses the standard asymptotic series with finite-sample correction.
pub fn ks_two_sample_pvalue(reference: &[f64], candidate: &[f64]) -> f64 {
    if reference.is_empty() || candidate.is_empty() {
        return 0.0;
    }

    let mut a = reference.to_vec();
    let mut b = candidate.to_vec();
    a.sort_by(f64::total_cmp);
    b.sort_by(f64::total_cmp);

    let mut i = 0usize;
    let mut j = 0usize;
    let mut d_max = 0.0;

    while i < a.len() && j < b.len() {
        let x = a[i].min(b[j]);
        while i < a.len() && a[i] <= x {
            i += 1;
        }
        while j < b.len() && b[j] <= x {
            j += 1;
        }
        let fa = i as f64 / a.len() as f64;
        let fb = j as f64 / b.len() as f64;
        let d = (fa - fb).abs();
        if d > d_max {
            d_max = d;
        }
    }

    let n = a.len() as f64;
    let m = b.len() as f64;
    let n_eff = (n * m) / (n + m);
    if n_eff <= 0.0 {
        return 0.0;
    }

    let lambda = (n_eff.sqrt() + 0.12 + 0.11 / n_eff.sqrt()) * d_max;
    let mut series = 0.0;
    for k in 1..=64 {
        let kf = k as f64;
        let term = (-2.0 * kf * kf * lambda * lambda).exp();
        if k % 2 == 1 {
            series += term;
        } else {
            series -= term;
        }
    }

    (2.0 * series).clamp(0.0, 1.0)
}

pub fn interval_coverage_95(reference: &[f64], candidate: &[f64]) -> f64 {
    if reference.is_empty() || candidate.is_empty() {
        return 0.0;
    }

    let mut ref_sorted = reference.to_vec();
    ref_sorted.sort_by(f64::total_cmp);

    let lo = quantile_sorted(&ref_sorted, 0.025);
    let hi = quantile_sorted(&ref_sorted, 0.975);

    let inside = candidate.iter().filter(|x| **x >= lo && **x <= hi).count();
    inside as f64 / candidate.len() as f64
}

fn quantile_sorted(sorted: &[f64], q: f64) -> f64 {
    if sorted.is_empty() {
        return 0.0;
    }
    let clamped = q.clamp(0.0, 1.0);
    let pos = clamped * (sorted.len().saturating_sub(1) as f64);
    let lo = pos.floor() as usize;
    let hi = pos.ceil() as usize;
    if lo == hi {
        sorted[lo]
    } else {
        let w = pos - lo as f64;
        sorted[lo] * (1.0 - w) + sorted[hi] * w
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::quantum::gates::Gate;

    #[test]
    fn qir_shim_contains_header_and_gates() {
        let mut circuit = QuantumCircuit::new(2);
        circuit.add_gate(Gate::h(0));
        circuit.add_gate(Gate::cnot(0, 1));

        let artifact = emit_qir_shim(&circuit, "calib_abc", "circ_123");
        assert_eq!(artifact.schema, "sounio.quantum.qir-shim.v1");
        assert!(artifact.qir.contains("@sounio__qir__entry"));
        assert!(artifact.qir.contains("qir__qis__h__body"));
        assert!(artifact.qir.contains("qir__qis__cnot__body"));
    }

    #[test]
    fn conformance_passes_for_close_distributions() {
        let reference = vec![0.10, 0.20, 0.15, 0.18, 0.22, 0.17, 0.19, 0.21, 0.16, 0.14];
        let candidate = vec![0.11, 0.19, 0.16, 0.17, 0.23, 0.18, 0.20, 0.22, 0.15, 0.13];

        let telemetry = evaluate_quantum_conformance(
            &reference,
            &candidate,
            64,
            &QuantumConformanceThresholds::default(),
            "calib",
            "circ",
        );
        assert!(telemetry.ks_pvalue >= 0.05);
        assert!(telemetry.coverage_95 >= 0.90);
        assert!(telemetry.conformant);
    }

    #[test]
    fn conformance_fails_for_shifted_distribution() {
        let reference = vec![0.10, 0.12, 0.11, 0.13, 0.09, 0.10, 0.11, 0.12, 0.10, 0.11];
        let candidate = vec![0.70, 0.72, 0.69, 0.71, 0.73, 0.74, 0.68, 0.70, 0.72, 0.71];

        let telemetry = evaluate_quantum_conformance(
            &reference,
            &candidate,
            64,
            &QuantumConformanceThresholds::default(),
            "calib",
            "circ",
        );
        assert!(!telemetry.conformant);
    }
}
