//! Octonion Neural Network (ONN) — MNIST Toy Training Integration Test
//!
//! Trains a small two-layer ONN on a 100-sample balanced MNIST subset
//! (80 train / 20 test, 8 per digit / 2 per digit) to demonstrate the
//! full ONN pipeline on real image data.
//!
//! Architecture:
//!   Input:  98 octonions (784 pixels / 8 components)
//!   Hidden: OctLinearLayer(98, 16) + ReLU  (frozen random projection)
//!   Output: OctLinearLayer(16, 10)         (trained via finite-difference SGD)
//!
//! The hidden layer is frozen as a random projection (Extreme Learning Machine
//! style), which is standard practice when using finite-difference gradients.
//! Only the output layer parameters are optimized, keeping the FD cost tractable:
//! 170 octonion params = 1360 scalar perturbations per gradient step.
//!
//! Assertions:
//!   1. Training loss decreases from epoch 0 to final epoch
//!   2. Test accuracy > 10% (above random baseline for 10 classes)
//!   3. All gradients are finite throughout training
//!
//! Reproduction:
//!   cargo test -p souc --test integration_onn_mnist_toy -- --nocapture

#[cfg(test)]
mod onn_mnist_toy {

    // ====================================================================
    // Embedded MNIST subset (80 train + 20 test, balanced across 0-9)
    // Generated by: python3 scripts/extract_mnist_subset.py
    // ====================================================================

    const MNIST_SUBSET: &[u8] = include_bytes!("data/mnist_100.bin");

    // ====================================================================
    // Octonion type and operations (matches stdlib/math/octonion.sio)
    // ====================================================================

    #[derive(Debug, Clone, Copy)]
    struct Octonion {
        e: [f64; 8],
    }

    impl Octonion {
        fn new(e0: f64, e1: f64, e2: f64, e3: f64, e4: f64, e5: f64, e6: f64, e7: f64) -> Self {
            Octonion {
                e: [e0, e1, e2, e3, e4, e5, e6, e7],
            }
        }

        fn zero() -> Self {
            Octonion { e: [0.0; 8] }
        }

        fn norm_sq(&self) -> f64 {
            self.e.iter().map(|x| x * x).sum()
        }

        fn add(&self, other: &Self) -> Self {
            let mut r = Octonion::zero();
            for i in 0..8 {
                r.e[i] = self.e[i] + other.e[i];
            }
            r
        }

        fn sub(&self, other: &Self) -> Self {
            let mut r = Octonion::zero();
            for i in 0..8 {
                r.e[i] = self.e[i] - other.e[i];
            }
            r
        }

        fn scale(&self, s: f64) -> Self {
            let mut r = Octonion::zero();
            for i in 0..8 {
                r.e[i] = self.e[i] * s;
            }
            r
        }

        /// Cayley-Dickson multiplication (120 FLOPs)
        fn mul(&self, other: &Self) -> Self {
            let (a0, a1, a2, a3, a4, a5, a6, a7) = (
                self.e[0], self.e[1], self.e[2], self.e[3], self.e[4], self.e[5], self.e[6],
                self.e[7],
            );
            let (b0, b1, b2, b3, b4, b5, b6, b7) = (
                other.e[0], other.e[1], other.e[2], other.e[3], other.e[4], other.e[5], other.e[6],
                other.e[7],
            );

            Octonion::new(
                a0 * b0 - a1 * b1 - a2 * b2 - a3 * b3 - a4 * b4 - a5 * b5 - a6 * b6 - a7 * b7,
                a0 * b1 + a1 * b0 + a2 * b3 - a3 * b2 + a4 * b5 - a5 * b4 - a6 * b7 + a7 * b6,
                a0 * b2 - a1 * b3 + a2 * b0 + a3 * b1 + a4 * b6 + a5 * b7 - a6 * b4 - a7 * b5,
                a0 * b3 + a1 * b2 - a2 * b1 + a3 * b0 + a4 * b7 - a5 * b6 + a6 * b5 - a7 * b4,
                a0 * b4 - a1 * b5 - a2 * b6 - a3 * b7 + a4 * b0 + a5 * b1 + a6 * b2 + a7 * b3,
                a0 * b5 + a1 * b4 - a2 * b7 + a3 * b6 - a4 * b1 + a5 * b0 - a6 * b3 + a7 * b2,
                a0 * b6 + a1 * b7 + a2 * b4 - a3 * b5 - a4 * b2 + a5 * b3 + a6 * b0 - a7 * b1,
                a0 * b7 - a1 * b6 + a2 * b5 + a3 * b4 - a4 * b3 - a5 * b2 + a6 * b1 + a7 * b0,
            )
        }

        /// Per-component ReLU
        fn relu(&self) -> Self {
            let mut r = Octonion::zero();
            for i in 0..8 {
                r.e[i] = if self.e[i] > 0.0 { self.e[i] } else { 0.0 };
            }
            r
        }
    }

    // ====================================================================
    // PRNG (same LCG as exhaustive tests for reproducibility)
    // ====================================================================

    struct Rng {
        state: u64,
    }

    impl Rng {
        fn new(seed: u64) -> Self {
            Rng { state: seed }
        }

        fn next_u64(&mut self) -> u64 {
            self.state = self
                .state
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            self.state
        }

        fn next_f64(&mut self) -> f64 {
            let v = self.next_u64();
            ((v >> 11) as f64 / (1u64 << 53) as f64) * 2.0 - 1.0
        }

        /// Uniform in [0, n) -- used for mini-batch sampling
        fn next_usize(&mut self, n: usize) -> usize {
            (self.next_u64() % n as u64) as usize
        }

        fn random_octonion(&mut self) -> Octonion {
            Octonion::new(
                self.next_f64(),
                self.next_f64(),
                self.next_f64(),
                self.next_f64(),
                self.next_f64(),
                self.next_f64(),
                self.next_f64(),
                self.next_f64(),
            )
        }

        /// Xavier-like initialization: scale = sqrt(2 / (fan_in + fan_out))
        fn random_xavier_octonion(&mut self, fan_in: usize, fan_out: usize) -> Octonion {
            let scale = (2.0 / (fan_in + fan_out) as f64).sqrt();
            self.random_octonion().scale(scale)
        }
    }

    // ====================================================================
    // MNIST data structures
    // ====================================================================

    struct MnistSample {
        label: u8,
        /// 98 octonions (784 pixels grouped into 8-component chunks, normalized to [0,1])
        octonions: Vec<Octonion>,
    }

    struct MnistDataset {
        train: Vec<MnistSample>,
        test: Vec<MnistSample>,
    }

    /// Precomputed hidden activation for a sample (avoids recomputing
    /// the frozen hidden layer during FD gradient estimation)
    struct PrecomputedSample {
        label: u8,
        hidden_activation: Vec<Octonion>, // HIDDEN_DIM octonions (hidden ReLU output)
    }

    fn pixels_to_octonions(pixels: &[u8]) -> Vec<Octonion> {
        assert_eq!(pixels.len(), 784);
        let mut octs = Vec::with_capacity(98);
        for chunk in pixels.chunks_exact(8) {
            octs.push(Octonion::new(
                chunk[0] as f64 / 255.0,
                chunk[1] as f64 / 255.0,
                chunk[2] as f64 / 255.0,
                chunk[3] as f64 / 255.0,
                chunk[4] as f64 / 255.0,
                chunk[5] as f64 / 255.0,
                chunk[6] as f64 / 255.0,
                chunk[7] as f64 / 255.0,
            ));
        }
        octs
    }

    fn parse_mnist_binary(data: &[u8]) -> MnistDataset {
        let n_train = u16::from_le_bytes([data[0], data[1]]) as usize;
        let n_test = u16::from_le_bytes([data[2], data[3]]) as usize;

        let sample_size = 1 + 784; // 1 byte label + 784 bytes pixels
        let expected_len = 4 + sample_size * (n_train + n_test);
        assert_eq!(
            data.len(),
            expected_len,
            "Binary size mismatch: got {}, expected {}",
            data.len(),
            expected_len
        );

        let mut train = Vec::with_capacity(n_train);
        let mut offset = 4;
        for _ in 0..n_train {
            let label = data[offset];
            let pixels = &data[offset + 1..offset + 1 + 784];
            train.push(MnistSample {
                label,
                octonions: pixels_to_octonions(pixels),
            });
            offset += sample_size;
        }

        let mut test = Vec::with_capacity(n_test);
        for _ in 0..n_test {
            let label = data[offset];
            let pixels = &data[offset + 1..offset + 1 + 784];
            test.push(MnistSample {
                label,
                octonions: pixels_to_octonions(pixels),
            });
            offset += sample_size;
        }

        MnistDataset { train, test }
    }

    /// One-hot target: 10 octonions, target[label].e[0] = 1.0, rest = 0.0
    fn one_hot_target(label: u8) -> Vec<Octonion> {
        let mut target = vec![Octonion::zero(); 10];
        target[label as usize].e[0] = 1.0;
        target
    }

    // ====================================================================
    // Octonion Linear Layer: y = W * x + b
    // ====================================================================

    struct OctLinearLayer {
        weights: Vec<Vec<Octonion>>, // [out_features][in_features]
        biases: Vec<Octonion>,       // [out_features]
        in_features: usize,
        out_features: usize,
    }

    impl OctLinearLayer {
        fn new(in_features: usize, out_features: usize, rng: &mut Rng) -> Self {
            let mut weights = Vec::new();
            for _ in 0..out_features {
                let mut row = Vec::new();
                for _ in 0..in_features {
                    row.push(rng.random_xavier_octonion(in_features, out_features));
                }
                weights.push(row);
            }
            let biases = vec![Octonion::zero(); out_features];
            OctLinearLayer {
                weights,
                biases,
                in_features,
                out_features,
            }
        }

        /// Forward pass: for each output j, y[j] = sum_i(W[j][i] * x[i]) + b[j]
        fn forward(&self, input: &[Octonion]) -> Vec<Octonion> {
            assert_eq!(input.len(), self.in_features);
            let mut output = Vec::with_capacity(self.out_features);
            for j in 0..self.out_features {
                let mut acc = self.biases[j];
                for i in 0..self.in_features {
                    acc = acc.add(&self.weights[j][i].mul(&input[i]));
                }
                output.push(acc);
            }
            output
        }

        /// Octonion parameter count: out * in (weights) + out (biases)
        fn octonion_param_count(&self) -> usize {
            self.out_features * self.in_features + self.out_features
        }
    }

    // ====================================================================
    // Two-layer ONN: hidden(98->16) + relu + output(16->10)
    // Hidden layer is a frozen random projection; only output is trained.
    // ====================================================================

    const HIDDEN_DIM: usize = 16;

    struct TwoLayerONN {
        hidden: OctLinearLayer,
        output: OctLinearLayer,
    }

    #[allow(dead_code)]
    impl TwoLayerONN {
        fn new(rng: &mut Rng) -> Self {
            TwoLayerONN {
                hidden: OctLinearLayer::new(98, HIDDEN_DIM, rng),
                output: OctLinearLayer::new(HIDDEN_DIM, 10, rng),
            }
        }

        /// Full forward pass through both layers
        fn forward(&self, input: &[Octonion]) -> Vec<Octonion> {
            let h = self.hidden.forward(input);
            let h_relu: Vec<Octonion> = h.iter().map(|o| o.relu()).collect();
            self.output.forward(&h_relu)
        }

        /// Total octonion parameter count (both layers)
        fn octonion_param_count(&self) -> usize {
            self.hidden.octonion_param_count() + self.output.octonion_param_count()
        }

        /// Trainable parameter count (output layer only)
        fn trainable_octonion_params(&self) -> usize {
            self.output.octonion_param_count()
        }

        /// Precompute hidden activations for a set of samples.
        /// This avoids recomputing the 98->16 projection during FD gradient steps.
        fn precompute_hidden(&self, samples: &[MnistSample]) -> Vec<PrecomputedSample> {
            samples
                .iter()
                .map(|s| {
                    let h = self.hidden.forward(&s.octonions);
                    let h_relu: Vec<Octonion> = h.iter().map(|o| o.relu()).collect();
                    PrecomputedSample {
                        label: s.label,
                        hidden_activation: h_relu,
                    }
                })
                .collect()
        }

        /// Classify: argmax over e[0] (real component) of each output octonion
        fn classify(&self, input: &[Octonion]) -> usize {
            let out = self.forward(input);
            let mut best_idx = 0;
            let mut best_val = f64::NEG_INFINITY;
            for (i, o) in out.iter().enumerate() {
                if o.e[0] > best_val {
                    best_val = o.e[0];
                    best_idx = i;
                }
            }
            best_idx
        }

        /// Classify from precomputed hidden activation (fast path)
        fn classify_from_hidden(&self, hidden: &[Octonion]) -> usize {
            let out = self.output.forward(hidden);
            let mut best_idx = 0;
            let mut best_val = f64::NEG_INFINITY;
            for (i, o) in out.iter().enumerate() {
                if o.e[0] > best_val {
                    best_val = o.e[0];
                    best_idx = i;
                }
            }
            best_idx
        }
    }

    // ====================================================================
    // MSE Loss over octonion outputs
    // ====================================================================

    fn mse_loss(predictions: &[Octonion], targets: &[Octonion]) -> f64 {
        assert_eq!(predictions.len(), targets.len());
        let n = predictions.len() as f64;
        let mut total = 0.0;
        for i in 0..predictions.len() {
            total += predictions[i].sub(&targets[i]).norm_sq();
        }
        total / (n * 8.0)
    }

    /// Average MSE loss using precomputed hidden activations (output layer only)
    fn batch_loss_precomputed(
        output_layer: &OctLinearLayer,
        samples: &[&PrecomputedSample],
    ) -> f64 {
        let mut total = 0.0;
        for sample in samples {
            let pred = output_layer.forward(&sample.hidden_activation);
            let target = one_hot_target(sample.label);
            total += mse_loss(&pred, &target);
        }
        total / samples.len() as f64
    }

    /// Average MSE loss over full training set (for reporting)
    fn full_train_loss(net: &TwoLayerONN, precomputed: &[PrecomputedSample]) -> f64 {
        let refs: Vec<&PrecomputedSample> = precomputed.iter().collect();
        batch_loss_precomputed(&net.output, &refs)
    }

    // ====================================================================
    // Finite-difference gradient descent (output layer only)
    // ====================================================================

    /// One gradient step on the output layer using finite-difference gradients
    /// over a mini-batch of precomputed hidden activations.
    /// Returns all_grads_finite.
    fn fd_gradient_step(
        output_layer: &mut OctLinearLayer,
        batch: &[&PrecomputedSample],
        lr: f64,
        epsilon: f64,
    ) -> bool {
        let mut all_finite = true;

        // Weight gradients
        for j in 0..output_layer.out_features {
            for i in 0..output_layer.in_features {
                for c in 0..8 {
                    let original = output_layer.weights[j][i].e[c];

                    output_layer.weights[j][i].e[c] = original + epsilon;
                    let loss_plus = batch_loss_precomputed(output_layer, batch);

                    output_layer.weights[j][i].e[c] = original - epsilon;
                    let loss_minus = batch_loss_precomputed(output_layer, batch);

                    output_layer.weights[j][i].e[c] = original;

                    let grad = (loss_plus - loss_minus) / (2.0 * epsilon);
                    if grad.is_finite() {
                        output_layer.weights[j][i].e[c] = original - lr * grad;
                    } else {
                        all_finite = false;
                    }
                }
            }
        }

        // Bias gradients
        for j in 0..output_layer.out_features {
            for c in 0..8 {
                let original = output_layer.biases[j].e[c];

                output_layer.biases[j].e[c] = original + epsilon;
                let loss_plus = batch_loss_precomputed(output_layer, batch);

                output_layer.biases[j].e[c] = original - epsilon;
                let loss_minus = batch_loss_precomputed(output_layer, batch);

                output_layer.biases[j].e[c] = original;

                let grad = (loss_plus - loss_minus) / (2.0 * epsilon);
                if grad.is_finite() {
                    output_layer.biases[j].e[c] = original - lr * grad;
                } else {
                    all_finite = false;
                }
            }
        }

        all_finite
    }

    /// One epoch: iterate through training data in mini-batches, applying
    /// finite-difference gradient descent on each.
    /// Returns (all_grads_finite_this_epoch).
    fn train_epoch(
        net: &mut TwoLayerONN,
        precomputed_train: &[PrecomputedSample],
        rng: &mut Rng,
        lr: f64,
        epsilon: f64,
        mini_batch_size: usize,
    ) -> bool {
        let n_steps = precomputed_train.len() / mini_batch_size;
        let mut all_finite = true;

        for _ in 0..n_steps {
            // Sample a random mini-batch
            let mut batch: Vec<&PrecomputedSample> = Vec::with_capacity(mini_batch_size);
            for _ in 0..mini_batch_size {
                let idx = rng.next_usize(precomputed_train.len());
                batch.push(&precomputed_train[idx]);
            }

            let step_finite = fd_gradient_step(&mut net.output, &batch, lr, epsilon);
            all_finite &= step_finite;
        }

        all_finite
    }

    /// Compute classification accuracy on precomputed data
    fn evaluate_accuracy_precomputed(net: &TwoLayerONN, precomputed: &[PrecomputedSample]) -> f64 {
        let mut correct = 0;
        for sample in precomputed {
            let pred = net.classify_from_hidden(&sample.hidden_activation);
            if pred == sample.label as usize {
                correct += 1;
            }
        }
        correct as f64 / precomputed.len() as f64
    }

    // ====================================================================
    // TEST 1: MNIST data loading and validation
    // ====================================================================

    #[test]
    fn test_mnist_data_loading() {
        eprintln!("\n=== MNIST Data Loading Validation ===");

        let dataset = parse_mnist_binary(MNIST_SUBSET);

        // Correct sample counts
        assert_eq!(dataset.train.len(), 80, "Expected 80 training samples");
        assert_eq!(dataset.test.len(), 20, "Expected 20 test samples");
        eprintln!("  Train samples: {}", dataset.train.len());
        eprintln!("  Test samples:  {}", dataset.test.len());

        // All labels in 0-9
        for (split_name, split) in [("train", &dataset.train), ("test", &dataset.test)] {
            for (idx, sample) in split.iter().enumerate() {
                assert!(
                    sample.label <= 9,
                    "{} sample {} has invalid label: {}",
                    split_name,
                    idx,
                    sample.label,
                );
            }
        }
        eprintln!("  All labels in [0, 9]: OK");

        // Balanced distribution
        for (split_name, split, expected_per_digit) in
            [("train", &dataset.train, 8), ("test", &dataset.test, 2)]
        {
            let mut counts = [0u32; 10];
            for sample in split.iter() {
                counts[sample.label as usize] += 1;
            }
            eprintln!("  {} distribution: {:?}", split_name, counts);
            for digit in 0..10 {
                assert_eq!(
                    counts[digit], expected_per_digit,
                    "{} digit {} has {} samples, expected {}",
                    split_name, digit, counts[digit], expected_per_digit,
                );
            }
        }
        eprintln!("  Balanced distribution: OK");

        // Octonion encoding: 98 octonions per image
        for sample in dataset.train.iter().chain(dataset.test.iter()) {
            assert_eq!(
                sample.octonions.len(),
                98,
                "Each image should encode as 98 octonions (784/8)"
            );
        }
        eprintln!("  Octonion encoding (98 per image): OK");

        // Pixel values in [0, 1] after normalization
        for sample in dataset.train.iter().chain(dataset.test.iter()) {
            for oct in &sample.octonions {
                for c in 0..8 {
                    assert!(
                        oct.e[c] >= 0.0 && oct.e[c] <= 1.0,
                        "Pixel value out of [0,1]: {}",
                        oct.e[c],
                    );
                }
            }
        }
        eprintln!("  Pixel normalization [0, 1]: OK");

        // Binary size check
        assert_eq!(MNIST_SUBSET.len(), 78504, "Binary file size mismatch");
        eprintln!("  Binary size: {} bytes", MNIST_SUBSET.len());

        eprintln!("  PASS");
    }

    // ====================================================================
    // TEST 2: Full MNIST toy ONN training pipeline
    // ====================================================================

    #[test]
    #[ignore = "long-running finite-difference training benchmark; run manually for deep ONN validation"]
    fn test_mnist_toy_onn_training() {
        eprintln!("\n=== MNIST Toy ONN Training ===");
        eprintln!("  Architecture: 98 -> {} (ReLU) -> 10", HIDDEN_DIM);
        eprintln!("  Hidden layer: frozen random projection (ELM-style)");
        eprintln!("  Output layer: trained via finite-difference SGD");

        let dataset = parse_mnist_binary(MNIST_SUBSET);

        // Initialize network with fixed seed
        let mut rng = Rng::new(0xA015700);
        let mut net = TwoLayerONN::new(&mut rng);

        let total_oct_params = net.octonion_param_count();
        let trainable_oct_params = net.trainable_octonion_params();
        let trainable_scalar_params = trainable_oct_params * 8;
        eprintln!(
            "  Total parameters: {} octonion ({} scalar)",
            total_oct_params,
            total_oct_params * 8
        );
        eprintln!(
            "  Trainable params: {} octonion ({} scalar)",
            trainable_oct_params, trainable_scalar_params
        );

        // Precompute hidden activations (frozen random projection)
        eprintln!("  Precomputing hidden activations...");
        let precomputed_train = net.precompute_hidden(&dataset.train);
        let precomputed_test = net.precompute_hidden(&dataset.test);

        // Hyperparameters
        let lr = 0.08;
        let epsilon = 1e-5;
        let n_epochs = 10;
        let mini_batch_size = 16;
        let steps_per_epoch = dataset.train.len() / mini_batch_size; // 5

        eprintln!(
            "  Hyperparams: lr={}, eps={}, epochs={}, batch={}, steps/epoch={}",
            lr, epsilon, n_epochs, mini_batch_size, steps_per_epoch
        );

        // Compute initial metrics
        let initial_loss = full_train_loss(&net, &precomputed_train);
        let initial_test_acc = evaluate_accuracy_precomputed(&net, &precomputed_test);

        eprintln!(
            "  Epoch  0: loss = {:.6}, test_acc = {:.1}%",
            initial_loss,
            initial_test_acc * 100.0
        );

        let mut all_grads_finite = true;
        let mut epoch_losses = vec![initial_loss];

        for epoch in 1..=n_epochs {
            let grads_finite = train_epoch(
                &mut net,
                &precomputed_train,
                &mut rng,
                lr,
                epsilon,
                mini_batch_size,
            );
            all_grads_finite &= grads_finite;

            let loss = full_train_loss(&net, &precomputed_train);
            let test_acc = evaluate_accuracy_precomputed(&net, &precomputed_test);
            epoch_losses.push(loss);

            eprintln!(
                "  Epoch {:2}: loss = {:.6}, test_acc = {:.1}%",
                epoch,
                loss,
                test_acc * 100.0
            );
        }

        let final_loss = *epoch_losses.last().unwrap();
        let final_test_acc = evaluate_accuracy_precomputed(&net, &precomputed_test);

        eprintln!("\n  --- Results ---");
        eprintln!("  Initial loss:     {:.6}", initial_loss);
        eprintln!("  Final loss:       {:.6}", final_loss);
        eprintln!(
            "  Loss reduction:   {:.2}x",
            initial_loss / final_loss.max(1e-15)
        );
        eprintln!("  Final test acc:   {:.1}%", final_test_acc * 100.0);
        eprintln!(
            "  All grads finite: {}",
            if all_grads_finite { "yes" } else { "NO" }
        );

        // Assertion 1: Training loss decreases
        assert!(
            final_loss < initial_loss,
            "Training loss should decrease: initial={:.6}, final={:.6}",
            initial_loss,
            final_loss,
        );

        // Assertion 2: Test accuracy > 10% (above random baseline)
        assert!(
            final_test_acc > 0.10,
            "Test accuracy should exceed 10% random baseline: got {:.1}%",
            final_test_acc * 100.0,
        );

        // Assertion 3: All gradients finite
        assert!(
            all_grads_finite,
            "All gradients should be finite throughout training",
        );

        eprintln!("  PASS");
    }
}
