[package]
name = "poseidon-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
poseidon-wrapper = { path = ".." }

[workspace]
members = ["."]

[[bin]]
name = "load_bytes"
path = "fuzz_targets/load_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "run"
path = "fuzz_targets/run.rs"
test = false
doc = false
bench = false
