//! C-Compatible Autodiff Runtime Functions
//!
//! This module provides C-compatible Rust functions for automatic differentiation
//! that can be called from assembly code generated by the native backend.
//!
//! Supports both forward-mode (dual numbers) and reverse-mode (tape-based) autodiff.
//!
//! # Reverse-mode (tape-based)
//!
//! The tape records operations during a forward pass, then propagates gradients
//! backwards via the chain rule. This computes gradients of a scalar output w.r.t.
//! all inputs in a single backward sweep (O(1) in number of outputs, vs O(n) for
//! forward-mode with n inputs).
//!
//! Tape lifecycle:
//! 1. `sounio_tape_create(n_inputs)` — allocate tape
//! 2. `sounio_tape_input(tape, idx, value)` — record each input
//! 3. `sounio_tape_add/mul/sin/...` — record operations (returns value indices)
//! 4. `sounio_autodiff_reverse(tape, output_grad, grads, n)` — backward sweep
//! 5. `sounio_tape_destroy(tape)` — deallocate

use std::ffi::c_void;

/// Dual number structure (value, derivative)
/// Layout: [value: f64, derivative: f64]
#[repr(C)]
pub struct Dual {
    pub value: f64,
    pub derivative: f64,
}

impl Dual {
    pub fn new(value: f64, derivative: f64) -> Self {
        Self { value, derivative }
    }

    pub fn constant(value: f64) -> Self {
        Self {
            value,
            derivative: 0.0,
        }
    }

    pub fn variable(value: f64) -> Self {
        Self {
            value,
            derivative: 1.0,
        }
    }
}

/// Forward-mode autodiff: dual number addition
/// C signature: void sounio_dual_add(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_add(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        (*result).value = a_val + b_val;
        (*result).derivative = a_der + b_der;
    }
}

/// Forward-mode autodiff: dual number subtraction
/// C signature: void sounio_dual_sub(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_sub(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        (*result).value = a_val - b_val;
        (*result).derivative = a_der - b_der;
    }
}

/// Forward-mode autodiff: dual number multiplication (product rule)
/// C signature: void sounio_dual_mul(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_mul(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        // Product rule: (a * b)' = a' * b + a * b'
        (*result).value = a_val * b_val;
        (*result).derivative = a_der * b_val + a_val * b_der;
    }
}

/// Forward-mode autodiff: dual number division (quotient rule)
/// C signature: void sounio_dual_div(Dual* a, Dual* b, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_div(a: *const Dual, b: *const Dual, result: *mut Dual) {
    if a.is_null() || b.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let a_val = (*a).value;
        let a_der = (*a).derivative;
        let b_val = (*b).value;
        let b_der = (*b).derivative;

        if b_val == 0.0 {
            // Division by zero - set result to NaN
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        // Quotient rule: (a / b)' = (a' * b - a * b') / b²
        (*result).value = a_val / b_val;
        let b_squared = b_val * b_val;
        (*result).derivative = (a_der * b_val - a_val * b_der) / b_squared;
    }
}

/// Forward-mode autodiff: compute gradient of scalar function
/// C signature: double sounio_autodiff_forward(
///     void (*f)(double*, double*),  // Function: f(x) -> y
///     double x,                      // Input value
///     double* gradient              // Output: df/dx at x
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_autodiff_forward(
    f: unsafe extern "C" fn(*const f64, *mut f64),
    x: f64,
    gradient: *mut f64,
) -> f64 {
    if gradient.is_null() {
        return f64::NAN;
    }

    // Simplified: compute numerical derivative as fallback
    // In production, this would use dual numbers directly
    let h = 1e-8;
    let mut y1 = 0.0;
    let mut y2 = 0.0;
    let x1 = x - h;
    let x2 = x + h;

    unsafe {
        f(&x1, &mut y1);
        f(&x2, &mut y2);
    }

    let result = (y2 - y1) / (2.0 * h);
    unsafe {
        *gradient = result;
    }

    // Return function value at x
    let mut y = 0.0;
    unsafe {
        f(&x, &mut y);
    }
    y
}

// =============================================================================
// Reverse-mode AD: Native Tape
// =============================================================================

/// Operation types recorded on the native tape (Wengert list).
///
/// Mirrors the GPU `TapeOp` but without GPU-specific operations
/// (no warp reductions, shared memory, quantization-aware training).
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativeTapeOp {
    // Arithmetic
    Add,
    Sub,
    Mul,
    Div,
    Neg,

    // Math functions
    Sin,
    Cos,
    Tan,
    Exp,
    Log,
    Sqrt,
    Pow,
    Abs,

    // Activations
    Tanh,
    Sigmoid,
    Relu,

    // Fused
    Fma,

    // Bookkeeping
    Const,
    Input,
}

impl NativeTapeOp {
    pub fn name(&self) -> &'static str {
        match self {
            NativeTapeOp::Add => "add",
            NativeTapeOp::Sub => "sub",
            NativeTapeOp::Mul => "mul",
            NativeTapeOp::Div => "div",
            NativeTapeOp::Neg => "neg",
            NativeTapeOp::Sin => "sin",
            NativeTapeOp::Cos => "cos",
            NativeTapeOp::Tan => "tan",
            NativeTapeOp::Exp => "exp",
            NativeTapeOp::Log => "log",
            NativeTapeOp::Sqrt => "sqrt",
            NativeTapeOp::Pow => "pow",
            NativeTapeOp::Abs => "abs",
            NativeTapeOp::Tanh => "tanh",
            NativeTapeOp::Sigmoid => "sigmoid",
            NativeTapeOp::Relu => "relu",
            NativeTapeOp::Fma => "fma",
            NativeTapeOp::Const => "const",
            NativeTapeOp::Input => "input",
        }
    }
}

/// A single entry in the native tape.
#[derive(Debug, Clone)]
pub struct NativeTapeEntry {
    pub op: NativeTapeOp,
    /// Index of the result value in the value buffer
    pub result_idx: u32,
    /// First operand index (unused for Const/Input)
    pub operand1: u32,
    /// Second operand index (unused for unary ops)
    pub operand2: u32,
    /// Third operand index (for ternary ops like FMA)
    pub operand3: u32,
    /// Extra scalar (constant value for Const, exponent for Pow)
    pub extra: f64,
}

/// Native CPU tape for reverse-mode automatic differentiation.
///
/// Records a Wengert list (computation trace) during the forward pass,
/// then sweeps backward to accumulate adjoint gradients via the chain rule.
pub struct NativeTape {
    entries: Vec<NativeTapeEntry>,
    /// Forward values (set during recording)
    values: Vec<f64>,
    /// Adjoint gradients (filled during backward sweep)
    gradients: Vec<f64>,
    /// Number of input variables
    n_inputs: usize,
    /// Next available value index
    next_idx: u32,
    /// Indices of the input variables (for extracting gradients)
    input_indices: Vec<u32>,
}

impl NativeTape {
    /// Create a new tape expecting `n_inputs` input variables.
    pub fn new(n_inputs: usize) -> Self {
        Self {
            entries: Vec::with_capacity(256),
            values: Vec::with_capacity(256),
            gradients: Vec::new(), // allocated at backward time
            n_inputs,
            next_idx: 0,
            input_indices: Vec::with_capacity(n_inputs),
        }
    }

    fn alloc_value(&mut self, val: f64) -> u32 {
        let idx = self.next_idx;
        self.next_idx += 1;
        self.values.push(val);
        idx
    }

    /// Record an input variable. `input_idx` is the logical input position (0..n_inputs).
    pub fn record_input(&mut self, input_idx: usize, value: f64) -> u32 {
        let idx = self.alloc_value(value);
        self.entries.push(NativeTapeEntry {
            op: NativeTapeOp::Input,
            result_idx: idx,
            operand1: input_idx as u32,
            operand2: 0,
            operand3: 0,
            extra: 0.0,
        });
        // Ensure input_indices is large enough
        if self.input_indices.len() <= input_idx {
            self.input_indices.resize(input_idx + 1, 0);
        }
        self.input_indices[input_idx] = idx;
        idx
    }

    /// Record a constant value.
    pub fn record_const(&mut self, value: f64) -> u32 {
        let idx = self.alloc_value(value);
        self.entries.push(NativeTapeEntry {
            op: NativeTapeOp::Const,
            result_idx: idx,
            operand1: 0,
            operand2: 0,
            operand3: 0,
            extra: value,
        });
        idx
    }

    /// Record a binary operation (Add, Sub, Mul, Div).
    pub fn record_binary(&mut self, op: NativeTapeOp, a: u32, b: u32) -> u32 {
        let a_val = self.values[a as usize];
        let b_val = self.values[b as usize];
        let result = match op {
            NativeTapeOp::Add => a_val + b_val,
            NativeTapeOp::Sub => a_val - b_val,
            NativeTapeOp::Mul => a_val * b_val,
            NativeTapeOp::Div => a_val / b_val,
            _ => panic!("record_binary called with non-binary op {:?}", op),
        };
        let idx = self.alloc_value(result);
        self.entries.push(NativeTapeEntry {
            op,
            result_idx: idx,
            operand1: a,
            operand2: b,
            operand3: 0,
            extra: 0.0,
        });
        idx
    }

    /// Record a unary operation (Neg, Sin, Cos, Exp, Log, Sqrt, Tanh, Sigmoid, Relu, Abs, Tan).
    pub fn record_unary(&mut self, op: NativeTapeOp, a: u32) -> u32 {
        let a_val = self.values[a as usize];
        let result = match op {
            NativeTapeOp::Neg => -a_val,
            NativeTapeOp::Sin => a_val.sin(),
            NativeTapeOp::Cos => a_val.cos(),
            NativeTapeOp::Tan => a_val.tan(),
            NativeTapeOp::Exp => a_val.exp(),
            NativeTapeOp::Log => a_val.ln(),
            NativeTapeOp::Sqrt => a_val.sqrt(),
            NativeTapeOp::Abs => a_val.abs(),
            NativeTapeOp::Tanh => a_val.tanh(),
            NativeTapeOp::Sigmoid => 1.0 / (1.0 + (-a_val).exp()),
            NativeTapeOp::Relu => if a_val > 0.0 { a_val } else { 0.0 },
            _ => panic!("record_unary called with non-unary op {:?}", op),
        };
        let idx = self.alloc_value(result);
        self.entries.push(NativeTapeEntry {
            op,
            result_idx: idx,
            operand1: a,
            operand2: 0,
            operand3: 0,
            extra: 0.0,
        });
        idx
    }

    /// Record x^p where p is a constant exponent.
    pub fn record_pow(&mut self, a: u32, exponent: f64) -> u32 {
        let a_val = self.values[a as usize];
        let result = a_val.powf(exponent);
        let idx = self.alloc_value(result);
        self.entries.push(NativeTapeEntry {
            op: NativeTapeOp::Pow,
            result_idx: idx,
            operand1: a,
            operand2: 0,
            operand3: 0,
            extra: exponent,
        });
        idx
    }

    /// Record fused multiply-add: a * b + c
    pub fn record_fma(&mut self, a: u32, b: u32, c: u32) -> u32 {
        let a_val = self.values[a as usize];
        let b_val = self.values[b as usize];
        let c_val = self.values[c as usize];
        let result = a_val * b_val + c_val;
        let idx = self.alloc_value(result);
        self.entries.push(NativeTapeEntry {
            op: NativeTapeOp::Fma,
            result_idx: idx,
            operand1: a,
            operand2: b,
            operand3: c,
            extra: 0.0,
        });
        idx
    }

    /// Get the forward value at a given index.
    pub fn value(&self, idx: u32) -> f64 {
        self.values[idx as usize]
    }

    /// Number of recorded entries.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the tape is empty.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Run the backward sweep.
    ///
    /// Seeds the gradient of `output_idx` with `output_gradient`, then processes
    /// the tape in reverse order, accumulating adjoint gradients.
    ///
    /// Returns a vector of gradients w.r.t. each input (in input_idx order).
    pub fn backward(&mut self, output_idx: u32, output_gradient: f64) -> Vec<f64> {
        let n = self.values.len();
        self.gradients.clear();
        self.gradients.resize(n, 0.0);

        // Seed the output
        self.gradients[output_idx as usize] = output_gradient;

        // Reverse sweep
        for entry in self.entries.iter().rev() {
            let dz = self.gradients[entry.result_idx as usize];
            if dz == 0.0 {
                continue;
            }

            match entry.op {
                NativeTapeOp::Add => {
                    // z = a + b → da += dz, db += dz
                    self.gradients[entry.operand1 as usize] += dz;
                    self.gradients[entry.operand2 as usize] += dz;
                }
                NativeTapeOp::Sub => {
                    // z = a - b → da += dz, db += -dz
                    self.gradients[entry.operand1 as usize] += dz;
                    self.gradients[entry.operand2 as usize] -= dz;
                }
                NativeTapeOp::Mul => {
                    // z = a * b → da += dz * b, db += dz * a
                    let a_val = self.values[entry.operand1 as usize];
                    let b_val = self.values[entry.operand2 as usize];
                    self.gradients[entry.operand1 as usize] += dz * b_val;
                    self.gradients[entry.operand2 as usize] += dz * a_val;
                }
                NativeTapeOp::Div => {
                    // z = a / b → da += dz / b, db += -dz * a / b²
                    let a_val = self.values[entry.operand1 as usize];
                    let b_val = self.values[entry.operand2 as usize];
                    self.gradients[entry.operand1 as usize] += dz / b_val;
                    self.gradients[entry.operand2 as usize] -=
                        dz * a_val / (b_val * b_val);
                }
                NativeTapeOp::Neg => {
                    // z = -a → da += -dz
                    self.gradients[entry.operand1 as usize] -= dz;
                }
                NativeTapeOp::Sin => {
                    // z = sin(a) → da += dz * cos(a)
                    let a_val = self.values[entry.operand1 as usize];
                    self.gradients[entry.operand1 as usize] += dz * a_val.cos();
                }
                NativeTapeOp::Cos => {
                    // z = cos(a) → da += -dz * sin(a)
                    let a_val = self.values[entry.operand1 as usize];
                    self.gradients[entry.operand1 as usize] -= dz * a_val.sin();
                }
                NativeTapeOp::Tan => {
                    // z = tan(a) → da += dz / cos²(a) = dz * (1 + tan²(a))
                    let z_val = self.values[entry.result_idx as usize];
                    self.gradients[entry.operand1 as usize] += dz * (1.0 + z_val * z_val);
                }
                NativeTapeOp::Exp => {
                    // z = exp(a) → da += dz * exp(a) = dz * z
                    let z_val = self.values[entry.result_idx as usize];
                    self.gradients[entry.operand1 as usize] += dz * z_val;
                }
                NativeTapeOp::Log => {
                    // z = ln(a) → da += dz / a
                    let a_val = self.values[entry.operand1 as usize];
                    self.gradients[entry.operand1 as usize] += dz / a_val;
                }
                NativeTapeOp::Sqrt => {
                    // z = sqrt(a) → da += dz / (2 * sqrt(a)) = dz / (2 * z)
                    let z_val = self.values[entry.result_idx as usize];
                    self.gradients[entry.operand1 as usize] += dz / (2.0 * z_val);
                }
                NativeTapeOp::Pow => {
                    // z = a^p → da += dz * p * a^(p-1)
                    let a_val = self.values[entry.operand1 as usize];
                    let p = entry.extra;
                    self.gradients[entry.operand1 as usize] +=
                        dz * p * a_val.powf(p - 1.0);
                }
                NativeTapeOp::Abs => {
                    // z = |a| → da += dz * sign(a)
                    let a_val = self.values[entry.operand1 as usize];
                    let sign = if a_val > 0.0 {
                        1.0
                    } else if a_val < 0.0 {
                        -1.0
                    } else {
                        0.0
                    };
                    self.gradients[entry.operand1 as usize] += dz * sign;
                }
                NativeTapeOp::Tanh => {
                    // z = tanh(a) → da += dz * (1 - z²)
                    let z_val = self.values[entry.result_idx as usize];
                    self.gradients[entry.operand1 as usize] +=
                        dz * (1.0 - z_val * z_val);
                }
                NativeTapeOp::Sigmoid => {
                    // z = σ(a) → da += dz * z * (1 - z)
                    let z_val = self.values[entry.result_idx as usize];
                    self.gradients[entry.operand1 as usize] +=
                        dz * z_val * (1.0 - z_val);
                }
                NativeTapeOp::Relu => {
                    // z = relu(a) → da += dz * (a > 0 ? 1 : 0)
                    let a_val = self.values[entry.operand1 as usize];
                    if a_val > 0.0 {
                        self.gradients[entry.operand1 as usize] += dz;
                    }
                }
                NativeTapeOp::Fma => {
                    // z = a * b + c → da += dz * b, db += dz * a, dc += dz
                    let a_val = self.values[entry.operand1 as usize];
                    let b_val = self.values[entry.operand2 as usize];
                    self.gradients[entry.operand1 as usize] += dz * b_val;
                    self.gradients[entry.operand2 as usize] += dz * a_val;
                    self.gradients[entry.operand3 as usize] += dz;
                }
                NativeTapeOp::Const | NativeTapeOp::Input => {
                    // No operands to propagate to
                }
            }
        }

        // Extract input gradients in order
        self.input_indices
            .iter()
            .map(|&idx| self.gradients[idx as usize])
            .collect()
    }
}

// =============================================================================
// C-callable tape API
// =============================================================================

/// Create a new native tape for reverse-mode AD.
/// Returns an opaque pointer to the tape.
#[unsafe(no_mangle)]
pub extern "C" fn sounio_tape_create(n_inputs: i32) -> *mut c_void {
    let tape = Box::new(NativeTape::new(n_inputs.max(0) as usize));
    Box::into_raw(tape) as *mut c_void
}

/// Destroy a native tape, freeing its memory.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_destroy(tape: *mut c_void) {
    if !tape.is_null() {
        unsafe {
            drop(Box::from_raw(tape as *mut NativeTape));
        }
    }
}

/// Record an input variable on the tape.
/// Returns the value index for use in subsequent operations.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_input(
    tape: *mut c_void,
    input_idx: i32,
    value: f64,
) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_input(input_idx as usize, value)
    }
}

/// Record a constant on the tape.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_const(tape: *mut c_void, value: f64) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_const(value)
    }
}

/// Record addition: z = a + b
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_add(tape: *mut c_void, a: u32, b: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_binary(NativeTapeOp::Add, a, b)
    }
}

/// Record subtraction: z = a - b
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_sub(tape: *mut c_void, a: u32, b: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_binary(NativeTapeOp::Sub, a, b)
    }
}

/// Record multiplication: z = a * b
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_mul(tape: *mut c_void, a: u32, b: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_binary(NativeTapeOp::Mul, a, b)
    }
}

/// Record division: z = a / b
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_div(tape: *mut c_void, a: u32, b: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_binary(NativeTapeOp::Div, a, b)
    }
}

/// Record negation: z = -a
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_neg(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Neg, a)
    }
}

/// Record sine: z = sin(a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_sin(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Sin, a)
    }
}

/// Record cosine: z = cos(a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_cos(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Cos, a)
    }
}

/// Record exponential: z = exp(a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_exp(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Exp, a)
    }
}

/// Record natural log: z = ln(a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_log(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Log, a)
    }
}

/// Record square root: z = sqrt(a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_sqrt(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Sqrt, a)
    }
}

/// Record power: z = a^exponent
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_pow(tape: *mut c_void, a: u32, exponent: f64) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_pow(a, exponent)
    }
}

/// Record tanh: z = tanh(a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_tanh(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Tanh, a)
    }
}

/// Record sigmoid: z = 1/(1+exp(-a))
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_sigmoid(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Sigmoid, a)
    }
}

/// Record ReLU: z = max(0, a)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_relu(tape: *mut c_void, a: u32) -> u32 {
    if tape.is_null() {
        return u32::MAX;
    }
    unsafe {
        let tape = &mut *(tape as *mut NativeTape);
        tape.record_unary(NativeTapeOp::Relu, a)
    }
}

/// Get the forward value at a tape index.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_tape_value(tape: *const c_void, idx: u32) -> f64 {
    if tape.is_null() {
        return f64::NAN;
    }
    unsafe {
        let tape = &*(tape as *const NativeTape);
        tape.value(idx)
    }
}

/// Reverse-mode autodiff: tape-based backpropagation.
///
/// Runs the backward sweep on a previously-built tape, seeding the gradient
/// of the last recorded value with `output_gradient`, then writes the
/// gradients w.r.t. each input into `input_gradients[0..n_inputs]`.
///
/// C signature: void sounio_autodiff_reverse(
///     void* tape,                   // Computation tape
///     double output_gradient,       // Gradient w.r.t. output
///     double* input_gradients,      // Output: gradients w.r.t. inputs
///     int n_inputs                  // Number of inputs
/// )
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_autodiff_reverse(
    tape: *mut c_void,
    output_gradient: f64,
    input_gradients: *mut f64,
    n_inputs: i32,
) {
    if tape.is_null() || input_gradients.is_null() || n_inputs <= 0 {
        return;
    }

    unsafe {
        let tape = &mut *(tape as *mut NativeTape);

        // The output is the last allocated value
        let output_idx = if tape.next_idx > 0 {
            tape.next_idx - 1
        } else {
            return;
        };

        let grads = tape.backward(output_idx, output_gradient);

        // Copy gradients to output buffer
        let n = (n_inputs as usize).min(grads.len());
        for i in 0..n {
            *input_gradients.add(i) = grads[i];
        }
    }
}

/// Forward-mode autodiff: dual number exponential
/// C signature: void sounio_dual_exp(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_exp(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        let exp_val = x_val.exp();
        // d/dx(exp(x)) = exp(x) * x'
        (*result).value = exp_val;
        (*result).derivative = exp_val * x_der;
    }
}

/// Forward-mode autodiff: dual number logarithm
/// C signature: void sounio_dual_log(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_log(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        if x_val <= 0.0 {
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        // d/dx(ln(x)) = x' / x
        (*result).value = x_val.ln();
        (*result).derivative = x_der / x_val;
    }
}

/// Forward-mode autodiff: dual number sine
/// C signature: void sounio_dual_sin(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_sin(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        // d/dx(sin(x)) = cos(x) * x'
        (*result).value = x_val.sin();
        (*result).derivative = x_val.cos() * x_der;
    }
}

/// Forward-mode autodiff: dual number cosine
/// C signature: void sounio_dual_cos(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_cos(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        // d/dx(cos(x)) = -sin(x) * x'
        (*result).value = x_val.cos();
        (*result).derivative = -x_val.sin() * x_der;
    }
}

/// Forward-mode autodiff: dual number power (x^p where p is constant)
/// C signature: void sounio_dual_pow(Dual* x, double power, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_pow(x: *const Dual, power: f64, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        if x_val <= 0.0 && power != power.floor() {
            // Negative base with non-integer exponent
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        let pow_val = x_val.powf(power);
        // d/dx(x^p) = p * x^(p-1) * x'
        (*result).value = pow_val;
        (*result).derivative = power * x_val.powf(power - 1.0) * x_der;
    }
}

/// Forward-mode autodiff: dual number square root
/// C signature: void sounio_dual_sqrt(Dual* x, Dual* result)
#[unsafe(no_mangle)]
pub unsafe extern "C" fn sounio_dual_sqrt(x: *const Dual, result: *mut Dual) {
    if x.is_null() || result.is_null() {
        return;
    }

    unsafe {
        let x_val = (*x).value;
        let x_der = (*x).derivative;

        if x_val < 0.0 {
            (*result).value = f64::NAN;
            (*result).derivative = f64::NAN;
            return;
        }

        let sqrt_val = x_val.sqrt();
        // d/dx(sqrt(x)) = x' / (2 * sqrt(x))
        (*result).value = sqrt_val;
        (*result).derivative = x_der / (2.0 * sqrt_val);
    }
}

// =============================================================================
// Tests for reverse-mode tape
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    const EPS: f64 = 1e-10;

    fn approx_eq(a: f64, b: f64, tol: f64) -> bool {
        (a - b).abs() < tol
    }

    // --- Tape Rust API tests ---

    #[test]
    fn test_tape_add() {
        // f(x, y) = x + y → df/dx = 1, df/dy = 1
        let mut tape = NativeTape::new(2);
        let x = tape.record_input(0, 3.0);
        let y = tape.record_input(1, 5.0);
        let z = tape.record_binary(NativeTapeOp::Add, x, y);

        assert!(approx_eq(tape.value(z), 8.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 1.0, EPS)); // df/dx
        assert!(approx_eq(grads[1], 1.0, EPS)); // df/dy
    }

    #[test]
    fn test_tape_mul() {
        // f(x, y) = x * y → df/dx = y, df/dy = x
        let mut tape = NativeTape::new(2);
        let x = tape.record_input(0, 3.0);
        let y = tape.record_input(1, 5.0);
        let z = tape.record_binary(NativeTapeOp::Mul, x, y);

        assert!(approx_eq(tape.value(z), 15.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 5.0, EPS)); // df/dx = y
        assert!(approx_eq(grads[1], 3.0, EPS)); // df/dy = x
    }

    #[test]
    fn test_tape_sub_div() {
        // f(x, y) = (x - y) / y → df/dx = 1/y, df/dy = -x/y²
        let mut tape = NativeTape::new(2);
        let x = tape.record_input(0, 6.0);
        let y = tape.record_input(1, 2.0);
        let diff = tape.record_binary(NativeTapeOp::Sub, x, y);
        let z = tape.record_binary(NativeTapeOp::Div, diff, y);

        assert!(approx_eq(tape.value(z), 2.0, EPS)); // (6-2)/2 = 2

        let grads = tape.backward(z, 1.0);
        // df/dx = 1/y = 0.5
        assert!(approx_eq(grads[0], 0.5, EPS));
        // df/dy = d/dy((x-y)/y) = d/dy(x/y - 1) = -x/y²
        // But via chain rule on the tape:
        //   z = diff / y → d(diff) += 1/y = 0.5, d(y) += -(diff)*1/y² = -4/4 = -1
        //   diff = x - y → d(x) += 0.5, d(y) += -0.5
        //   total d(y) = -1 + (-0.5) = -1.5
        assert!(approx_eq(grads[1], -1.5, EPS)); // -x/y² = -6/4 = -1.5
    }

    #[test]
    fn test_tape_exp() {
        // f(x) = exp(x) → df/dx = exp(x)
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 2.0);
        let z = tape.record_unary(NativeTapeOp::Exp, x);

        let expected = 2.0_f64.exp();
        assert!(approx_eq(tape.value(z), expected, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], expected, EPS));
    }

    #[test]
    fn test_tape_log() {
        // f(x) = ln(x) → df/dx = 1/x
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 2.0);
        let z = tape.record_unary(NativeTapeOp::Log, x);

        assert!(approx_eq(tape.value(z), 2.0_f64.ln(), EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 0.5, EPS)); // 1/2
    }

    #[test]
    fn test_tape_sin_cos() {
        // f(x) = sin(x) + cos(x) → df/dx = cos(x) - sin(x)
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 1.0);
        let s = tape.record_unary(NativeTapeOp::Sin, x);
        let c = tape.record_unary(NativeTapeOp::Cos, x);
        let z = tape.record_binary(NativeTapeOp::Add, s, c);

        let expected = 1.0_f64.sin() + 1.0_f64.cos();
        assert!(approx_eq(tape.value(z), expected, EPS));

        let grads = tape.backward(z, 1.0);
        let expected_grad = 1.0_f64.cos() - 1.0_f64.sin();
        assert!(approx_eq(grads[0], expected_grad, EPS));
    }

    #[test]
    fn test_tape_pow() {
        // f(x) = x³ → df/dx = 3x²
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 2.0);
        let z = tape.record_pow(x, 3.0);

        assert!(approx_eq(tape.value(z), 8.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 12.0, EPS)); // 3 * 2² = 12
    }

    #[test]
    fn test_tape_sqrt() {
        // f(x) = sqrt(x) → df/dx = 1/(2*sqrt(x))
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 4.0);
        let z = tape.record_unary(NativeTapeOp::Sqrt, x);

        assert!(approx_eq(tape.value(z), 2.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 0.25, EPS)); // 1/(2*2) = 0.25
    }

    #[test]
    fn test_tape_tanh() {
        // f(x) = tanh(x) → df/dx = 1 - tanh²(x)
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 0.5);
        let z = tape.record_unary(NativeTapeOp::Tanh, x);

        let t = 0.5_f64.tanh();
        assert!(approx_eq(tape.value(z), t, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 1.0 - t * t, EPS));
    }

    #[test]
    fn test_tape_sigmoid() {
        // f(x) = σ(x) → df/dx = σ(x)(1-σ(x))
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 1.0);
        let z = tape.record_unary(NativeTapeOp::Sigmoid, x);

        let s = 1.0 / (1.0 + (-1.0_f64).exp());
        assert!(approx_eq(tape.value(z), s, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], s * (1.0 - s), EPS));
    }

    #[test]
    fn test_tape_relu() {
        // f(x) = relu(x), positive input
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 3.0);
        let z = tape.record_unary(NativeTapeOp::Relu, x);
        assert!(approx_eq(tape.value(z), 3.0, EPS));
        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 1.0, EPS));

        // negative input
        let mut tape2 = NativeTape::new(1);
        let x2 = tape2.record_input(0, -2.0);
        let z2 = tape2.record_unary(NativeTapeOp::Relu, x2);
        assert!(approx_eq(tape2.value(z2), 0.0, EPS));
        let grads2 = tape2.backward(z2, 1.0);
        assert!(approx_eq(grads2[0], 0.0, EPS));
    }

    #[test]
    fn test_tape_fma() {
        // f(x, y, z) = x * y + z → df/dx = y, df/dy = x, df/dz = 1
        let mut tape = NativeTape::new(3);
        let x = tape.record_input(0, 2.0);
        let y = tape.record_input(1, 3.0);
        let z = tape.record_input(2, 4.0);
        let r = tape.record_fma(x, y, z);

        assert!(approx_eq(tape.value(r), 10.0, EPS)); // 2*3 + 4

        let grads = tape.backward(r, 1.0);
        assert!(approx_eq(grads[0], 3.0, EPS)); // df/dx = y
        assert!(approx_eq(grads[1], 2.0, EPS)); // df/dy = x
        assert!(approx_eq(grads[2], 1.0, EPS)); // df/dz = 1
    }

    #[test]
    fn test_tape_composite_quadratic() {
        // f(x) = x² + 2x + 1 → df/dx = 2x + 2
        // At x=3: f(3)=16, f'(3)=8
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 3.0);
        let two = tape.record_const(2.0);
        let one = tape.record_const(1.0);
        let x_sq = tape.record_binary(NativeTapeOp::Mul, x, x);
        let two_x = tape.record_binary(NativeTapeOp::Mul, two, x);
        let sum1 = tape.record_binary(NativeTapeOp::Add, x_sq, two_x);
        let z = tape.record_binary(NativeTapeOp::Add, sum1, one);

        assert!(approx_eq(tape.value(z), 16.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 8.0, EPS)); // 2*3 + 2 = 8
    }

    #[test]
    fn test_tape_rosenbrock() {
        // Rosenbrock: f(x,y) = (1-x)² + 100*(y-x²)²
        // df/dx = -2(1-x) + 100 * 2*(y-x²)*(-2x)
        //       = -2(1-x) - 400*x*(y-x²)
        // df/dy = 200*(y-x²)
        // At (1,1): f=0, df/dx=0, df/dy=0
        // At (0,0): f=1, df/dx=-2, df/dy=0
        let mut tape = NativeTape::new(2);
        let x = tape.record_input(0, 0.0);
        let y = tape.record_input(1, 0.0);
        let one = tape.record_const(1.0);
        let hundred = tape.record_const(100.0);

        let one_minus_x = tape.record_binary(NativeTapeOp::Sub, one, x);
        let term1 = tape.record_binary(NativeTapeOp::Mul, one_minus_x, one_minus_x);

        let x_sq = tape.record_binary(NativeTapeOp::Mul, x, x);
        let y_minus_xsq = tape.record_binary(NativeTapeOp::Sub, y, x_sq);
        let t2_sq = tape.record_binary(NativeTapeOp::Mul, y_minus_xsq, y_minus_xsq);
        let term2 = tape.record_binary(NativeTapeOp::Mul, hundred, t2_sq);

        let z = tape.record_binary(NativeTapeOp::Add, term1, term2);

        assert!(approx_eq(tape.value(z), 1.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], -2.0, EPS));
        assert!(approx_eq(grads[1], 0.0, EPS));
    }

    #[test]
    fn test_tape_chain_rule_deep() {
        // f(x) = exp(sin(x²)) — chain rule across 3 levels
        // f'(x) = exp(sin(x²)) * cos(x²) * 2x
        let x_val = 0.5;
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, x_val);
        let x_sq = tape.record_binary(NativeTapeOp::Mul, x, x);
        let sin_xsq = tape.record_unary(NativeTapeOp::Sin, x_sq);
        let z = tape.record_unary(NativeTapeOp::Exp, sin_xsq);

        let xsq = x_val * x_val;
        let expected_val = xsq.sin().exp();
        assert!(approx_eq(tape.value(z), expected_val, EPS));

        let grads = tape.backward(z, 1.0);
        let expected_grad = expected_val * xsq.cos() * 2.0 * x_val;
        assert!(approx_eq(grads[0], expected_grad, EPS));
    }

    // --- C API tests (mirrors integration test pattern) ---

    #[test]
    fn test_c_api_reverse_mode() {
        // f(x, y) = x * y + x → df/dx = y + 1, df/dy = x
        // At x=3, y=5: f=18, df/dx=6, df/dy=3
        unsafe {
            let tape = sounio_tape_create(2);
            let x = sounio_tape_input(tape, 0, 3.0);
            let y = sounio_tape_input(tape, 1, 5.0);
            let xy = sounio_tape_mul(tape, x, y);
            let _z = sounio_tape_add(tape, xy, x);

            assert!(approx_eq(sounio_tape_value(tape, _z), 18.0, EPS));

            let mut grads = [0.0f64; 2];
            sounio_autodiff_reverse(tape, 1.0, grads.as_mut_ptr(), 2);

            assert!(approx_eq(grads[0], 6.0, EPS)); // df/dx = y + 1 = 6
            assert!(approx_eq(grads[1], 3.0, EPS)); // df/dy = x = 3

            sounio_tape_destroy(tape);
        }
    }

    #[test]
    fn test_c_api_exp_log_round_trip() {
        // f(x) = log(exp(x)) = x → df/dx = 1
        unsafe {
            let tape = sounio_tape_create(1);
            let x = sounio_tape_input(tape, 0, 2.5);
            let e = sounio_tape_exp(tape, x);
            let _z = sounio_tape_log(tape, e);

            assert!(approx_eq(sounio_tape_value(tape, _z), 2.5, 1e-9));

            let mut grad = 0.0f64;
            sounio_autodiff_reverse(tape, 1.0, &mut grad, 1);
            assert!(approx_eq(grad, 1.0, 1e-9));

            sounio_tape_destroy(tape);
        }
    }

    #[test]
    fn test_tape_neg() {
        // f(x) = -x → df/dx = -1
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 7.0);
        let z = tape.record_unary(NativeTapeOp::Neg, x);
        assert!(approx_eq(tape.value(z), -7.0, EPS));
        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], -1.0, EPS));
    }

    #[test]
    fn test_tape_gradient_accumulation() {
        // f(x) = x + x + x = 3x → df/dx = 3
        let mut tape = NativeTape::new(1);
        let x = tape.record_input(0, 2.0);
        let s1 = tape.record_binary(NativeTapeOp::Add, x, x);
        let z = tape.record_binary(NativeTapeOp::Add, s1, x);

        assert!(approx_eq(tape.value(z), 6.0, EPS));

        let grads = tape.backward(z, 1.0);
        assert!(approx_eq(grads[0], 3.0, EPS));
    }
}
