(executable
 (name loom)
 (modules loom loom_arrow loom_epistemic loom_exec loom_hook loom_lane_health loom_resident loom_effect_closure loom_invocation_cell loom_exec_grant_cell loom_peer_activation_capsule loom_membrane loom_witness loom_witness_epoch loom_witness_transparency loom_ui)
 (libraries unix cryptokit)
 (foreign_stubs
  (language c)
  (names
   loom_pty_stubs
   loom_membrane_stubs
   loom_arrow_stubs
   loom_nanoarrow
   loom_nanoarrow_ipc
   loom_flatcc)
  (include_dirs vendor))
 (link_flags -cclib -lutil -cclib -lm))
