let html =
  {loom|<!doctype html>
<html lang="en" data-loom-ui="fusion-v1">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark light">
<title>Sounio Loom</title>
<style>
:root{
  color-scheme:dark;
  --ink:#071019;--ink-2:#0b1520;--ink-3:#111d29;--line:#2b4054;
  --paper:#f2f4f7;--paper-2:#f8f9fb;--paper-line:#cbd3dc;
  --text:#eaf1f7;--muted:#8495a8;--dark-text:#202b36;--dark-muted:#687585;
  --cyan:#40d8ff;--mint:#32f6c1;--violet:#a98bff;--rose:#ff5d87;
  --amber:#ffd34d;--orange:#ff8e59;--blue:#3588ff;
  --toolbar-h:52px;--chrono-h:194px;
}
*{box-sizing:border-box}
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#02060a}
body{font-family:Inter,-apple-system,BlinkMacSystemFont,"SF Pro Text",sans-serif;color:var(--text);letter-spacing:0;display:grid;grid-template-rows:var(--toolbar-h) minmax(0,1fr) var(--chrono-h)}
button,input{font:inherit;letter-spacing:0}
button{color:inherit}
.topbar{position:relative;display:grid;grid-template-columns:240px minmax(220px,370px) 1fr auto;align-items:center;gap:16px;padding:0 14px;background:linear-gradient(90deg,#0b1520,#111827 44%,#08121a);border-bottom:1px solid #31475c;min-width:0}
.topbar:after{content:"";position:absolute;left:0;right:0;bottom:-1px;height:2px;background:linear-gradient(90deg,var(--cyan),var(--mint),var(--amber),var(--rose),var(--violet),var(--cyan));opacity:.9}
.brand{display:flex;align-items:center;gap:12px;min-width:0}.mark{width:26px;height:30px;display:grid;place-items:center;color:var(--cyan);font:700 18px ui-monospace,monospace;border-left:2px solid var(--cyan);border-right:1px solid var(--violet)}
.brand strong{font-size:18px}.brand small{display:block;color:var(--muted);font:9px ui-monospace,monospace;text-transform:uppercase;margin-top:2px}
.command{height:32px;display:flex;align-items:center;gap:9px;padding:0 10px;border:1px solid #304458;background:#0b141e;border-radius:6px;min-width:0}.command span{color:var(--muted)}.command input{width:100%;min-width:0;border:0;outline:0;background:transparent;color:var(--text);font-size:11px}.command kbd{font:9px ui-monospace,monospace;color:#8799ac}
.toolbar-center{display:flex;justify-content:center;min-width:0}.segments{display:flex;border:1px solid #30475b;border-radius:6px;overflow:hidden;background:#09121a}.segments button{height:30px;min-width:84px;border:0;border-right:1px solid #30475b;background:transparent;color:#9aabba;font-size:10px;cursor:pointer}.segments button:last-child{border-right:0}.segments button.active{color:#fff;background:#12283a;box-shadow:inset 0 -2px 0 var(--cyan)}
.toolbar-status{display:flex;align-items:center;justify-content:flex-end;gap:12px;white-space:nowrap}.metric{min-width:96px}.metric label{display:block;color:#718397;font:8px ui-monospace,monospace}.metric b{display:block;color:var(--mint);font:14px ui-monospace,monospace;margin-top:3px}.live{height:28px;padding:0 10px;border:1px solid rgba(50,246,193,.55);border-radius:5px;background:#0b1d1d;color:#baffea;font:9px ui-monospace,monospace}.live:before{content:"";display:inline-block;width:6px;height:6px;margin-right:7px;border-radius:50%;background:var(--mint)}
.cutover-pill{height:28px;min-width:104px;padding:0 10px;border:1px solid rgba(255,211,77,.55);border-radius:5px;background:#211d0d;color:#ffe99d;font:8px ui-monospace,monospace;display:flex;align-items:center;justify-content:center;gap:7px}.cutover-pill:before{content:"";width:6px;height:6px;border-radius:50%;background:var(--amber);box-shadow:0 0 9px rgba(255,211,77,.75)}body[data-cutover="cutover_ready"] .cutover-pill{border-color:rgba(50,246,193,.7);background:#0b1d1d;color:#baffea}body[data-cutover="cutover_ready"] .cutover-pill:before{background:var(--mint);box-shadow:0 0 10px rgba(50,246,193,.85)}body[data-cutover="fail_closed"] .cutover-pill,body[data-cutover^="deny"] .cutover-pill{border-color:rgba(255,93,135,.55);background:#241018;color:#ffc1d1}body[data-cutover="fail_closed"] .cutover-pill:before,body[data-cutover^="deny"] .cutover-pill:before{background:var(--rose);box-shadow:0 0 9px rgba(255,93,135,.75)}
.workspace{display:grid;grid-template-columns:260px minmax(300px,370px) minmax(420px,1fr) 330px;min-height:0;overflow:hidden;background:var(--ink)}
.panel{min-width:0;min-height:0;overflow:hidden;border-right:1px solid var(--line)}
.panel-head{height:38px;display:flex;align-items:center;gap:8px;padding:0 12px;border-bottom:1px solid currentColor;color:#dfe8f1}.panel-head strong{font-size:10px}.panel-head small{color:var(--muted);font-size:9px;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.panel-head .spacer{margin-left:auto}
.fleet{background:linear-gradient(180deg,#091522,#071019);display:grid;grid-template-rows:38px minmax(0,1fr) 40px}.fleet-list{overflow:auto;scrollbar-width:thin;scrollbar-color:#294158 transparent}.fleet-group{padding:8px 10px 4px;color:var(--cyan);font:8px ui-monospace,monospace;text-transform:uppercase;display:flex}.fleet-group span{margin-left:auto;color:#718397}
.lane{width:calc(100% - 12px);height:34px;margin:0 6px 2px;padding:0 7px;display:grid;grid-template-columns:22px 1fr auto;align-items:center;gap:7px;border:1px solid transparent;border-radius:5px;background:transparent;text-align:left;cursor:pointer}.lane:hover{background:#101d29}.lane.active{background:#102538;border-color:rgba(64,216,255,.7);box-shadow:inset 3px 0 0 var(--cyan)}.lane-index{color:#64778c;font:8px ui-monospace,monospace}.lane-name{min-width:0;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.lane-name small{display:block;color:#718397;font:7px ui-monospace,monospace;margin-top:2px}.lane-tail{display:flex;align-items:center;gap:6px}.state-dot{width:6px;height:6px;border-radius:50%;background:var(--mint)}.lane-state{font:7px ui-monospace,monospace;color:var(--mint);text-transform:uppercase}.spark{width:38px;height:12px}.fleet-foot{margin:4px 7px 6px;padding:6px 8px;border:1px solid #294159;border-radius:5px;background:#0a1723;color:#8193a7;font:7px ui-monospace,monospace;display:grid;grid-template-columns:1fr auto;align-items:center}.fleet-foot b{color:var(--mint)}
.weave{position:relative;background:var(--paper);color:var(--dark-text);display:grid;grid-template-rows:38px minmax(0,1fr)}.weave .panel-head{color:#25313e;border-color:var(--paper-line);background:#f8f9fb}.weave-stage{position:relative;overflow:hidden}.weave-stage canvas{position:absolute;inset:0;width:100%;height:100%}.weave-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(55,74,92,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(55,74,92,.07) 1px,transparent 1px);background-size:34px 34px;pointer-events:none}.weave-edges{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.weave-edges path{fill:none;stroke-width:1.5}.weave-label{position:absolute;left:14px;color:#687585;font:8px ui-monospace,monospace;text-transform:uppercase}.weave-label.up{top:14px}.weave-label.down{top:58%}
.graph-node{position:absolute;width:142px;min-height:58px;padding:10px 10px 8px 28px;border:1px solid var(--node-color);border-radius:6px;background:rgba(249,250,252,.93);box-shadow:0 7px 18px rgba(22,37,52,.07);color:#26313d}.graph-node:before{content:"";position:absolute;left:11px;top:13px;width:8px;height:8px;border-radius:50%;background:var(--node-color)}.graph-node strong{display:block;font-size:10px}.graph-node small{display:block;color:#6b7785;font:7px ui-monospace,monospace;margin-top:7px;line-height:1.35}.graph-node.selected{width:190px;min-height:90px;padding-top:14px;border-width:2px;background:rgba(255,255,255,.96);box-shadow:0 8px 24px rgba(35,130,164,.16)}.graph-node.selected small{font-size:8px}.graph-node .node-pulse{height:12px;margin-top:10px;background:linear-gradient(135deg,transparent 0 10%,var(--node-color) 11% 13%,transparent 14% 23%,var(--node-color) 24% 26%,transparent 27% 38%,var(--node-color) 39% 41%,transparent 42% 54%,var(--node-color) 55% 57%,transparent 58%)}
.node-a{left:6%;top:9%;--node-color:var(--blue)}.node-b{right:6%;top:9%;--node-color:var(--mint)}.node-core{left:50%;top:31%;transform:translateX(-50%);--node-color:var(--cyan)}.node-gate{left:6%;top:66%;--node-color:var(--rose)}.node-store{right:6%;top:66%;--node-color:var(--amber)}
.shader-badge{position:absolute;right:10px;bottom:10px;height:24px;padding:0 8px;display:flex;align-items:center;border:1px solid rgba(64,216,255,.5);border-radius:5px;background:rgba(242,248,250,.8);color:#48606f;font:8px ui-monospace,monospace}.shader-badge b{color:#087f9d;margin-left:5px}
.terminal-panel{background:#050b12;display:grid;grid-template-rows:38px minmax(0,1fr) 38px 28px}.terminal-panel .panel-head{border-color:#263d52;background:#08131e}.terminal-title{color:#fff}.terminal-state{color:var(--mint);font:8px ui-monospace,monospace}.terminal{margin:0;padding:13px 15px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;color:#d6e1eb;background:radial-gradient(circle at 80% 0,rgba(21,74,92,.18),transparent 40%),#050b12;font:10px/1.45 "Geist Mono","SFMono-Regular",Consolas,monospace;letter-spacing:0;scrollbar-width:thin;scrollbar-color:#294158 transparent}.message-composer{display:grid;grid-template-columns:76px minmax(0,1fr) 58px;gap:6px;align-items:center;padding:5px 8px;border-top:1px solid #284056;background:#08131e}.message-composer select,.message-composer input{height:28px;min-width:0;border:1px solid #35506a;border-radius:5px;background:#050c13;color:#eaf1f7;font:9px ui-monospace,monospace;outline:0}.message-composer select{padding:0 6px}.message-composer input{padding:0 9px}.message-composer input:focus,.message-composer select:focus{border-color:var(--cyan)}.message-composer button{height:28px;border:1px solid rgba(50,246,193,.65);border-radius:5px;background:#0b2925;color:#baffea;font:8px ui-monospace,monospace;cursor:pointer}.message-composer button:disabled,.message-composer input:disabled,.message-composer select:disabled{opacity:.42;cursor:not-allowed}.terminal-foot{display:flex;align-items:center;gap:14px;padding:0 12px;border-top:1px solid #21374b;color:#71849a;background:#07111b;font:8px ui-monospace,monospace}.terminal-foot span:last-child{margin-left:auto}.cursor-block{display:inline-block;width:6px;height:11px;background:var(--text);vertical-align:-2px;animation:blink 1s step-end infinite}@keyframes blink{50%{opacity:.1}}
.inspector{background:var(--paper);color:var(--dark-text);display:grid;grid-template-rows:38px minmax(0,1fr)}.inspector .panel-head{color:#25313e;border-color:var(--paper-line);background:#fafbfc}.inspector-body{overflow:auto;padding:0 12px 14px;scrollbar-width:thin;scrollbar-color:#b7c1cc transparent}.inspect-section{padding:12px 0;border-bottom:1px solid #d4dae1}.inspect-section h3{margin:0 0 9px;color:#637080;font:8px ui-monospace,monospace}.inspect-row{display:grid;grid-template-columns:88px minmax(0,1fr);gap:8px;margin:5px 0;color:#596675;font-size:9px}.inspect-row b{color:#293540;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.verified-card{padding:10px;border:1px solid rgba(50,246,193,.5);border-radius:6px;background:#e9f8f4}.verified-card.bad{border-color:rgba(255,93,135,.45);background:#fff0f4}.verified-card.neutral{border-color:#aeb9c5;background:#edf1f5}.verified-card strong{color:#17765c;font-size:10px}.verified-card.bad strong{color:#b72c52}.verified-card.neutral strong{color:#536271}.head-digest{display:block;margin-top:7px;color:#5d6c78;font:7px ui-monospace,monospace;overflow:hidden;text-overflow:ellipsis}.score{height:7px;background:#dbe4e2;border-radius:4px;overflow:hidden;margin-top:8px}.score i{display:block;height:100%;width:98.7%;background:linear-gradient(90deg,var(--mint),var(--cyan))}.inspect-actions{display:flex;gap:7px;margin-top:10px}.inspect-actions button{height:27px;padding:0 9px;border:1px solid #8aa0b6;border-radius:5px;background:#f8fafc;color:#33414e;font-size:8px}.inspect-actions button.primary{border-color:#24bf99;color:#08785c;background:#e8f8f3}
.drain-state{padding:10px;border:1px solid #c8d0d9;border-radius:6px;background:#edf1f5}.drain-state strong{display:flex;align-items:center;gap:7px;color:#536271;font:10px ui-monospace,monospace}.drain-state strong:before{content:"";width:7px;height:7px;border-radius:50%;background:#8795a4}.drain-state.deny{border-color:rgba(255,93,135,.4);background:#fff0f4}.drain-state.deny strong{color:#b72c52}.drain-state.deny strong:before{background:var(--rose)}.drain-state.draining{border-color:rgba(255,211,77,.55);background:#fff9df}.drain-state.draining strong{color:#85680b}.drain-state.draining strong:before{background:var(--amber)}.drain-state.ready{border-color:rgba(50,246,193,.55);background:#e9f8f4}.drain-state.ready strong{color:#17765c}.drain-state.ready strong:before{background:#24bf99}.drain-counts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;margin:9px 0}.drain-count{padding:6px 3px;border:1px solid #d3dae2;border-radius:4px;background:#fafbfc;text-align:center}.drain-count b{display:block;color:#24313d;font:12px ui-monospace,monospace}.drain-count span{display:block;margin-top:2px;color:#74808c;font:6px ui-monospace,monospace}.drain-block{margin-top:8px;color:#596675;font:7px/1.4 ui-monospace,monospace;overflow-wrap:anywhere}.drain-hashes{display:grid;grid-template-columns:64px minmax(0,1fr);gap:4px 7px;margin-top:8px;color:#75818d;font:7px ui-monospace,monospace}.drain-hashes b{color:#374451;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.chronograph{min-height:0;display:grid;grid-template-rows:34px 1fr 30px;background:linear-gradient(90deg,#091522,#06101a 55%,#101427);border-top:1px solid #30465b}.chrono-head{display:flex;align-items:center;gap:18px;padding:0 14px;border-bottom:1px solid #2d4358;font-size:9px}.chrono-head strong{font-size:10px}.chrono-head .live-label{color:var(--mint);margin-left:70px}.chrono-legend{margin-left:auto;display:flex;gap:18px;color:#8798ab;font:8px ui-monospace,monospace}.chrono-legend i{display:inline-block;width:7px;height:7px;margin-right:5px}.chrono-wrap{position:relative;min-height:0}.chrono-wrap canvas{position:absolute;inset:0;width:100%;height:100%}.chrono-tip{position:absolute;display:none;min-width:156px;padding:8px;border:1px solid var(--cyan);border-radius:5px;background:#091a27;color:#eaf4fb;pointer-events:none;font:8px/1.45 ui-monospace,monospace;box-shadow:0 8px 20px rgba(0,0,0,.35)}.chrono-controls{display:flex;align-items:center;gap:14px;padding:0 14px;border-top:1px solid #2d4358;color:#8fa0b3;font:9px ui-monospace,monospace}.scrub{height:4px;flex:1;border-radius:2px;background:#32475d;position:relative}.scrub:after{content:"";position:absolute;left:68%;top:-3px;width:10px;height:10px;border-radius:50%;background:var(--cyan)}
.empty{padding:18px;color:var(--muted);font:10px ui-monospace,monospace}
@media(max-width:1280px){.workspace{grid-template-columns:230px 320px minmax(380px,1fr) 290px}.topbar{grid-template-columns:210px minmax(180px,300px) 1fr auto}.metric{display:none}}
@media(max-width:980px){:root{--chrono-h:170px}.topbar{grid-template-columns:170px 1fr auto;padding:0 9px}.command{display:none}.toolbar-center{justify-content:flex-start}.segments button{min-width:64px}.toolbar-status .live{display:none}.workspace{position:relative;display:block}.workspace>.panel{position:absolute;inset:0;border-right:0;display:none}.workspace>.terminal-panel{display:grid}body[data-surface="focus"] .workspace>.terminal-panel,body[data-surface="weave"] .workspace>.terminal-panel,body[data-surface="evidence"] .workspace>.terminal-panel{display:none}body[data-surface="focus"] .workspace>.fleet{display:grid}body[data-surface="weave"] .workspace>.weave{display:grid}body[data-surface="evidence"] .workspace>.inspector{display:grid}.fleet .lane{max-width:520px}.chrono-legend{display:none}}
@media(max-width:560px){.brand small{display:none}.brand{gap:7px}.mark{width:20px}.topbar{grid-template-columns:96px 1fr}.toolbar-status{display:none}.segments{width:100%}.segments button{min-width:0;flex:1}.graph-node{width:122px}.graph-node.selected{width:166px}.chrono-head .live-label{margin-left:auto}.chrono-head span:not(.live-label){display:none}}
@media(prefers-reduced-motion:reduce){.cursor-block{animation:none}}
</style>
</head>
<body data-surface="terminal">
<header class="topbar">
  <div class="brand"><div class="mark">L</div><div><strong>Loom</strong><small>Sounio Core</small></div></div>
  <label class="command"><span>/</span><input id="command" aria-label="Command palette" placeholder="Command palette"><kbd>Ctrl K</kbd></label>
  <div class="toolbar-center"><nav class="segments" aria-label="Workspace surfaces">
    <button data-surface="focus">Focus</button><button data-surface="weave" class="active">Weave</button><button data-surface="evidence">Evidence</button>
  </nav></div>
  <div class="toolbar-status"><div class="metric"><label>CONTINUITY HEALTH</label><b id="continuity">--</b></div><div class="cutover-pill" id="cutover-pill">9046 CONNECTING</div><button class="live" id="fleet-live">CONNECTING</button></div>
</header>
<main class="workspace">
  <aside class="panel fleet">
    <div class="panel-head"><strong>LANES</strong><small id="fleet-count">0 / 0</small><span class="spacer"></span><small>FILTER</small></div>
    <div class="fleet-list" id="lanes"></div>
    <div class="fleet-foot"><span id="fleet-summary">NO VERIFIED SESSIONS</span><b id="bus-state">READ ONLY</b></div>
  </aside>
  <section class="panel weave">
    <div class="panel-head"><strong>WEAVE</strong><small id="weave-title">Causal neighborhood</small><span class="spacer"></span><small id="weave-health">--</small></div>
    <div class="weave-stage" id="weave-stage">
      <canvas id="weave-fallback" aria-hidden="true"></canvas><canvas id="weave-gpu" aria-label="Live spectral causal field"></canvas><div class="weave-grid"></div>
      <svg class="weave-edges" viewBox="0 0 370 700" preserveAspectRatio="none" aria-hidden="true">
        <path d="M75 135 C75 230 150 220 185 305" stroke="#3588ff"/><path d="M295 135 C295 230 220 220 185 305" stroke="#32f6c1"/>
        <path d="M185 390 C185 470 80 455 75 530" stroke="#ff5d87" stroke-dasharray="5 4"/><path d="M185 390 C185 470 290 455 295 530" stroke="#ffd34d" stroke-dasharray="5 4"/>
      </svg>
      <span class="weave-label up">UPSTREAM / VERIFIED JOURNALS</span><span class="weave-label down">DOWNSTREAM / CUSTODY</span>
      <div class="graph-node node-a"><strong id="node-a-name">Provider A</strong><small id="node-a-meta">waiting</small></div>
      <div class="graph-node node-b"><strong id="node-b-name">Provider B</strong><small id="node-b-meta">waiting</small></div>
      <div class="graph-node selected node-core"><strong id="node-core-name">No lane selected</strong><small id="node-core-meta">durable session identity</small><div class="node-pulse"></div></div>
      <div class="graph-node node-gate"><strong id="node-gate-name">Semantic journal</strong><small id="node-gate-meta">not measured</small></div>
      <div class="graph-node node-store"><strong>Guardian custody</strong><small id="node-store-meta">not measured</small></div>
      <div class="shader-badge">RENDERER <b id="shader-mode">STARTING</b></div>
    </div>
  </section>
  <section class="panel terminal-panel">
    <div class="panel-head"><strong class="terminal-title" id="terminal-title">No lane selected</strong><span class="terminal-state" id="terminal-state">WAITING</span><span class="spacer"></span><small id="terminal-latency">WRITE CONNECTING</small></div>
    <pre class="terminal" id="terminal"></pre>
    <form class="message-composer" id="message-composer"><select id="message-kind" aria-label="Message kind" disabled><option value="info">INFO</option><option value="request">REQUEST</option><option value="blocker">BLOCKER</option></select><input id="message-text" aria-label="Message" autocomplete="off" placeholder="Message selected lane" disabled><button id="message-send" type="submit" disabled>SEND</button></form>
    <div class="terminal-foot"><span id="terminal-instance">instance --</span><span id="terminal-cursor">0 B</span><span id="terminal-runtime">LOOM VERIFIED SNAPSHOT</span><span><span class="cursor-block"></span></span></div>
  </section>
  <aside class="panel inspector">
    <div class="panel-head"><strong id="inspector-title">CONTEXT</strong><span class="spacer"></span><small>READ ONLY</small></div>
    <div class="inspector-body">
      <section class="inspect-section"><h3>AUTHORITY LATTICE</h3><div class="inspect-row"><span>Bus presence</span><b id="inspect-presence">missing</b></div><div class="inspect-row"><span>Delivery</span><b id="inspect-endpoint">missing</b></div><div class="inspect-row"><span>Loom custody</span><b id="inspect-custody">none</b></div><div class="inspect-row"><span>Generation</span><b id="inspect-instance">--</b></div><div class="inspect-row"><span>Guardian</span><b id="inspect-guardian">--</b></div><div class="inspect-row"><span>Harness PID</span><b id="inspect-harness">--</b></div><div class="inspect-row"><span>Last signal</span><b id="inspect-started">--</b></div></section>
      <section class="inspect-section"><h3>NATIVE HOOK GENERATION DRAIN</h3><div class="drain-state" id="drain-state"><strong id="drain-decision">NOT MEASURED</strong><div class="drain-counts"><div class="drain-count"><b id="drain-native">0</b><span>NATIVE</span></div><div class="drain-count"><b id="drain-legacy">0</b><span>LEGACY</span></div><div class="drain-count"><b id="drain-unknown">0</b><span>UNKNOWN</span></div><div class="drain-count"><b id="drain-unresponsive">0</b><span>UNRESP</span></div></div><div class="drain-hashes"><span>CURRENT</span><b id="drain-current">--</b><span>CANDIDATE</span><b id="drain-candidate">--</b><span>CANARIES</span><b id="drain-canaries">0 / 15</b><span>ROLLBACK</span><b id="drain-rollback">UNPROVEN</b><span>SIGNATURE</span><b id="drain-signature">UNVERIFIED</b></div><div class="drain-block" id="drain-block">authority snapshot pending</div></div></section>
      <section class="inspect-section"><h3>CAUSAL GENERATION RECONCILIATION</h3><div class="drain-state" id="reconcile-state"><strong id="reconcile-decision">9047 NOT MEASURED</strong><div class="drain-hashes"><span>CAUSE</span><b id="reconcile-cause">none</b><span>RELATED</span><b id="reconcile-related">0 BOUND</b><span>TRANSACTION</span><b id="reconcile-transaction">--</b><span>KERNEL</span><b id="reconcile-kernel">--</b><span>MUTATION</span><b id="reconcile-mutation">READ ONLY</b></div></div></section>
      <section class="inspect-section"><h3>OBSERVATION AUTHORITY</h3><div class="verified-card" id="verified-card"><strong id="verified-label">NOT MEASURED</strong><span class="head-digest" id="semantic-head">semantic --</span><span class="head-digest" id="guardian-head">guardian --</span></div></section>
      <section class="inspect-section"><h3>RECOVERY CONTINUITY</h3><div class="inspect-row"><span>Recoveries</span><b id="inspect-recoveries">0</b></div><div class="inspect-row"><span>Output cursor</span><b id="inspect-output">0 B</b></div><div class="inspect-row"><span>Command</span><b id="inspect-command">--</b></div><div class="score"><i id="score-bar"></i></div></section>
      <section class="inspect-section"><h3>WORKTREE</h3><div class="inspect-row"><span>Lane</span><b id="inspect-lane">--</b></div><div class="inspect-row"><span>Path</span><b id="inspect-worktree">--</b></div><div class="inspect-actions"><button class="primary" type="button">VERIFIED VIEW</button><button type="button" id="copy-instance">COPY INSTANCE</button></div></section>
    </div>
  </aside>
</main>
<section class="chronograph">
  <div class="chrono-head"><strong>EVENT CHRONOGRAPH</strong><span class="live-label" id="chrono-live">LIVE</span><span>LAST VERIFIED WINDOW</span><div class="chrono-legend"><span><i style="background:#ff5d57"></i>EXIT</span><span><i style="background:#40d8ff;border-radius:50%"></i>RECOVERY</span><span><i style="background:#a98bff;transform:rotate(45deg)"></i>LEASE</span><span><i style="background:#3588ff;border-radius:50%"></i>OUTPUT</span><span><i style="background:#32f6c1"></i>START</span></div></div>
  <div class="chrono-wrap" id="chrono-wrap"><canvas id="chrono" aria-label="Verified Loom event chronology"></canvas><div class="chrono-tip" id="chrono-tip"></div></div>
  <div class="chrono-controls"><span>PLAY</span><span>1x</span><div class="scrub"></div><span>-</span><span>+</span><span>FIT</span></div>
</section>
<script>
'use strict';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const lanes=q('#lanes'),term=q('#terminal'),chrono=q('#chrono'),chronoTip=q('#chrono-tip');
const state={sessions:[],fleet:null,drain:null,reconcile:null,eventGroups:[],selected:null,cursor:0,terminal:'',continuity:0,recoveries:0,shaderEpoch:0,write:{enabled:false,agent:'',lane:'',token:''},sending:false};
const palette=['#40d8ff','#32f6c1','#a98bff','#ff5d87','#ffd34d','#ff8e59','#3588ff'];
const healthColors={WORKING:'#32f6c1',IDLE:'#40d8ff',BLOCKED:'#ffd34d',DISCONNECTED:'#ff8e59',UNRESPONSIVE:'#ffe16a',ORPHANED:'#ff5d87',DEAD:'#ff5d57',CONFLICTED:'#a98bff',OBSERVED:'#40d8ff',UNKNOWN:'#64778c'};
const clean=s=>s.replace(/\x1b\[[0-?]*[ -\/]*[@-~]/g,'').replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'');
const short=(s,n=12)=>s&&s.length>n?s.slice(0,n):s||'--';
const groupFor=s=>{const a=(s.agent||'').toLowerCase();if(/claude|codex|grok|kimi|cursor/.test(a))return'Providers';if(/lean|coq|isabelle|tla/.test(a))return'Proofs';if(/web|api|data/.test(a))return'Surfaces';return'Coordination'};
const colorFor=(s,i=0)=>{const text=(s.agent||'')+(s.lane||'');let h=0;for(const ch of text)h=(h*31+ch.charCodeAt(0))>>>0;return palette[(h+i)%palette.length]};
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(url+' '+r.status);return r.json()}
function setText(id,value){const n=q(id);if(n)n.textContent=value}
function setSurface(surface){document.body.dataset.surface=surface;qa('.segments button').forEach(b=>b.classList.toggle('active',b.dataset.surface===surface))}
qa('.segments button').forEach(b=>b.addEventListener('click',()=>setSurface(b.dataset.surface)));
q('#command').addEventListener('keydown',e=>{if(e.key==='Enter'){const value=e.currentTarget.value.trim().toLowerCase();if(['focus','weave','evidence'].includes(value))setSurface(value);e.currentTarget.value=''}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();q('#command').focus()}});
function updateComposer(){const enabled=!!(state.write.enabled&&state.write.token&&state.selected&&!state.sending);q('#message-text').disabled=!enabled;q('#message-kind').disabled=!enabled;q('#message-send').disabled=!enabled;setText('#terminal-latency',state.sending?'SENDING':state.write.enabled?(state.selected?'WRITE READY':'SELECT LANE'):'READ ONLY')}
async function refreshWriteState(){try{state.write=await json('/api/write-state');updateComposer()}catch(e){state.write={enabled:false,agent:'',lane:'',token:''};updateComposer()}}
q('#message-composer').addEventListener('submit',async e=>{e.preventDefault();const s=state.selected,message=q('#message-text').value.trim();if(!s||!message||!state.write.enabled||state.sending)return;state.sending=true;updateComposer();try{const r=await fetch('/api/send',{method:'POST',headers:{'Content-Type':'application/json','X-Loom-Write-Token':state.write.token},body:JSON.stringify({toAgent:s.agent,toLane:s.lane,kind:q('#message-kind').value,message})}),receipt=await r.json();if(!r.ok)throw new Error(receipt.error||('HTTP '+r.status));q('#message-text').value='';setText('#terminal-latency','SENT '+short(receipt.messageId,18)+' / '+String(receipt.wake||'durable').toUpperCase())}catch(error){setText('#terminal-latency','SEND REFUSED / '+error.message)}finally{state.sending=false;const held=q('#terminal-latency').textContent;updateComposer();setText('#terminal-latency',held)}});
function drawSpark(canvas,color,seed){const dpr=devicePixelRatio||1,w=38,h=12;canvas.width=w*dpr;canvas.height=h*dpr;const x=canvas.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.strokeStyle=color;x.lineWidth=1;x.beginPath();for(let i=0;i<9;i++){const y=6+Math.sin(i*1.7+seed)*3+(i%3-1);i?x.lineTo(i*w/8,y):x.moveTo(0,y)}x.stroke()}
function laneKey(s){return(s.agent||'')+'\n'+(s.lane||'')}
function healthLabel(s){const health=s.health_state||'UNKNOWN';if(s.observation_authorized&&s.sample_fresh)return health;if(s.presence_state==='live'||s.endpoint_state==='active'||s.loom_state==='active')return'OBSERVED';return health}
function renderFleet(){lanes.replaceChildren();const grouped=new Map();state.sessions.forEach(s=>{const g=groupFor(s);if(!grouped.has(g))grouped.set(g,[]);grouped.get(g).push(s)});let index=0;for(const [name,list] of grouped){const h=document.createElement('div');h.className='fleet-group';h.append(document.createTextNode(name));const count=document.createElement('span');count.textContent=list.length;h.append(count);lanes.append(h);for(const s of list){index++;const health=healthLabel(s),b=document.createElement('button');b.className='lane '+health.toLowerCase()+(state.selected&&laneKey(state.selected)===laneKey(s)?' active':'');const idx=document.createElement('span');idx.className='lane-index';idx.textContent=String(index).padStart(2,'0');const label=document.createElement('span');label.className='lane-name';label.textContent=s.agent||'unknown';const detail=document.createElement('small');detail.textContent=(s.lane||'session')+' / '+(s.transport||'none');label.append(detail);const tail=document.createElement('span');tail.className='lane-tail';const dot=document.createElement('i');dot.className='state-dot';const col=healthColors[health]||healthColors.UNKNOWN;dot.style.background=col;dot.style.boxShadow='0 0 8px '+col;const st=document.createElement('span');st.className='lane-state';st.style.color=col;st.textContent=health;const spark=document.createElement('canvas');spark.className='spark';tail.append(dot,st,spark);b.append(idx,label,tail);b.onclick=()=>choose(s);lanes.append(b);drawSpark(spark,col,index)}}}
function selectedGroup(){return state.selected&&state.selected.loom_instance?state.eventGroups.find(g=>g.instance_id===state.selected.loom_instance):null}
function updateMetrics(){const summary=state.fleet&&state.fleet.summary||{},total=summary.lanes||state.sessions.length,working=summary.working||0,idle=summary.idle||0,blocked=summary.blocked||0,observed=state.sessions.filter(s=>healthLabel(s)==='OBSERVED').length,known=working+idle+blocked;state.continuity=total?known/total:0;state.recoveries=state.eventGroups.reduce((n,g)=>n+(g.recoveries||0),0);const authorized=!!(state.fleet&&state.fleet.observation_authorized);setText('#fleet-count',(authorized?working:observed)+' '+(authorized?'WORK':'OBSERVED')+' / '+total);setText('#fleet-live',authorized?(working+' WORKING / '+idle+' IDLE'):(observed+' OBSERVED / HEALTH LOCKED'));setText('#fleet-summary',authorized?('WORK '+working+' / BLOCK '+blocked+' / UNRESP '+(summary.unresponsive||0)+' / UNKNOWN '+(summary.unknown||0)):('OBSERVED '+observed+' / RAW LIVE '+(summary.live||0)+' / HEALTH UNVERIFIED'));setText('#bus-state',authorized?'SOUNIO VERIFIED':'READ ONLY');setText('#continuity',authorized&&total?(state.continuity*100).toFixed(1)+'%':'--');q('#score-bar').style.width=(authorized?(state.continuity*100).toFixed(1):'0')+'%'}
function updateWeave(){const s=state.selected,g=selectedGroup(),d=state.drain,health=s&&healthLabel(s);setText('#node-a-name','Coordination claim');setText('#node-a-meta',s?(s.claim_state+' / '+short(s.last_seen_utc,19)):'waiting');setText('#node-b-name','Delivery endpoint');setText('#node-b-meta',s?(s.endpoint_state+' / '+s.transport):'waiting');setText('#node-core-name',s?s.agent+' / '+s.lane:'No lane selected');setText('#node-core-meta',s?(health+' / generation '+short(s.loom_instance||s.session_id,16)+' / '+s.cursor+' B'):'durable session identity');setText('#node-gate-name',d?'Sounio 9046':'Semantic journal');setText('#node-gate-meta',d?(d.decision+' / '+short(d.authority&&d.authority.semantics_sha256,16)):s?('Sounio '+short(s.health_semantics_sha256,16)):g&&g.verified?'verified '+short(g.semantic_head):'not measured');setText('#node-store-meta',d?((d.cutover_ready?'cutover open':'cutover locked')+' / '+d.block_reason):s?(s.loom_state+' / guardian '+(s.guardian_pid||'--')):'not measured');setText('#weave-title',s?s.agent+' / '+s.lane:'Authority neighborhood');setText('#weave-health',d?(d.decision+' / ACTION 9046'):s?(health+' / '+s.presence_state.toUpperCase()+' / '+s.endpoint_state.toUpperCase()):'--')}
function updateDrain(){const d=state.drain;if(!d)return;document.body.dataset.cutover=String(d.decision||'fail_closed').toLowerCase();setText('#cutover-pill','9046 '+d.decision);setText('#drain-decision',d.decision+' / '+(d.cutover_command_exposed?'COMMAND OPEN':'COMMAND LOCKED'));const box=q('#drain-state');box.classList.toggle('ready',d.decision==='CUTOVER_READY');box.classList.toggle('draining',d.decision==='DRAINING');box.classList.toggle('deny',d.decision!=='DRAINING'&&d.decision!=='CUTOVER_READY');const inv=d.inventory||{},bind=d.bindings||{},can=d.canaries||{},att=d.ui_attestation||{};setText('#drain-native',inv.native||0);setText('#drain-legacy',inv.legacy||0);setText('#drain-unknown',inv.unknown||0);setText('#drain-unresponsive',inv.unresponsive||0);setText('#drain-current',short(bind.current_runtime_id||bind.old_runtime_sha256,26));setText('#drain-candidate',short(bind.candidate_runtime_id||bind.candidate_runtime_sha256,26));setText('#drain-canaries',(can.mask||0)+' / '+(can.required_mask||15));setText('#drain-rollback',d.rollback_pair_tested?'PROVEN':'UNPROVEN');setText('#drain-signature',att.verified?('VERIFIED '+short(att.key_id,12)):'UNVERIFIED');setText('#drain-block',d.block_reason+' / inventory '+(inv.fresh&&inv.complete?'FRESH+COMPLETE':'INCOMPLETE')+' / ui '+(att.verified?'SIGNED':'UNSIGNED')+' / receipt '+short(d.authority&&d.authority.output_sha256,16));updateWeave()}
function updateReconcile(){const r=state.reconcile||{decision:'NOT MEASURED',absence_reason:'none',related_total:0,transaction_sha256:'',kernel_observation_sha256:''},decision=r.decision||'FAIL_CLOSED',box=q('#reconcile-state');setText('#reconcile-decision','9047 '+decision);box.classList.toggle('ready',decision==='KEEP');box.classList.toggle('draining',decision==='QUARANTINE_ELIGIBLE');box.classList.toggle('deny',decision==='FAIL_CLOSED'||decision.startsWith('DENY'));setText('#reconcile-cause',r.absence_reason||r.reason||'none');setText('#reconcile-related',String(r.related_total||0)+' BOUND');setText('#reconcile-transaction',short(r.transaction_sha256,26));setText('#reconcile-kernel',short(r.kernel_observation_sha256,26));setText('#reconcile-mutation',r.mutation_applied?'APPLIED':'READ ONLY')}
function updateInspector(){const s=state.selected,g=selectedGroup(),health=s&&healthLabel(s);setText('#inspector-title',s?(s.agent+' / '+health).toUpperCase():'CONTEXT');setText('#inspect-presence',s?(s.presence_state+' / '+s.presence_reason):'missing');setText('#inspect-endpoint',s?(s.endpoint_state+' / '+s.transport):'missing');setText('#inspect-custody',s?s.loom_state:'none');setText('#inspect-instance',s?short(s.loom_instance||s.session_id,20):'--');setText('#inspect-guardian',s?s.guardian_pid||'--':'--');setText('#inspect-harness',s?s.harness_pid||s.pid||'--':'--');setText('#inspect-started',s?s.last_seen_utc||s.started_utc||'--':'--');setText('#inspect-recoveries',g?g.recoveries||0:0);setText('#inspect-output',s?s.cursor+' B':'0 B');setText('#inspect-command',s?s.command||s.harness||'--':'--');setText('#inspect-lane',s?s.lane||'--':'--');setText('#inspect-worktree',s?s.worktree||'--':'--');const verified=!!(s&&s.observation_authorized&&s.sample_fresh),observed=!!(s&&!verified&&health==='OBSERVED'),card=q('#verified-card');card.classList.toggle('bad',!!s&&!verified&&!observed);card.classList.toggle('neutral',!s||observed);setText('#verified-label',verified?'SOUNIO HEALTH OBSERVATION VERIFIED':observed?'SESSION OBSERVED / HEALTH UNVERIFIED':'HEALTH OBSERVATION FAIL CLOSED');setText('#semantic-head','semantic '+(s?short(s.health_semantics_sha256,28):'--'));setText('#guardian-head','OCaml realization / state '+(health||'--'))}
function choose(s){const changed=!state.selected||laneKey(state.selected)!==laneKey(s),health=healthLabel(s);state.selected=s;if(changed){state.cursor=0;state.terminal='';state.reconcile=null;term.textContent='';updateReconcile();setSurface(innerWidth<981?'terminal':'weave');refreshReconcile()}setText('#terminal-title',s.agent+' / '+s.lane);setText('#terminal-state',health);q('#terminal-state').style.color=healthColors[health]||healthColors.UNKNOWN;setText('#terminal-instance','generation '+short(s.loom_instance||s.session_id,18));setText('#terminal-cursor',s.cursor+' B');setText('#terminal-runtime',s.loom_state==='none'?'TRUTHFUL BUS OBSERVATION':'LOOM VERIFIED SNAPSHOT');if(s.loom_state==='none'){term.textContent=['HEALTH        '+(s.observation_authorized?health:'UNVERIFIED'),'OBSERVATION   '+(health==='OBSERVED'?'SESSION PRESENT':'NO TRUSTED HEALTH'),'AUTHORITY     '+(s.observation_authorized?'SOUNIO VERIFIED':'FAIL CLOSED'),'BUS PRESENCE  '+s.presence_state.toUpperCase(),'DELIVERY      '+s.endpoint_state.toUpperCase()+' / '+s.transport,'OBLIGATIONS   '+s.active_obligations+' ACTIVE / '+s.pending_obligations+' PENDING','PROGRESS      '+(s.progress_observed?'OBSERVED':s.progress_window_complete?'NONE IN WINDOW':'WINDOW OPEN'),'GENERATION    '+(s.session_id||'--'),'LAST SIGNAL   '+(s.last_seen_utc||'--')].join('\n')}updateWeave();updateInspector();updateComposer();renderFleet();pollSnapshot()}
async function pollSnapshot(){const s=state.selected;if(!s||s.loom_state==='none')return;try{const params=new URLSearchParams({agent:s.agent,lane:s.lane,cursor:String(state.cursor)}),r=await fetch('/api/snapshot?'+params,{cache:'no-store'});if(!r.ok)return;const data=new Uint8Array(await r.arrayBuffer());state.cursor=Number(r.headers.get('x-loom-cursor')||state.cursor);if(data.length){state.terminal+=clean(new TextDecoder().decode(data));if(state.terminal.length>240000)state.terminal=state.terminal.slice(-240000);term.textContent=state.terminal;term.scrollTop=term.scrollHeight}setText('#terminal-cursor',state.cursor+' B')}catch(e){setText('#terminal-state','SNAPSHOT ERROR')}}
async function refreshSessions(){try{const fleet=await json('/api/fleet'),list=fleet.lanes||[];state.fleet=fleet;state.sessions=list;const current=state.selected&&list.find(s=>laneKey(s)===laneKey(state.selected));if(current)state.selected=current;else if(list.length)state.selected=list.find(s=>s.health_state==='WORKING')||list.find(s=>s.health_state==='BLOCKED')||list.find(s=>s.health_state==='UNRESPONSIVE')||list.find(s=>s.loom_state==='active')||list[0];renderFleet();updateMetrics();if(state.selected)choose(state.selected);else{lanes.replaceChildren();const e=document.createElement('div');e.className='empty';e.textContent='No coordination records';lanes.append(e)}}catch(e){setText('#fleet-live','DISCONNECTED');setText('#bus-state','OFFLINE')}}
async function refreshEvents(){try{state.eventGroups=await json('/api/events');updateMetrics();updateWeave();updateInspector();drawChronograph()}catch(e){setText('#chrono-live','EVENT FEED OFFLINE')}}
async function refreshDrain(){try{state.drain=await json('/api/hook-generation-drain');updateDrain()}catch(e){state.drain={decision:'FAIL_CLOSED',cutover_command_exposed:false,block_reason:'generation-drain-endpoint-offline',inventory:{},bindings:{},canaries:{}};updateDrain()}}
async function refreshReconcile(){const s=state.selected;if(!s)return;const key=laneKey(s),params=new URLSearchParams({agent:s.agent,lane:s.lane});try{const result=await json('/api/hook-generation-reconcile?'+params);if(state.selected&&laneKey(state.selected)===key){state.reconcile=result;updateReconcile()}}catch(e){if(state.selected&&laneKey(state.selected)===key){state.reconcile={decision:'FAIL_CLOSED',reason:'generation-reconcile-endpoint-offline'};updateReconcile()}}}
q('#copy-instance').addEventListener('click',async()=>{if(state.selected&&navigator.clipboard)await navigator.clipboard.writeText(state.selected.loom_instance||state.selected.session_id||'')});
function eventColor(kind){if(/RECOVER/.test(kind))return'#40d8ff';if(/EXIT|SIGNAL/.test(kind))return'#ff5d57';if(/LEASE|OBSERVER|WAKE/.test(kind))return'#a98bff';if(/START/.test(kind))return'#32f6c1';if(/OUTPUT/.test(kind))return'#3588ff';return'#ffd34d'}
let chronoPoints=[];
function drawChronograph(){const wrap=q('#chrono-wrap'),rect=wrap.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(1,rect.width),h=Math.max(1,rect.height);chrono.width=w*dpr;chrono.height=h*dpr;const x=chrono.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.font='8px ui-monospace, monospace';const groups=state.eventGroups.slice(0,5),left=112,right=12,top=20,bottom=10,trackH=Math.max(18,(h-top-bottom)/Math.max(groups.length,1));let events=[];groups.forEach((g,gi)=>g.events.forEach(e=>events.push({...e,lane:g.lane,agent:g.agent,gi})));events=events.filter((e,i)=>!(/OUTPUT/.test(e.kind))||i%7===0).slice(-800);const times=events.map(e=>Date.parse(e.utc)).filter(Number.isFinite),now=Date.now(),min=times.length?Math.min(...times):now-7200000,max=times.length?Math.max(...times,now):now;chronoPoints=[];x.strokeStyle='#294057';x.fillStyle='#8394a8';for(let i=0;i<7;i++){const px=left+(w-left-right)*i/6;x.beginPath();x.moveTo(px,top);x.lineTo(px,h-bottom);x.stroke();const dt=new Date(min+(max-min)*i/6);x.fillText(dt.toISOString().slice(11,16),px+4,12)}groups.forEach((g,gi)=>{const y=top+trackH*(gi+.5);x.strokeStyle='#294057';x.beginPath();x.moveTo(left,y);x.lineTo(w-right,y);x.stroke();x.fillStyle=g.instance_id===(state.selected&&state.selected.loom_instance)?'#40d8ff':'#9aa9ba';x.fillText(short(g.agent,13),10,y+3)});for(const e of events){const ms=Date.parse(e.utc);if(!Number.isFinite(ms))continue;const px=left+(w-left-right)*(ms-min)/Math.max(1,max-min),py=top+trackH*(e.gi+.5),col=eventColor(e.kind);x.fillStyle=col;if(/LEASE|OBSERVER|WAKE/.test(e.kind)){x.save();x.translate(px,py);x.rotate(Math.PI/4);x.fillRect(-4,-4,8,8);x.restore()}else if(/RECOVER|OUTPUT/.test(e.kind)){x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill()}else x.fillRect(px-3.5,py-3.5,7,7);chronoPoints.push({x:px,y:py,event:e})}const nx=left+(w-left-right)*(now-min)/Math.max(1,max-min);x.strokeStyle='#40d8ff';x.beginPath();x.moveTo(nx,top);x.lineTo(nx,h-bottom);x.stroke();setText('#chrono-live',state.eventGroups.length?(state.eventGroups.every(g=>g.verified)?'VERIFIED LIVE':'PARTIAL'):'NO LOOM EVENTS')}
chrono.addEventListener('mousemove',e=>{const r=chrono.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,p=chronoPoints.find(p=>Math.hypot(p.x-mx,p.y-my)<8);if(!p){chronoTip.style.display='none';return}chronoTip.style.display='block';chronoTip.style.left=Math.min(r.width-170,p.x+10)+'px';chronoTip.style.top=Math.max(4,p.y-48)+'px';chronoTip.textContent=p.event.utc.slice(11,19)+' / '+p.event.agent+' / '+p.event.kind});chrono.addEventListener('mouseleave',()=>chronoTip.style.display='none');
const gpuCanvas=q('#weave-gpu'),fallbackCanvas=q('#weave-fallback'),stage=q('#weave-stage');let gpuSize={w:1,h:1},gpuRender=null;
function sizeSpectral(){const r=stage.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);gpuSize={w:Math.max(1,Math.floor(r.width*dpr)),h:Math.max(1,Math.floor(r.height*dpr))};gpuCanvas.width=gpuSize.w;gpuCanvas.height=gpuSize.h;fallbackCanvas.width=gpuSize.w;fallbackCanvas.height=gpuSize.h;drawFallback(performance.now()/1000)}
function drawFallback(time){fallbackCanvas.style.display='block';const x=fallbackCanvas.getContext('2d'),w=fallbackCanvas.width,h=fallbackCanvas.height;x.clearRect(0,0,w,h);const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#f6eefa');g.addColorStop(.45,'#edf6fa');g.addColorStop(1,'#eaf8f2');x.fillStyle=g;x.fillRect(0,0,w,h);x.globalAlpha=.2;for(let i=0;i<5;i++){x.strokeStyle=palette[i];x.lineWidth=2;x.beginPath();for(let px=0;px<=w;px+=16){const py=h*(.22+i*.13)+Math.sin(px*.012+time+i)*h*.035;px?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()}x.globalAlpha=1}
async function initSpectral(){const epoch=++state.shaderEpoch;gpuCanvas.style.display='none';drawFallback(0);if(!navigator.gpu){setText('#shader-mode','CANVAS 2D');return}try{const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'}),device=await adapter?.requestDevice();if(!device)throw new Error('no WebGPU device');const context=gpuCanvas.getContext('webgpu'),format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format,alphaMode:'premultiplied'});const module=device.createShaderModule({code:`
struct Uniforms { resolution: vec2f, time: f32, energy: f32, recovery: f32, continuity: f32, sessions: f32, pad: f32 };
@group(0) @binding(0) var<uniform> u: Uniforms;
@vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f { let p=array(vec2f(-1.,-1.),vec2f(3.,-1.),vec2f(-1.,3.)); return vec4f(p[i],0.,1.); }
fn band(uv:vec2f,offset:f32,freq:f32)->f32 { let y=.18+offset+sin(uv.x*freq+u.time*(.22+offset))*0.045; return exp(-abs(uv.y-y)*90.); }
@fragment fn fs(@builtin(position) pos:vec4f)->@location(0) vec4f { let uv=pos.xy/u.resolution; let c1=vec3f(.25,.85,1.); let c2=vec3f(.2,.96,.76); let c3=vec3f(.66,.54,1.); let c4=vec3f(1.,.36,.53); let field=band(uv,.05,8.)*c1+band(uv,.22,10.)*c2+band(uv,.39,7.)*c3+band(uv,.55,11.)*c4; let haze=.035+.055*u.energy+.035*u.recovery; let base=mix(vec3f(.965,.97,.98),vec3f(.9,.965,.97),uv.x*.45); return vec4f(base+field*haze,1.); }
`});const pipeline=device.createRenderPipeline({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format}]}}),buffer=device.createBuffer({size:32,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}),bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer}}]});device.lost.then(()=>{if(epoch===state.shaderEpoch){setText('#shader-mode','RECOVERING');initSpectral()}});gpuCanvas.style.display='block';fallbackCanvas.style.display='none';setText('#shader-mode','WEBGPU');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function frame(ms){if(epoch!==state.shaderEpoch)return;const data=new Float32Array([gpuSize.w,gpuSize.h,reduced?0:ms/1000,state.sessions.filter(s=>s.health_state==='WORKING').length/Math.max(1,state.sessions.length),Math.min(1,state.recoveries/4),state.continuity,Math.min(1,state.sessions.length/23),0]);device.queue.writeBuffer(buffer,0,data);const encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:context.getCurrentTexture().createView(),clearValue:[.96,.97,.98,1],loadOp:'clear',storeOp:'store'}]});pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.draw(3);pass.end();device.queue.submit([encoder.finish()]);requestAnimationFrame(frame)}requestAnimationFrame(frame)}catch(e){setText('#shader-mode','CANVAS 2D');gpuCanvas.style.display='none';fallbackCanvas.style.display='block'}}
new ResizeObserver(()=>{sizeSpectral();drawChronograph()}).observe(stage);new ResizeObserver(drawChronograph).observe(q('#chrono-wrap'));
sizeSpectral();initSpectral();refreshWriteState();refreshSessions();refreshEvents();refreshDrain();setInterval(refreshSessions,2000);setInterval(refreshEvents,2000);setInterval(refreshDrain,2000);setInterval(refreshReconcile,4000);
</script>
</body>
</html>|loom}
