import Foundation

/// O sistema de design não é duplicado aqui.
///
/// O gerador lê os mesmos arquivos CSS que o app React usa. Assim a comparação
/// entre os dois geradores isola o modelo de geração — quem garante o quê, o
/// que cada um consegue produzir — em vez de comparar quem escreveu CSS melhor.
enum Design {
    static func css(webRoot: URL) throws -> String {
        let files = [
            "src/styles/tokens.css",
            "src/App.css",
            "src/components/corpus.css",
            "src/components/dose.css",
            "src/components/h2.css",
            "src/pages/proof.css",
            "src/pages/honesty.css",
        ]
        var out = "/* CSS lido de web/ — fonte única com o app React */\n"
        for f in files {
            let url = webRoot.appendingPathComponent(f)
            guard let text = try? String(contentsOf: url, encoding: .utf8) else { continue }
            out += "\n/* ---- \(f) ---- */\n" + text
        }
        return out
    }

    static let fonts = """
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?\
    family=JetBrains+Mono:wght@400;500;700&display=swap">
    """

    /// Escapa texto para HTML. Sem isto, um `reason` de artefato com < ou &
    /// quebraria a página — e os artefatos são dados de fora do nosso controle.
    static func esc(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }

    static func page(title: String, css: String, nav: String, body: String) -> String {
        """
        <!doctype html>
        <html lang="en"><head><meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>\(esc(title))</title>
        \(fonts)
        <style>\(css)</style>
        </head><body>
        <header class="masthead">
          <a class="lockup" href="index.html">
            <img class="column" src="brand/column_verdigris.png" alt="" aria-hidden="true">
            <span class="wordmark">Sounio</span>
          </a>
          <nav class="nav">\(nav)</nav>
          <button class="theme" type="button" data-theme-toggle aria-label="Toggle theme">
            <span aria-hidden="true">◐</span>
          </button>
        </header>
        \(body)
        <footer class="colophon">
          <img class="column column-sm" src="brand/column_verdigris.png" alt="" aria-hidden="true">
          <p>Generated by <code>sitegen</code> in Swift, reading
          <code>artifacts/**/*.json</code>. Every numeral passed through
          <code>Claim</code>, whose initializer is private.</p>
        </footer>
        <script type="module" src="islands.js"></script>
        </body></html>
        """
    }
}
