#!/usr/bin/env bash
set -euo pipefail

SOUNIO_DIR="${SOUNIO_DIR:-/home/devsounio/sounio}"
PROFILE="${PROFILE:-lowdata}"
TEMPORAL_PROFILE="${TEMPORAL_PROFILE:-v5}"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"

case "${TEMPORAL_PROFILE}" in
  v2)
    MANIFEST_PATH_DEFAULT="/orangefs/training/sounio/abide-data/abide_roi_manifest.tsv"
    ;;
  v3)
    MANIFEST_PATH_DEFAULT="/orangefs/training/sounio/abide-data/abide_roi_temporal_manifest_v3.tsv"
    ;;
  v4)
    MANIFEST_PATH_DEFAULT="/orangefs/training/sounio/abide-data/abide_roi_temporal_manifest_v4_pca.tsv"
    ;;
  v5)
    MANIFEST_PATH_DEFAULT="/orangefs/training/sounio/abide-data/abide_roi_temporal_manifest_v5_pca_delta.tsv"
    ;;
  *)
    echo "unsupported TEMPORAL_PROFILE=${TEMPORAL_PROFILE}; expected v2|v3|v4|v5" >&2
    exit 1
    ;;
esac

ABIDE_MANIFEST_PATH="${ABIDE_MANIFEST_PATH:-${MANIFEST_PATH_DEFAULT}}"

case "${PROFILE}" in
  lowdata)
    TRAIN_FRACTION="${TRAIN_FRACTION:-0.25}"
    DROP_CHANNEL_FRAC="${DROP_CHANNEL_FRAC:-0.0}"
    NOISE_STD="${NOISE_STD:-0.0}"
    PROFILE_TAG="lowdata-tf${TRAIN_FRACTION}"
    ;;
  missing)
    TRAIN_FRACTION="${TRAIN_FRACTION:-1.0}"
    DROP_CHANNEL_FRAC="${DROP_CHANNEL_FRAC:-0.25}"
    NOISE_STD="${NOISE_STD:-0.0}"
    PROFILE_TAG="missing-dc${DROP_CHANNEL_FRAC}"
    ;;
  noise)
    TRAIN_FRACTION="${TRAIN_FRACTION:-1.0}"
    DROP_CHANNEL_FRAC="${DROP_CHANNEL_FRAC:-0.0}"
    NOISE_STD="${NOISE_STD:-0.10}"
    PROFILE_TAG="noise-ns${NOISE_STD}"
    ;;
  *)
    echo "unsupported PROFILE=${PROFILE}; expected lowdata|missing|noise" >&2
    exit 1
    ;;
esac

RUN_ID="${RUN_ID:-brain-ossm-abide-${TEMPORAL_PROFILE}-${PROFILE_TAG}-${TIMESTAMP}}"
ORANGEFS_RESULTS_DIR="${ORANGEFS_RESULTS_DIR:-/orangefs/training/sounio/abide-robustness/${TEMPORAL_PROFILE}-${PROFILE_TAG}}"
PERSIST_MODE="${PERSIST_MODE:-worker_local}"
SBATCH_NODELIST="${SBATCH_NODELIST:-gpuorangefs-r770-proxmox}"
SBATCH_EXCLUDE="${SBATCH_EXCLUDE:-}"

echo "Submitting ABIDE robustness run:"
echo "  PROFILE=${PROFILE}"
echo "  TEMPORAL_PROFILE=${TEMPORAL_PROFILE}"
echo "  ABIDE_MANIFEST_PATH=${ABIDE_MANIFEST_PATH}"
echo "  TRAIN_FRACTION=${TRAIN_FRACTION}"
echo "  DROP_CHANNEL_FRAC=${DROP_CHANNEL_FRAC}"
echo "  NOISE_STD=${NOISE_STD}"
echo "  OCT_TRAIN_EPOCHS=${OCT_TRAIN_EPOCHS:-default}"
echo "  OCT_TRAIN_LR=${OCT_TRAIN_LR:-default}"
echo "  OCT_CORE_LR_SCALE=${OCT_CORE_LR_SCALE:-default}"
echo "  OCT_WARMUP_EPOCHS=${OCT_WARMUP_EPOCHS:-default}"
echo "  OCT_TRAIN_PROFILE=${OCT_TRAIN_PROFILE:-o_default}"
echo "  OCT_TRAIN_MODE=${OCT_TRAIN_MODE:-default}"
echo "  OCT_INIT_PRESET=${OCT_INIT_PRESET:-default}"
echo "  OCT_ASSOC_REG=${OCT_ASSOC_REG:-default}"
echo "  OCT_ASSOC_TARGET=${OCT_ASSOC_TARGET:-default}"
echo "  OCT_ASSOC_SCHEDULE_MODE=${OCT_ASSOC_SCHEDULE_MODE:-default}"
echo "  OCT_ASSOC_SCHEDULE_START=${OCT_ASSOC_SCHEDULE_START:-default}"
echo "  OCT_ASSOC_SCHEDULE_MID=${OCT_ASSOC_SCHEDULE_MID:-default}"
echo "  OCT_ASSOC_SCHEDULE_END=${OCT_ASSOC_SCHEDULE_END:-default}"
echo "  OCT_ASSOC_DRIFT_REG=${OCT_ASSOC_DRIFT_REG:-default}"
echo "  OCT_HEAD_TRUST_REGION=${OCT_HEAD_TRUST_REGION:-default}"
echo "  OCT_HEAD_RENORM=${OCT_HEAD_RENORM:-default}"
echo "  OCT_INPUT_PROJ_MODE=${OCT_INPUT_PROJ_MODE:-identity}"
echo "  OCT_PROJ_LR_SCALE=${OCT_PROJ_LR_SCALE:-0.6}"
echo "  OCT_PROJ_STRUCTURED_SCALE=${OCT_PROJ_STRUCTURED_SCALE:-0.35}"
echo "  OCT_PROJ_DELTA_SCALE=${OCT_PROJ_DELTA_SCALE:-0.18}"
echo "  OCT_PROJ_HYBRID_SCALE=${OCT_PROJ_HYBRID_SCALE:-0.12}"
echo "  H_TRAIN_EPOCHS=${H_TRAIN_EPOCHS:-default}"
echo "  H_TRAIN_LR=${H_TRAIN_LR:-default}"
echo "  H_CORE_LR_SCALE=${H_CORE_LR_SCALE:-default}"
echo "  H_WARMUP_EPOCHS=${H_WARMUP_EPOCHS:-default}"
echo "  H_INIT_PRESET=${H_INIT_PRESET:-default}"
echo "  H_INPUT_PROJ_MODE=${H_INPUT_PROJ_MODE:-identity}"
echo "  H_PROJ_LR_SCALE=${H_PROJ_LR_SCALE:-0.6}"
echo "  RUN_ID=${RUN_ID}"
echo "  ORANGEFS_RESULTS_DIR=${ORANGEFS_RESULTS_DIR}"
echo "  PERSIST_MODE=${PERSIST_MODE}"
echo "  SBATCH_NODELIST=${SBATCH_NODELIST}"
echo "  SBATCH_EXCLUDE=${SBATCH_EXCLUDE:-none}"

RUN_ID="${RUN_ID}" \
ABIDE_MANIFEST_PATH="${ABIDE_MANIFEST_PATH}" \
TRAIN_FRACTION="${TRAIN_FRACTION}" \
DROP_CHANNEL_FRAC="${DROP_CHANNEL_FRAC}" \
NOISE_STD="${NOISE_STD}" \
OCT_TRAIN_EPOCHS="${OCT_TRAIN_EPOCHS:-}" \
OCT_TRAIN_LR="${OCT_TRAIN_LR:-}" \
OCT_CORE_LR_SCALE="${OCT_CORE_LR_SCALE:-}" \
OCT_WARMUP_EPOCHS="${OCT_WARMUP_EPOCHS:-}" \
OCT_TRAIN_PROFILE="${OCT_TRAIN_PROFILE:-o_default}" \
OCT_TRAIN_MODE="${OCT_TRAIN_MODE:-}" \
OCT_INIT_PRESET="${OCT_INIT_PRESET:-}" \
OCT_ASSOC_REG="${OCT_ASSOC_REG:-}" \
OCT_ASSOC_TARGET="${OCT_ASSOC_TARGET:-}" \
OCT_ASSOC_SCHEDULE_MODE="${OCT_ASSOC_SCHEDULE_MODE:-}" \
OCT_ASSOC_SCHEDULE_START="${OCT_ASSOC_SCHEDULE_START:-}" \
OCT_ASSOC_SCHEDULE_MID="${OCT_ASSOC_SCHEDULE_MID:-}" \
OCT_ASSOC_SCHEDULE_END="${OCT_ASSOC_SCHEDULE_END:-}" \
OCT_ASSOC_DRIFT_REG="${OCT_ASSOC_DRIFT_REG:-}" \
OCT_HEAD_TRUST_REGION="${OCT_HEAD_TRUST_REGION:-}" \
OCT_HEAD_RENORM="${OCT_HEAD_RENORM:-}" \
OCT_INPUT_PROJ_MODE="${OCT_INPUT_PROJ_MODE:-identity}" \
OCT_PROJ_LR_SCALE="${OCT_PROJ_LR_SCALE:-0.6}" \
OCT_PROJ_STRUCTURED_SCALE="${OCT_PROJ_STRUCTURED_SCALE:-0.35}" \
OCT_PROJ_DELTA_SCALE="${OCT_PROJ_DELTA_SCALE:-0.18}" \
OCT_PROJ_HYBRID_SCALE="${OCT_PROJ_HYBRID_SCALE:-0.12}" \
H_TRAIN_EPOCHS="${H_TRAIN_EPOCHS:-}" \
H_TRAIN_LR="${H_TRAIN_LR:-}" \
H_CORE_LR_SCALE="${H_CORE_LR_SCALE:-}" \
H_WARMUP_EPOCHS="${H_WARMUP_EPOCHS:-}" \
H_INIT_PRESET="${H_INIT_PRESET:-}" \
H_INPUT_PROJ_MODE="${H_INPUT_PROJ_MODE:-identity}" \
H_PROJ_LR_SCALE="${H_PROJ_LR_SCALE:-0.6}" \
ORANGEFS_RESULTS_DIR="${ORANGEFS_RESULTS_DIR}" \
PERSIST_MODE="${PERSIST_MODE}" \
SBATCH_NODELIST="${SBATCH_NODELIST}" \
SBATCH_EXCLUDE="${SBATCH_EXCLUDE}" \
bash "${SOUNIO_DIR}/slurm-jobs/brain-ossm/submit-abide-campaign-gpu.sh"
