// C++ MATERIAL_PARITY probe for frozen Sounio xclbin receipt semantics.
// It emits material facts only. Sounio alone opens or refuses parity.

#include "material_sha256.hpp"

#include <array>
#include <cerrno>
#include <cstdint>
#include <filesystem>
#include <fcntl.h>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <vector>

namespace {

constexpr std::uintmax_t kArtifactSize = 41112056;
constexpr char kArtifactDigest[] =
    "d30078c7b2e8690aef892b4b6cf96af0f490b70e2b367e5e3679be04fcd4bdbf";
constexpr char kParentSemantics[] =
    "e7d4a83e81c054a1d15808292d49fbcda6ea43a06dbf31469e7c4c81d51d3fe5";
constexpr char kParentFreeze[] =
    "89278d99fab89bc2b582958a27d2806775b0b13a1e8f258550924fc20e3dc05e";
constexpr char kToolchainDigest[] =
    "a1e020d492e3da5d2a994606dc7969a5ee64968b1eb388443635d0d205729f8f";
constexpr char kHardwareDigest[] =
    "6e106fbdc3b9ce6cd8795bc2229f7ac1a2d57c90321afe77cc18270d48e151a8";
constexpr char kCommandDigest[] =
    "835e77c055184092c24616016ae85c347288dead3489a21c4204fdcfa31b4bc2";
constexpr char kResultDigest[] =
    "2d35e8ebaf5723b7d024299c1c21defe4b6e73dd7e8cb06a4455ac877c01060a";

struct ToolResult {
  int exit_code = 127;
  std::string output;
};

std::string sha256_file(const std::filesystem::path& path) {
  std::ifstream input(path, std::ios::binary);
  if (!input) {
    return {};
  }
  pireus::material::Sha256 sha;
  std::array<std::uint8_t, 1U << 16U> buffer{};
  while (input) {
    input.read(reinterpret_cast<char*>(buffer.data()), buffer.size());
    const std::streamsize count = input.gcount();
    if (count > 0) {
      sha.update(buffer.data(), static_cast<std::size_t>(count));
    }
  }
  return pireus::material::digest_hex(sha.finish());
}

ToolResult run_xclbinutil(const char* tool, const char* artifact) {
  int output_pipe[2] = {-1, -1};
  if (pipe(output_pipe) != 0) {
    return {};
  }
  const pid_t child = fork();
  if (child < 0) {
    close(output_pipe[0]);
    close(output_pipe[1]);
    return {};
  }
  if (child == 0) {
    (void)dup2(output_pipe[1], STDOUT_FILENO);
    const int null_fd = open("/dev/null", O_WRONLY);
    if (null_fd >= 0) {
      (void)dup2(null_fd, STDERR_FILENO);
    }
    close(output_pipe[0]);
    close(output_pipe[1]);
    char* const arguments[] = {
        const_cast<char*>(tool), const_cast<char*>("--info"),
        const_cast<char*>("--input"), const_cast<char*>(artifact), nullptr};
    execv(tool, arguments);
    _exit(127);
  }
  close(output_pipe[1]);
  ToolResult result;
  std::array<char, 8192> buffer{};
  while (true) {
    const ssize_t count = read(output_pipe[0], buffer.data(), buffer.size());
    if (count > 0) {
      result.output.append(buffer.data(), static_cast<std::size_t>(count));
      continue;
    }
    if (count < 0 && errno == EINTR) {
      continue;
    }
    break;
  }
  close(output_pipe[0]);
  int status = 0;
  while (waitpid(child, &status, 0) < 0 && errno == EINTR) {}
  result.exit_code = WIFEXITED(status) ? WEXITSTATUS(status) : 128;
  return result;
}

bool contains(const std::string& text, std::string_view needle) {
  return text.find(needle) != std::string::npos;
}

std::size_t count_occurrences(const std::string& text,
                              std::string_view needle) {
  std::size_t count = 0;
  std::size_t position = 0;
  while ((position = text.find(needle, position)) != std::string::npos) {
    ++count;
    position += needle.size();
  }
  return count;
}

bool argument_block_matches(const std::string& report,
                            std::string_view argument,
                            std::string_view port,
                            std::string_view memory) {
  const std::string marker = "Argument:          " + std::string(argument);
  const std::size_t begin = report.find(marker);
  if (begin == std::string::npos) {
    return false;
  }
  std::size_t end = report.find("Argument:          ", begin + marker.size());
  if (end == std::string::npos) {
    end = report.find("Generated By", begin + marker.size());
  }
  if (end == std::string::npos) {
    end = report.size();
  }
  const std::string_view block(report.data() + begin, end - begin);
  return block.find("Port:              " + std::string(port)) !=
             std::string_view::npos &&
         block.find("Memory:            " + std::string(memory)) !=
             std::string_view::npos;
}

bool arguments_in_order(const std::string& report) {
  constexpr std::array<std::string_view, 8> names = {
      "samples", "lut", "q_delta", "n_points", "n_samples",
      "hist_out", "catastrophe_out", "flops_out"};
  std::size_t position = 0;
  for (const std::string_view name : names) {
    position = report.find("Argument:          " + std::string(name), position);
    if (position == std::string::npos) {
      return false;
    }
    ++position;
  }
  return true;
}

void emit_bool(const char* key, bool value) {
  std::cout << key << '=' << (value ? "true" : "false") << '\n';
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 3) {
    std::cerr << "usage: u250_xclbin_material_probe XCLBIN XCLBINUTIL\n";
    return 64;
  }
  const std::filesystem::path artifact = argv[1];
  std::error_code size_error;
  const std::uintmax_t size = std::filesystem::file_size(artifact, size_error);
  const std::string digest = sha256_file(artifact);
  const ToolResult tool = run_xclbinutil(argv[2], argv[1]);
  const std::string& report = tool.output;

  std::array<char, 256> hostname{};
  const bool hostname_valid =
      gethostname(hostname.data(), hostname.size() - 1) == 0;
  const bool identity_valid = !size_error && size == kArtifactSize &&
      digest == kArtifactDigest && tool.exit_code == 0 &&
      contains(report, "Kernels:                krnl_san_scan") &&
      contains(report,
          "UUID (xclbin):          c50267ec-ae68-48a1-1559-3473f046689c") &&
      contains(report,
          "Platform VBNV:          xilinx_u250_gen3x16_xdma_4_1_202210_1") &&
      contains(report, "Generated by:           v++ (2025.1)") &&
      contains(report, "Requested Freq: 250 MHz") &&
      contains(report, "Achieved Freq:  135.2 MHz");
  const bool abi_valid = arguments_in_order(report) &&
      count_occurrences(report, "Argument:          ") == 8 &&
      argument_block_matches(report, "samples", "M_AXI_GMEM0", "bank1") &&
      argument_block_matches(report, "lut", "M_AXI_GMEM1", "bank1") &&
      argument_block_matches(report, "q_delta", "S_AXI_CONTROL",
                             "<not applicable>") &&
      argument_block_matches(report, "n_points", "S_AXI_CONTROL",
                             "<not applicable>") &&
      argument_block_matches(report, "n_samples", "S_AXI_CONTROL",
                             "<not applicable>") &&
      argument_block_matches(report, "hist_out", "M_AXI_GMEM1", "bank1") &&
      argument_block_matches(report, "catastrophe_out", "M_AXI_GMEM1",
                             "bank1") &&
      argument_block_matches(report, "flops_out", "M_AXI_GMEM1", "bank1");
  const bool host_valid = hostname_valid &&
      std::string(hostname.data()) == "dl380-proxmox";
  const bool valid = identity_valid && abi_valid && host_valid;

  std::cout << "schema=pireus.u250.xclbin-material-probe.v0\n";
  std::cout << "producer_language=C++\n";
  std::cout << "producer_role=MATERIAL_PARITY\n";
  std::cout << "semantic_authority_language=Sounio\n";
  std::cout << "parent_semantics_sha256=" << kParentSemantics << '\n';
  std::cout << "parent_freeze_sha256=" << kParentFreeze << '\n';
  std::cout << "artifact_name=krnl_san_scan.hw.xclbin\n";
  std::cout << "artifact_size_bytes=" << size << '\n';
  std::cout << "artifact_sha256=" << digest << '\n';
  std::cout << "xclbin_uuid=c50267ec-ae68-48a1-1559-3473f046689c\n";
  std::cout << "kernel=krnl_san_scan\n";
  std::cout << "platform=xilinx_u250_gen3x16_xdma_4_1_202210_1\n";
  std::cout << "vitis_version=2025.1\n";
  std::cout << "requested_frequency_mhz=250\n";
  std::cout << "achieved_frequency_tenths_mhz=1352\n";
  std::cout << "argument_count=8\n";
  std::cout << "argument_0=samples,M_AXI_GMEM0,bank1\n";
  std::cout << "argument_1=lut,M_AXI_GMEM1,bank1\n";
  std::cout << "argument_2=q_delta,S_AXI_CONTROL,none\n";
  std::cout << "argument_3=n_points,S_AXI_CONTROL,none\n";
  std::cout << "argument_4=n_samples,S_AXI_CONTROL,none\n";
  std::cout << "argument_5=hist_out,M_AXI_GMEM1,bank1\n";
  std::cout << "argument_6=catastrophe_out,M_AXI_GMEM1,bank1\n";
  std::cout << "argument_7=flops_out,M_AXI_GMEM1,bank1\n";
  std::cout << "interface_binding_count=8\n";
  std::cout << "material_bank_binding_count=5\n";
  std::cout << "toolchain_sha256=" << kToolchainDigest << '\n';
  std::cout << "hardware_sha256=" << kHardwareDigest << '\n';
  std::cout << "command_sha256=" << kCommandDigest << '\n';
  std::cout << "result_sha256=" << kResultDigest << '\n';
  emit_bool("bitstream_present", !size_error);
  emit_bool("bitstream_digest_present", !digest.empty());
  emit_bool("metadata_present", tool.exit_code == 0);
  emit_bool("probe_valid", valid);
  emit_bool("semantic_verdict_emitted", false);
  emit_bool("classification_requested", false);
  emit_bool("kernel_execution_observed", false);
  emit_bool("kernel_correctness_present", false);
  emit_bool("performance_present", false);
  emit_bool("claim_ready", false);
  return valid ? 0 : 1;
}
