#!/usr/bin/env bash
# Sounio.lock file management library

set -euo pipefail

# Default lockfile name
LOCKFILE_NAME="Sounio.lock"

# Read lockfile and output entries
# Usage: lockfile_read "Sounio.lock"
lockfile_read() {
    local file="${1:-$LOCKFILE_NAME}"
    
    if [[ ! -f "$file" ]]; then
        return 1
    fi
    
    local current_pkg=""
    local name="" version="" source="" hash=""
    
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip empty lines and comments
        [[ -z "$line" ]] && continue
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        
        # Start of new package entry
        if [[ "$line" =~ ^\[\[package\]\] ]]; then
            # Output previous package if complete
            if [[ -n "$name" && -n "$version" ]]; then
                echo "${name}|${version}|${source}|${hash}"
            fi
            # Reset
            name=""; version=""; source=""; hash=""
            continue
        fi
        
        # Parse key = value
        if [[ "$line" =~ ^([a-zA-Z0-9_-]+)[[:space:]]*=[[:space:]]*\"(.+)\" ]]; then
            local key="${BASH_REMATCH[1]}"
            local value="${BASH_REMATCH[2]}"
            
            case "$key" in
                name) name="$value" ;;
                version) version="$value" ;;
                source) source="$value" ;;
                hash) hash="$value" ;;
            esac
        fi
    done < "$file"
    
    # Output last package
    if [[ -n "$name" && -n "$version" ]]; then
        echo "${name}|${version}|${source}|${hash}"
    fi
}

# Write lockfile from entries
# Usage: lockfile_write "Sounio.lock" "pkg1|1.0.0|registry|abc123" "pkg2|2.0.0|git:...|def456"
lockfile_write() {
    local file="$1"
    shift
    
    # Generate timestamp
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    {
        echo "# This file is automatically generated by sounio-pkg."
        echo "# Do not edit manually."
        echo "# Generated: ${timestamp}"
        echo ""
        
        for entry in "$@"; do
            IFS='|' read -r name version source hash <<< "$entry"
            
            echo "[[package]]"
            echo "name = \"${name}\""
            echo "version = \"${version}\""
            [[ -n "$source" ]] && echo "source = \"${source}\""
            [[ -n "$hash" ]] && echo "hash = \"${hash}\""
            echo ""
        done
    } > "$file"
}

# Get version for a package from lockfile
# Usage: lockfile_get_version "Sounio.lock" "package-name"
lockfile_get_version() {
    local file="$1"
    local pkg_name="$2"
    
    lockfile_read "$file" | while IFS='|' read -r name version source hash; do
        if [[ "$name" == "$pkg_name" ]]; then
            echo "$version"
            return 0
        fi
    done
}

# Get source for a package from lockfile
# Usage: lockfile_get_source "Sounio.lock" "package-name"
lockfile_get_source() {
    local file="$1"
    local pkg_name="$2"
    
    lockfile_read "$file" | while IFS='|' read -r name version source hash; do
        if [[ "$name" == "$pkg_name" ]]; then
            echo "$source"
            return 0
        fi
    done
}

# Get hash for a package from lockfile
# Usage: lockfile_get_hash "Sounio.lock" "package-name"
lockfile_get_hash() {
    local file="$1"
    local pkg_name="$2"
    
    lockfile_read "$file" | while IFS='|' read -r name version source hash; do
        if [[ "$name" == "$pkg_name" ]]; then
            echo "$hash"
            return 0
        fi
    done
}

# Check if lockfile exists
# Usage: lockfile_exists "Sounio.lock"
lockfile_exists() {
    local file="${1:-$LOCKFILE_NAME}"
    [[ -f "$file" ]]
}

# Check if lockfile is fresh (newer than manifest)
# Usage: lockfile_is_fresh "Sounio.toml" "Sounio.lock"
lockfile_is_fresh() {
    local manifest="$1"
    local lockfile="${2:-$LOCKFILE_NAME}"
    
    # Lockfile must exist
    if [[ ! -f "$lockfile" ]]; then
        return 1
    fi
    
    # Manifest must exist
    if [[ ! -f "$manifest" ]]; then
        return 0  # No manifest means lockfile is "fresh"
    fi
    
    # Check if lockfile is newer than manifest
    if [[ "$lockfile" -nt "$manifest" ]]; then
        return 0
    fi
    
    return 1
}

# Add or update a package in the lockfile
# Usage: lockfile_update "Sounio.lock" "package-name" "1.0.0" "registry" "abc123"
lockfile_update() {
    local file="$1"
    local pkg_name="$2"
    local pkg_version="$3"
    local pkg_source="${4:-}"
    local pkg_hash="${5:-}"
    
    local entries=()
    local found=0
    
    # Read existing entries
    if lockfile_exists "$file"; then
        while IFS= read -r line; do
            IFS='|' read -r name version source hash <<< "$line"
            
            if [[ "$name" == "$pkg_name" ]]; then
                # Update this entry
                entries+=("${pkg_name}|${pkg_version}|${pkg_source}|${pkg_hash}")
                found=1
            else
                entries+=("${name}|${version}|${source}|${hash}")
            fi
        done < <(lockfile_read "$file")
    fi
    
    # Add new entry if not found
    if [[ $found -eq 0 ]]; then
        entries+=("${pkg_name}|${pkg_version}|${pkg_source}|${pkg_hash}")
    fi
    
    # Write back
    lockfile_write "$file" "${entries[@]}"
}

# Remove a package from the lockfile
# Usage: lockfile_remove "Sounio.lock" "package-name"
lockfile_remove() {
    local file="$1"
    local pkg_name="$2"
    
    local entries=()
    
    # Read existing entries, skipping the one to remove
    while IFS= read -r line; do
        IFS='|' read -r name version source hash <<< "$line"
        
        if [[ "$name" != "$pkg_name" ]]; then
            entries+=("${name}|${version}|${source}|${hash}")
        fi
    done < <(lockfile_read "$file")
    
    # Write back
    lockfile_write "$file" "${entries[@]}"
}

# List all packages in lockfile
# Usage: lockfile_list "Sounio.lock"
lockfile_list() {
    local file="${1:-$LOCKFILE_NAME}"
    
    lockfile_read "$file" | while IFS='|' read -r name version source hash; do
        echo "$name"
    done
}

# Check if a package exists in lockfile
# Usage: lockfile_has_package "Sounio.lock" "package-name"
lockfile_has_package() {
    local file="$1"
    local pkg_name="$2"
    
    lockfile_list "$file" | grep -qx "$pkg_name"
}
