#!/usr/bin/env bash
#
# Lockfile management for Sounio package manager
# Handles Sounio.lock file format
#

set -euo pipefail

readonly LOCKFILE_VERSION="1"

# Read a lockfile and output as structured data
# Usage: lockfile_read "Sounio.lock"
# Output format: package.name, package.version, package.source, etc.
lockfile_read() {
    local file="$1"

    [[ ! -f "$file" ]] && return 1

    local current_pkg=""
    local in_package=false

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Skip empty lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue

        # Trim leading whitespace
        line="${line#"${line%%[![:space:]]*}"}"

        # Start of package entry
        if [[ "$line" == "[[package]]" ]]; then
            in_package=true
            current_pkg=""
            continue
        fi

        # Parse key-value pairs within package
        if $in_package && [[ "$line" =~ ^([a-zA-Z0-9_-]+)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
            local key="${BASH_REMATCH[1]}"
            local value="${BASH_REMATCH[2]}"

            # Remove inline comments
            value="${value%%#*}"
            value="${value%"${value##*[![:space:]]}"}"

            # Unquote value
            if [[ "$value" =~ ^\"(.*)\"$ ]]; then
                value="${BASH_REMATCH[1]}"
            elif [[ "$value" =~ ^\'(.*)\'$ ]]; then
                value="${BASH_REMATCH[1]}"
            fi

            printf 'package.%s.%s=%s\n' "$current_pkg" "$key" "$value"

            # Track package name for grouping
            if [[ "$key" == "name" ]]; then
                current_pkg="$value"
                # Update previous lines with correct package name
            fi
        fi
    done < "$file"

    # Second pass: fix up package names
    # (In practice, we'd parse more carefully, but this is a simple implementation)
}

# Write lockfile entries to a file
# Usage: lockfile_write "Sounio.lock" "entries"
# Entries format: "name version source hash [checksum]"
lockfile_write() {
    local file="$1"
    shift

    {
        printf '# This file is automatically generated by sounio-pkg.\n'
        printf '# It is not intended for manual editing.\n'
        printf 'version = "%s"\n' "$LOCKFILE_VERSION"
        printf '\n'

        for entry in "$@"; do
            local name version source hash checksum
            read -r name version source hash checksum <<< "$entry"

            printf '[[package]]\n'
            printf 'name = "%s"\n' "$name"
            printf 'version = "%s"\n' "$version"
            printf 'source = "%s"\n' "$source"
            [[ -n "$hash" ]] && printf 'hash = "%s"\n' "$hash"
            [[ -n "$checksum" ]] && printf 'checksum = "%s"\n' "$checksum"
            printf '\n'
        done
    } > "$file"
}

# Add or update a package entry in the lockfile
# Usage: lockfile_add_entry "Sounio.lock" "name" "version" "source" "hash" "checksum"
lockfile_add_entry() {
    local file="$1"
    local name="$2"
    local version="$3"
    local source="$4"
    local hash="${5:-}"
    local checksum="${6:-}"

    local entries=()

    # Read existing entries
    if [[ -f "$file" ]]; then
        while IFS='=' read -r key value; do
            [[ "$key" == package.* ]] || continue
            local pkg_name="${key#package.}"
            pkg_name="${pkg_name%%.*}"
            local field="${key##*.}"
            
            # Skip the one we're updating
            [[ "$pkg_name" == "$name" ]] && continue
            
            # Collect existing entries
            # (This is simplified - full implementation would track all fields)
        done < <(lockfile_read "$file" 2>/dev/null || true)
    fi

    # Add new entry
    entries+=("$name $version $source $hash $checksum")

    # Write back
    lockfile_write "$file" "${entries[@]}"
}

# Get package version from lockfile
# Usage: lockfile_get_version "Sounio.lock" "package_name"
lockfile_get_version() {
    local file="$1"
    local pkg_name="$2"

    [[ ! -f "$file" ]] && return 1

    local in_package=false
    local current_name=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Start of package
        if [[ "$line" == "[[package]]" ]]; then
            in_package=true
            current_name=""
            continue
        fi

        # Parse within package
        if $in_package; then
            if [[ "$line" =~ ^name[[:space:]]*=[[:space:]]*\"(.+)\"$ ]]; then
                current_name="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ ^version[[:space:]]*=[[:space:]]*\"(.+)\"$ ]]; then
                if [[ "$current_name" == "$pkg_name" ]]; then
                    printf '%s\n' "${BASH_REMATCH[1]}"
                    return 0
                fi
            fi
        fi
    done < "$file"

    return 1
}

# Get package source from lockfile
# Usage: lockfile_get_source "Sounio.lock" "package_name"
lockfile_get_source() {
    local file="$1"
    local pkg_name="$2"

    [[ ! -f "$file" ]] && return 1

    local in_package=false
    local current_name=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" == "[[package]]" ]]; then
            in_package=true
            current_name=""
            continue
        fi

        if $in_package; then
            if [[ "$line" =~ ^name[[:space:]]*=[[:space:]]*\"(.+)\"$ ]]; then
                current_name="${BASH_REMATCH[1]}"
            elif [[ "$line" =~ ^source[[:space:]]*=[[:space:]]*\"(.+)\"$ ]]; then
                if [[ "$current_name" == "$pkg_name" ]]; then
                    printf '%s\n' "${BASH_REMATCH[1]}"
                    return 0
                fi
            fi
        fi
    done < "$file"

    return 1
}

# Check if lockfile is fresh relative to manifest
# Usage: lockfile_is_fresh "Sounio.toml" "Sounio.lock"
lockfile_is_fresh() {
    local manifest="$1"
    local lockfile="$2"

    [[ ! -f "$manifest" ]] && return 1
    [[ ! -f "$lockfile" ]] && return 1

    # Check if manifest is newer than lockfile
    if [[ "$manifest" -nt "$lockfile" ]]; then
        return 1
    fi

    # TODO: Check if all manifest dependencies are in lockfile
    # and if versions still satisfy constraints

    return 0
}

# Remove a package from the lockfile
# Usage: lockfile_remove "Sounio.lock" "package_name"
lockfile_remove() {
    local file="$1"
    local remove_name="$2"

    [[ ! -f "$file" ]] && return 1

    local temp_file="${file}.tmp"
    local in_package=false
    local skip_package=false
    local current_name=""
    local buffer=""

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Detect start of package
        if [[ "$line" == "[[package]]" ]]; then
            # Write previous package if not skipping
            if [[ -n "$buffer" && "$skip_package" == false ]]; then
                printf '%s\n' "$buffer" >> "$temp_file"
            fi
            in_package=true
            skip_package=false
            current_name=""
            buffer="$line"
            continue
        fi

        if $in_package; then
            buffer="$buffer
$line"

            if [[ "$line" =~ ^name[[:space:]]*=[[:space:]]*\"(.+)\"$ ]]; then
                current_name="${BASH_REMATCH[1]}"
                if [[ "$current_name" == "$remove_name" ]]; then
                    skip_package=true
                fi
            fi
        else
            # Outside of package, write directly
            printf '%s\n' "$line" >> "$temp_file"
        fi
    done < "$file"

    # Write last package
    if [[ -n "$buffer" && "$skip_package" == false ]]; then
        printf '%s\n' "$buffer" >> "$temp_file"
    fi

    mv "$temp_file" "$file"
}

# List all packages in lockfile
# Usage: lockfile_list "Sounio.lock"
lockfile_list() {
    local file="$1"

    [[ ! -f "$file" ]] && return 1

    grep -E '^name\s*=' "$file" | sed 's/^name\s*=\s*"\(.*\)"/\1/'
}

# Example usage:
#   lockfile_write "Sounio.lock" "lib1 1.0.0 registry sha256:abc" "lib2 2.0.0 git sha256:def"
#   version=$(lockfile_get_version "Sounio.lock" "lib1")
#   lockfile_is_fresh "Sounio.toml" "Sounio.lock" || echo "Need to update"
