#!/usr/bin/env python3
"""
Extract main() functions from stdlib modules to example files.

This script:
1. Extracts main() and helper functions from stdlib modules
2. Moves them to examples/ mirroring stdlib structure
3. Moves explicit test files to tests/stdlib/
4. Removes main() from original files (keeping library code)

Run analyze_stdlib_mains.sh first to generate classification files.
"""

import os
import sys
import re
import shutil
from pathlib import Path
from typing import Tuple, Optional

# Configuration
STDLIB_ROOT = Path("stdlib")
REPO_ROOT = Path(".")
OUTPUT_DIR = Path("/tmp/stdlib_main_analysis")

# Classification files generated by analyze_stdlib_mains.sh
EXPLICIT_TESTS_FILE = OUTPUT_DIR / "explicit_tests.txt"
NAMED_EXAMPLES_FILE = OUTPUT_DIR / "named_examples.txt"
MODULE_DEMOS_FILE = OUTPUT_DIR / "module_demos.txt"


def read_classification_file(path: Path) -> list[str]:
    """Read a classification file and return list of file paths."""
    if not path.exists():
        return []
    with open(path) as f:
        return [line.strip() for line in f if line.strip()]


def extract_main_function(content: str) -> Tuple[str, Optional[str], int]:
    """
    Extract main() function from source.

    Returns:
        (library_content_without_main, main_content, main_start_line)
    """
    lines = content.split('\n')

    # Find main() function start (must be at start of line with fn main()
    main_start = None
    for i, line in enumerate(lines):
        if re.match(r'^fn main\(', line):
            main_start = i
            break

    if main_start is None:
        return content, None, -1

    # Find preceding comment block and separator
    # Look for lines like "// ====" or "// ----" or just "//"
    separator_start = main_start
    found_separator = False

    for i in range(main_start - 1, max(-1, main_start - 50), -1):
        line = lines[i] if i >= 0 else ""
        stripped = line.strip()

        # Check for separator pattern (==== or ---- comments)
        if re.match(r'^//\s*[=\-]{4,}', stripped):
            separator_start = i
            found_separator = True
            break
        # Also accept just comment lines that seem to introduce main
        elif stripped.startswith('//') and ('main' in stripped.lower() or
                                           'test' in stripped.lower() or
                                           'demo' in stripped.lower() or
                                           'example' in stripped.lower()):
            # Found a relevant comment, keep looking for separator
            separator_start = i

    # If no separator found, still extract from some comment
    if not found_separator:
        # Just use a few lines before main
        separator_start = max(0, main_start - 3)

    # Extract the library code (everything before separator)
    library_lines = lines[:separator_start]
    # Remove trailing empty lines
    while library_lines and not library_lines[-1].strip():
        library_lines.pop()

    library_content = '\n'.join(library_lines)
    if library_content:
        library_content += '\n'

    # Extract main and everything after it
    main_content = '\n'.join(lines[separator_start:])

    return library_content, main_content, separator_start


def create_demo_header(original_module_path: str) -> str:
    """Create header for demo file with module reference."""
    # Extract module path: stdlib/graph/curvature.sio -> graph::curvature
    parts = Path(original_module_path).relative_to(STDLIB_ROOT).parts

    # Remove .sio extension from last part
    module_parts = []
    for part in parts:
        if part.endswith('.sio'):
            module_parts.append(part[:-4])
        else:
            module_parts.append(part)

    module_path = "::".join(module_parts)
    rel_path = '/'.join(parts)

    header = f"""// Demo for stdlib/{rel_path}
//
// This file demonstrates usage of the {module_path} module.
// Module source: stdlib/{rel_path}

"""
    return header


def create_directories(path: Path) -> None:
    """Create directory structure for a file path."""
    path.parent.mkdir(parents=True, exist_ok=True)


def process_explicit_test(src_path: str, dry_run: bool = False) -> bool:
    """Move explicit test file to tests/stdlib/"""
    src = Path(src_path)

    # Preserve relative structure under tests/stdlib/
    rel_path = src.relative_to(STDLIB_ROOT)
    dst = REPO_ROOT / "tests" / "stdlib" / rel_path

    if not dry_run:
        create_directories(dst)
        shutil.copy2(src, dst)

    status = "[DRY]" if dry_run else "[MOVE]"
    print(f"{status} {src} -> {dst}")
    return True


def process_named_example(src_path: str, dry_run: bool = False) -> bool:
    """Move named example file to examples/"""
    src = Path(src_path)

    # Preserve relative structure under examples/
    rel_path = src.relative_to(STDLIB_ROOT)
    dst = REPO_ROOT / "examples" / rel_path

    if not dry_run:
        create_directories(dst)
        shutil.copy2(src, dst)

    status = "[DRY]" if dry_run else "[MOVE]"
    print(f"{status} {src} -> {dst}")
    return True


def process_module_demo(src_path: str, dry_run: bool = False) -> bool:
    """Extract main() from module to demo file, keep library in stdlib."""
    src = Path(src_path)

    if not src.exists():
        print(f"[ERROR] File not found: {src}")
        return False

    # Read the original file
    try:
        content = src.read_text()
    except Exception as e:
        print(f"[ERROR] Failed to read {src}: {e}")
        return False

    # Extract main() and library code
    lib_content, main_content, line_no = extract_main_function(content)

    if main_content is None:
        print(f"[WARNING] No main() found in {src}")
        return False

    # Create demo file path
    rel_path = src.relative_to(STDLIB_ROOT)
    stem = rel_path.stem  # filename without .sio
    parent = rel_path.parent
    demo_name = f"{stem}_demo.sio"
    dst = REPO_ROOT / "examples" / parent / demo_name

    if not dry_run:
        # Write library file (removing main)
        src.write_text(lib_content)

        # Write demo file (with header + main)
        create_directories(dst)
        demo_header = create_demo_header(src_path)
        dst.write_text(demo_header + main_content)

    status = "[DRY]" if dry_run else "[EXTRACT]"
    print(f"{status} {src} (main removed) -> {dst}")
    return True


def main():
    # Check if classification files exist
    if not EXPLICIT_TESTS_FILE.exists():
        print("ERROR: Classification files not found!")
        print(f"Run this first: bash scripts/analyze_stdlib_mains.sh")
        return 1

    # Parse command line arguments
    dry_run = "--dry-run" in sys.argv or "-n" in sys.argv
    category = None
    limit = None
    offset = 0

    # Parse category argument
    if "--category" in sys.argv:
        idx = sys.argv.index("--category")
        if idx + 1 < len(sys.argv):
            category = sys.argv[idx + 1]

    if "--limit" in sys.argv:
        idx = sys.argv.index("--limit")
        if idx + 1 < len(sys.argv):
            limit = int(sys.argv[idx + 1])

    if "--offset" in sys.argv:
        idx = sys.argv.index("--offset")
        if idx + 1 < len(sys.argv):
            offset = int(sys.argv[idx + 1])

    # Change to repo root
    os.chdir(REPO_ROOT)

    # Read classification files
    explicit_tests = read_classification_file(EXPLICIT_TESTS_FILE)
    named_examples = read_classification_file(NAMED_EXAMPLES_FILE)
    module_demos = read_classification_file(MODULE_DEMOS_FILE)

    mode = "DRY RUN" if dry_run else "EXECUTE"
    print(f"\n{'='*60}")
    print(f"Extract Stdlib main() Functions - {mode}")
    print(f"{'='*60}\n")

    # Process based on category
    if category is None or category == "explicit_tests":
        print("Explicit Test Files (test_*.sio):")
        print(f"  Found: {len(explicit_tests)} files")
        for src in explicit_tests:
            process_explicit_test(src, dry_run=dry_run)
        print()

    if category is None or category == "named_examples":
        print("Named Example Files (*_example.sio):")
        print(f"  Found: {len(named_examples)} files")
        for src in named_examples:
            process_named_example(src, dry_run=dry_run)
        print()

    if category is None or category == "module_demos":
        print("Module Demo Files (everything else with main):")
        files_to_process = module_demos

        if limit:
            files_to_process = files_to_process[offset:offset+limit]
        elif offset > 0:
            files_to_process = files_to_process[offset:]

        print(f"  Found: {len(module_demos)} total files")
        if limit:
            print(f"  Processing: {offset} to {offset+len(files_to_process)} (limit {limit})")
        elif offset > 0:
            print(f"  Processing: {offset} to end (offset {offset})")

        for src in files_to_process:
            process_module_demo(src, dry_run=dry_run)
        print()

    if dry_run:
        print("✓ DRY RUN COMPLETE - No files were modified")
        print("To execute, run without --dry-run flag")
    else:
        print("✓ TRANSFORMATION COMPLETE")

    return 0


if __name__ == "__main__":
    sys.exit(main())
