#!/usr/bin/env python3
"""Extract a 16-channel 80-sample window from EEGMMIDB S001R01 and emit
a Sounio init_eeg_data() function.

Data source: PhysioNet EEGMMIDB 1.0.0, subject S001, run R01 (baseline
eyes-open, 60.75s at 160 Hz, 64 channels). We use the first 16 channels
(Fc5, Fc3, Fc1, Fcz, Fc2, Fc4, Fc6, C5, C3, C1, Cz, C2, C4, C6, Cp5, Cp3)
which cover the fronto-central and central cortical strips.

Scalar prediction task: INPUT[t] = mean of channels 0-7, TARGET[t] = mean
of channels 8-15 shifted by +1 sample (one-step-ahead). Both normalized
to [-1, 1] by training-window max-abs scale.

Window [2000..2081] at 160 Hz is from ~12.5s into the recording, past
any startup transients.

Usage:
    python3 scripts/extract_eeg_for_sounio.py > /tmp/eeg_init.sio
"""
import pyedflib
import numpy as np
import sys

EDF_PATH = "data/eegmmidb/S001R01.edf"
WINDOW_START = 2000
WINDOW_LEN = 81           # need 81 samples to get 80 (INPUT, TARGET) pairs


def main():
    f = pyedflib.EdfReader(EDF_PATH)
    sigs = np.stack([f.readSignal(i) for i in range(16)])
    f.close()
    window = sigs[:, WINDOW_START:WINDOW_START + WINDOW_LEN]

    left = window[0:8].mean(axis=0)
    right = window[8:16].mean(axis=0)

    inp_raw = left[:80]
    tgt_raw = right[1:81]

    scale_i = np.abs(inp_raw[:64]).max() + 1e-6
    scale_t = np.abs(tgt_raw[:64]).max() + 1e-6
    input_norm = inp_raw / scale_i
    target_norm = tgt_raw / scale_t

    # Sanity stats on stderr
    sys.stderr.write(f"input range: [{input_norm.min():.3f}, {input_norm.max():.3f}]\n")
    sys.stderr.write(f"target range: [{target_norm.min():.3f}, {target_norm.max():.3f}]\n")
    sys.stderr.write(f"corr(left, right shifted): {np.corrcoef(inp_raw, tgt_raw)[0,1]:.3f}\n")

    out = sys.stdout
    out.write("// Generated by scripts/extract_eeg_for_sounio.py from\n")
    out.write("// data/eegmmidb/S001R01.edf, samples [2000..2080].\n")
    out.write("fn init_eeg_data() with Mut {\n")
    for t, v in enumerate(input_norm):
        out.write(f"    INPUT[{t}] = {v:.6f}\n")
    for t, v in enumerate(target_norm):
        out.write(f"    TARGET[{t}] = {v:.6f}\n")
    out.write("}\n")


if __name__ == "__main__":
    main()
