#!/usr/bin/env python3
"""Extract 16-channel sedenion EEG data from EEGMMIDB S001R01.
Emits a Sounio init_eeg_16ch() function with per-index assignments.

Task: Predict CH0[t+1] given all 16 channels at time t (sedenion input).
Each channel is independently normalized to [-1,1] by training-window max-abs.
Window [2000..2080], 64 train + 16 test samples.

Usage:
    python3 scripts/extract_eeg_16ch_for_sounio.py
"""
import pyedflib
import numpy as np
import sys

EDF_PATH = "data/eegmmidb/S001R01.edf"
WINDOW_START = 2000
WINDOW_LEN = 81  # 81 samples → 80 (input, target) pairs

CH_NAMES = [
    "Fc5","Fc3","Fc1","Fcz","Fc2","Fc4","Fc6","C5",
    "C3","C1","Cz","C2","C4","C6","Cp5","Cp3"
]

def main():
    f = pyedflib.EdfReader(EDF_PATH)
    sigs = np.stack([f.readSignal(i) for i in range(16)])
    f.close()

    window = sigs[:, WINDOW_START:WINDOW_START + WINDOW_LEN]  # (16, 81)
    data = window[:, :80]   # (16, 80) — input samples
    target_raw = window[0, 1:81]  # CH0 shifted +1 = TARGET

    # normalize each channel independently by training-window max-abs
    scales = np.abs(data[:, :64]).max(axis=1) + 1e-6
    normed = data / scales[:, None]
    target_scale = np.abs(target_raw[:64]).max() + 1e-6
    target_normed = target_raw / target_scale

    # diagnostics to stderr
    for k in range(16):
        sys.stderr.write(f"CH{k:02d} ({CH_NAMES[k]}): scale={scales[k]:.4f}  "
                         f"range=[{normed[k].min():.3f},{normed[k].max():.3f}]\n")
    corr = np.corrcoef(normed[0, :64], target_normed[:64])[0, 1]
    sys.stderr.write(f"corr(CH0_in, CH0_target_train): {corr:.3f}\n")
    cross_corrs = [np.corrcoef(normed[k, :64], target_normed[:64])[0,1] for k in range(16)]
    sys.stderr.write(f"mean cross-ch corr with target: {np.mean(cross_corrs):.3f}  "
                     f"max: {max(cross_corrs):.3f} (ch {np.argmax(cross_corrs)})\n")

    out = sys.stdout
    out.write("// Generated by scripts/extract_eeg_16ch_for_sounio.py\n")
    out.write("// data/eegmmidb/S001R01.edf  window [2000..2080]\n")
    out.write("// 16 fronto-central channels; TARGET = CH0 shifted +1 sample.\n")
    out.write("fn init_eeg_16ch() with Mut {\n")
    for k in range(16):
        out.write(f"    // CH{k} ({CH_NAMES[k]})\n")
        for t in range(80):
            out.write(f"    CH{k}[{t}] = {normed[k, t]:.6f}\n")
    out.write("    // TARGET = CH0 one-step ahead\n")
    for t in range(80):
        out.write(f"    TARGET[{t}] = {target_normed[t]:.6f}\n")
    out.write("}\n")

if __name__ == "__main__":
    main()
