#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUNDLE_REL_DIR="stdlib/data/data/ontology/bundles"
OUT_DIR="$ROOT_DIR/stdlib/ontology/generated"
TYPED_DIR="$ROOT_DIR/stdlib/ontology/typed"
RUN_PASS_DIR="$ROOT_DIR/tests/run-pass"
COMPILE_FAIL_DIR="$ROOT_DIR/tests/compile-fail"
IMPORTER="${SOUNIO_DONTOLOGY_IMPORTER:-/tmp/sounio-dontology-ffi-importer}"
MANIFEST="$OUT_DIR/MANIFEST.tsv"

mkdir -p "$OUT_DIR"
mkdir -p "$TYPED_DIR"
mkdir -p "$RUN_PASS_DIR" "$COMPILE_FAIL_DIR"

"$ROOT_DIR/scripts/ontology/build_dontology_ffi_importer.sh" "$IMPORTER" >/dev/null

{
    printf 'bundle\tstub\tontology\tclass_count\tclass_limit\tconst_count\tdisjoint_count\tdisjoint_limit\tsurface\tpositive_witness\tnegative_witnesses\ttyped_bridge\ttyped_witness\tupstream_release\tfetched_at\tsource_uri\tsource_sha256\n'
} >"$MANIFEST"

# Provenance of the source slice a bundle was built from. Emitted into the
# manifest so the generated artifacts carry where they came from, not just what
# they contain.
#
# UNKNOWN is written deliberately and is not a placeholder to fill in later. The
# committed slices declare `version: "fixture-2026.03"` and nothing else -- no
# upstream release, no fetch time, no URI. Promoting a fixture version into
# `upstream_release` would state a provenance that does not exist, which is the
# failure this column was added to prevent. The sha256 is real: it is the slice
# on disk, so a drifted slice shows up as a changed manifest.
slice_provenance() {
    local stem="$1"
    local slice="$ROOT_DIR/stdlib/data/data/ontology/source/${stem}_slice.json"
    local rel="upstream_release" fetched="fetched_at" uri="source_uri"
    local up="UNKNOWN" at="UNKNOWN" src="UNKNOWN" sha="UNKNOWN"
    if [[ -f "$slice" ]]; then
        sha="$(sha256sum "$slice" | awk '{print $1}')"
        up="$(python3 -c "import json,sys;d=json.load(open(sys.argv[1]));print(d.get('$rel') or 'UNKNOWN')" "$slice" 2>/dev/null || printf 'UNKNOWN')"
        at="$(python3 -c "import json,sys;d=json.load(open(sys.argv[1]));print(d.get('$fetched') or 'UNKNOWN')" "$slice" 2>/dev/null || printf 'UNKNOWN')"
        src="$(python3 -c "import json,sys;d=json.load(open(sys.argv[1]));print(d.get('$uri') or 'UNKNOWN')" "$slice" 2>/dev/null || printf 'UNKNOWN')"
    fi
    printf '%s\t%s\t%s\t%s' "$up" "$at" "$src" "$sha"
}

extract_ontology_block() {
    local stub="$1"
    awk '/^ontology /,/^}/ { print }' "$stub"
}

first_subclass_pair() {
    local stub="$1"
    awk '
        /^[[:space:]]*class[[:space:]][A-Za-z0-9_]+[[:space:]]+subclass_of[[:space:]]/ {
            child = $2
            parent = $4
            sub(/,$/, "", parent)
            print child "\t" parent
            exit
        }
    ' "$stub"
}

first_const_pair() {
    local stub="$1"
    awk '
        /^const[[:space:]][A-Za-z0-9_]+_ID:[[:space:]]i64[[:space:]]=/ {
            name = $2
            sub(/:$/, "", name)
            value = $5
            print name "\t" value
            exit
        }
    ' "$stub"
}

write_positive_witness() {
    local stem="$1"
    local stub="$2"
    local out="$RUN_PASS_DIR/ontology_generated_${stem}_types.sio"
    local pair const_pair child parent const_name const_value label

    pair="$(first_subclass_pair "$stub")"
    if [[ -z "$pair" ]]; then
        echo "generated stub has no subclass pair for positive witness: $stub" >&2
        exit 1
    fi
    child="${pair%%$'\t'*}"
    parent="${pair#*$'\t'}"

    const_pair="$(first_const_pair "$stub")"
    if [[ -n "$const_pair" ]]; then
        const_name="${const_pair%%$'\t'*}"
        const_value="${const_pair#*$'\t'}"
    else
        const_name=""
        const_value=""
    fi
    label="ontology generated ${stem} types OK"

    {
        printf '//@ run-pass\n'
        printf '//@ expect-stdout: %s\n\n' "$label"
        printf '// Generated by scripts/ontology/generate_dontology_stubs.sh\n'
        printf '// The .dontology importer only ingests data; Sounio owns reasoning.\n\n'
        extract_ontology_block "$stub"
        printf '\n'
        grep '^const ' "$stub" || true
        printf '\n'
        printf 'fn make_%s_child() -> %s {\n' "$stem" "$child"
        printf '    0 as %s\n' "$child"
        printf '}\n\n'
        printf 'fn accept_%s_parent(x: %s) -> i32 {\n' "$stem" "$parent"
        printf '    1\n'
        printf '}\n\n'
        printf 'fn main() -> i32 {\n'
        printf '    let x: %s = make_%s_child()\n' "$child" "$stem"
        printf '    accept_%s_parent(x)\n' "$stem"
        if [[ -n "$const_name" ]]; then
            printf '    if %s == %s {\n' "$const_name" "$const_value"
            printf '        print("%s\\n")\n' "$label"
            printf '        return 0\n'
            printf '    }\n'
            printf '    1\n'
        else
            printf '    print("%s\\n")\n' "$label"
            printf '    0\n'
        fi
        printf '}\n'
    } >"$out"

    printf '%s' "tests/run-pass/ontology_generated_${stem}_types.sio"
}

first_sibling_triple() {
    local stub="$1"
    awk '
        /^[[:space:]]*class[[:space:]][A-Za-z0-9_]+[[:space:]]+subclass_of[[:space:]]/ {
            child = $2
            parent = $4
            sub(/,$/, "", parent)
            if (first_child[parent] == "") {
                first_child[parent] = child
            } else if (first_child[parent] != child) {
                print parent "\t" first_child[parent] "\t" child
                exit
            }
        }
    ' "$stub"
}

write_sibling_negative_witness() {
    local stem="$1"
    local stub="$2"
    local out="$COMPILE_FAIL_DIR/ontology_generated_${stem}_reject.sio"
    local triple parent target source

    triple="$(first_sibling_triple "$stub")"
    if [[ -z "$triple" ]]; then
        return 0
    fi
    parent="${triple%%$'\t'*}"
    triple="${triple#*$'\t'}"
    target="${triple%%$'\t'*}"
    source="${triple#*$'\t'}"

    {
        printf '//@ compile-fail\n'
        printf '//@ error-pattern: cannot prove ontology subsumption\n\n'
        printf '// Generated sibling negative witness for %s.\n' "$stem"
        printf '// %s and %s share parent %s, but neither proves subsumption to the other.\n\n' "$target" "$source" "$parent"
        extract_ontology_block "$stub"
        printf '\n'
        printf 'fn accept_%s_target(x: %s) -> i32 {\n' "$stem" "$target"
        printf '    1\n'
        printf '}\n\n'
        printf 'fn reject_%s_sibling(x: %s) -> i32 {\n' "$stem" "$source"
        printf '    accept_%s_target(x)\n' "$stem"
        printf '}\n'
    } >"$out"

    printf '%s' "tests/compile-fail/ontology_generated_${stem}_reject.sio"
}

first_disjoint_pair() {
    local stub="$1"
    awk '
        /^[[:space:]]*disjoint[[:space:]][A-Za-z0-9_]+,[[:space:]][A-Za-z0-9_]+/ {
            left = $2
            sub(/,$/, "", left)
            right = $3
            print left "\t" right
            exit
        }
    ' "$stub"
}

first_direct_child_of() {
    local stub="$1"
    local parent="$2"
    awk -v wanted="$parent" '
        /^[[:space:]]*class[[:space:]][A-Za-z0-9_]+[[:space:]]+subclass_of[[:space:]]/ {
            child = $2
            for (i = 4; i <= NF; i++) {
                p = $i
                sub(/,$/, "", p)
                if (p == wanted) {
                    print child
                    exit
                }
            }
        }
    ' "$stub"
}

write_disjoint_negative_witness() {
    local stem="$1"
    local stub="$2"
    local out="$COMPILE_FAIL_DIR/ontology_generated_${stem}_disjoint_reject.sio"
    local pair left right source

    pair="$(first_disjoint_pair "$stub")"
    if [[ -z "$pair" ]]; then
        return 0
    fi
    left="${pair%%$'\t'*}"
    right="${pair#*$'\t'}"
    source="$(first_direct_child_of "$stub" "$left")"
    if [[ -z "$source" ]]; then
        source="$left"
    fi

    {
        printf '//@ compile-fail\n'
        printf '//@ error-pattern: ontology classes are disjoint\n\n'
        printf '// Generated disjointness negative witness for %s.\n' "$stem"
        printf '// %s is rejected where disjoint class %s is required.\n\n' "$source" "$right"
        extract_ontology_block "$stub"
        printf '\n'
        printf 'fn accept_%s_disjoint_target(x: %s) -> i32 {\n' "$stem" "$right"
        printf '    1\n'
        printf '}\n\n'
        printf 'fn reject_%s_disjoint(x: %s) -> i32 {\n' "$stem" "$source"
        printf '    accept_%s_disjoint_target(x)\n' "$stem"
        printf '}\n'
    } >"$out"

    printf '%s' "tests/compile-fail/ontology_generated_${stem}_disjoint_reject.sio"
}

# Emit the runtime-model <-> generated-type bridge for one bundle. Mirrors the
# hand-written reference stdlib/ontology/typed/go.sio, but uses ID-based names
# (the importer has class ids, not human labels). For each class C with a
# C_ID constant: a C_iri() -> IRI constructor; for every class: iri_as_C(&IRI)
# and owl_class_as_C(&OWLClass) coercions. One generated bundle per compile
# unit (the compiler scopes ontology classes per block); import the bridge ONLY.
write_typed_bridge() {
    local stem="$1"
    local stub="$2"
    local out="$TYPED_DIR/$stem.sio"
    local ontology_name="$3"

    {
        printf '// Generated by scripts/ontology/generate_dontology_stubs.sh\n'
        printf '// Bridge: runtime ontology model (IRI/OWLClass) <-> generated %s types.\n' "$ontology_name"
        printf '// A runtime IRI tagged with a class id is re-presented as that class'"'"'s\n'
        printf '// compile-time nominal type, so the compiler enforces subclass subsumption.\n'
        printf '//\n'
        printf '// CONSTRAINT: one generated bundle per compile unit. The compiler scopes\n'
        printf '// ontology classes per `ontology {}` block, so importing this bridge AND\n'
        printf '// `generated::%s` directly (two copies of the block) breaks subsumption\n' "$stem"
        printf '// (E001). Import this bridge ONLY; it re-exports the types + _ID consts.\n\n'
        printf 'use ontology::model::{IRI, iri_new, OWLClass}\n'
        printf 'use ontology::generated::%s::*\n\n' "$stem"

        # Typed IRI constructors — one per class that has an _ID constant.
        printf '// Typed IRI constructors (one per class with a numeric id).\n'
        awk '
            /^const[[:space:]][A-Za-z0-9_]+_ID:[[:space:]]i64[[:space:]]=/ {
                name = $2; sub(/:$/, "", name)        # GO_0008150_ID
                cls = name; sub(/_ID$/, "", cls)      # GO_0008150
                printf "pub fn %s_iri() -> IRI { iri_new(%s) }\n", cls, name
            }
        ' "$stub"
        printf '\n'

        # IRI -> nominal and OWLClass -> nominal coercions — one per class.
        printf '// IRI / OWLClass -> nominal coercions (no runtime check; hands the\n'
        printf '// value to the compiler subsumption checker).\n'
        awk '
            /^[[:space:]]*class[[:space:]][A-Za-z0-9_]+/ {
                cls = $2
                printf "pub fn iri_as_%s(iri: &IRI) -> %s { iri.id as %s }\n", cls, cls, cls
                printf "pub fn owl_class_as_%s(c: &OWLClass) -> %s { c.iri.id as %s }\n", cls, cls, cls
            }
        ' "$stub"
    } >"$out"

    printf '%s' "stdlib/ontology/typed/$stem.sio"
}

# Emit a run-pass smoke test that drives the bridge: build a runtime IRI for a
# child class via its constructor, coerce it, and pass it to a function that
# requires the parent class (a subclass upcast the compiler must accept).
write_typed_bridge_witness() {
    local stem="$1"
    local stub="$2"
    local out="$RUN_PASS_DIR/ontology_typed_bridge_${stem}.sio"
    local pair child parent label

    pair="$(first_subclass_pair "$stub")"
    if [[ -z "$pair" ]]; then
        return 0
    fi
    child="${pair%%$'\t'*}"
    parent="${pair#*$'\t'}"
    label="ontology typed bridge ${stem} OK"

    {
        printf '//@ run-pass\n'
        printf '//@ expect-stdout: %s\n\n' "$label"
        printf '// Generated by scripts/ontology/generate_dontology_stubs.sh\n'
        printf '// Drives stdlib/ontology/typed/%s.sio: a runtime IRI for %s is coerced\n' "$stem" "$child"
        printf '// to its nominal type and upcast to its parent %s.\n' "$parent"
        printf '// Import the bridge ONLY for ontology types (see the one-bundle rule);\n'
        printf '// model.sio has no ontology block, so importing iri_new/owl_class_new is safe.\n'
        printf '// Build the IRI via iri_new (not a typed constructor) so the witness works\n'
        printf '// for bundles whose class ids are non-numeric and thus have no _ID const.\n\n'
        printf 'use ontology::model::{iri_new, owl_class_new}\n'
        printf 'use ontology::typed::%s::*\n\n' "$stem"
        printf 'fn accept_%s_parent(x: %s) -> i32 { 1 }\n\n' "$stem" "$parent"
        printf 'fn main() -> i32 with IO {\n'
        printf '    let iri = iri_new(0)\n'
        printf '    let c = iri_as_%s(&iri)\n' "$child"
        printf '    let r = accept_%s_parent(c)\n' "$stem"
        printf '    if r != 1 { return 1 }\n'
        printf '    let cls = owl_class_new(iri_new(0))\n'
        printf '    let c2 = owl_class_as_%s(&cls)\n' "$child"
        printf '    let r2 = accept_%s_parent(c2)\n' "$stem"
        printf '    if r2 != 1 { return 2 }\n'
        printf '    print("%s\\n")\n' "$label"
        printf '    0\n'
        printf '}\n'
    } >"$out"

    printf '%s' "tests/run-pass/ontology_typed_bridge_${stem}.sio"
}

generate_one() {
    local stem="$1"
    local ontology_name="$2"
    local bundle="$BUNDLE_REL_DIR/$stem.dontology"
    local out="$OUT_DIR/$stem.sio"
    local positive_witness sibling_negative disjoint_negative negative_witnesses

    if [[ ! -f "$ROOT_DIR/$bundle" ]]; then
        echo "missing ontology bundle: $bundle" >&2
        exit 1
    fi

    (cd "$ROOT_DIR" && "$IMPORTER" "$bundle" "$ontology_name" "$out")

    local class_count
    class_count="$(grep -c '^[[:space:]]*class ' "$out")"
    if [[ "$class_count" -gt 64 ]]; then
        echo "generated stub exceeds compiler ontology class limit: $out has $class_count classes" >&2
        exit 1
    fi

    local disjoint_count
    disjoint_count="$(grep -c '^[[:space:]]*disjoint ' "$out" || true)"
    if [[ "$disjoint_count" -gt 64 ]]; then
        echo "generated stub exceeds importer disjoint limit: $out has $disjoint_count disjoint pairs" >&2
        exit 1
    fi

    local const_count
    const_count="$(grep -c '^const ' "$out" || true)"

    local const_surface="numeric-constants"
    if [[ "$const_count" -eq 0 ]]; then
        const_surface="no-numeric-constants"
    fi

    local disjoint_surface="no-disjointness"
    if [[ "$disjoint_count" -gt 0 ]]; then
        disjoint_surface="disjoint"
    fi
    local surface="classes+subclass+$const_surface+$disjoint_surface"

    positive_witness="$(write_positive_witness "$stem" "$out")"
    sibling_negative="$(write_sibling_negative_witness "$stem" "$out")"
    disjoint_negative="$(write_disjoint_negative_witness "$stem" "$out")"

    # Typed runtime<->generated bridge. `go` is the hand-written reference
    # (human-readable labels in stdlib/ontology/typed/go.sio); the generator
    # owns the rest with id-based names.
    if [[ "$stem" != "go" ]]; then
        write_typed_bridge "$stem" "$out" "$ontology_name" >/dev/null
        write_typed_bridge_witness "$stem" "$out" >/dev/null
    fi

    negative_witnesses="-"
    if [[ -n "$sibling_negative" && -n "$disjoint_negative" ]]; then
        negative_witnesses="$sibling_negative,$disjoint_negative"
    elif [[ -n "$sibling_negative" ]]; then
        negative_witnesses="$sibling_negative"
    elif [[ -n "$disjoint_negative" ]]; then
        negative_witnesses="$disjoint_negative"
    fi

    local provenance
    provenance="$(slice_provenance "$stem")"

    printf '%s\t%s\t%s\t%s\t64\t%s\t%s\t64\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$bundle" \
        "stdlib/ontology/generated/$stem.sio" \
        "$ontology_name" \
        "$class_count" \
        "$const_count" \
        "$disjoint_count" \
        "$surface" \
        "$positive_witness" \
        "$negative_witnesses" \
        "stdlib/ontology/typed/$stem.sio" \
        "tests/run-pass/ontology_typed_bridge_$stem.sio" \
        "$provenance" >>"$MANIFEST"
}

generate_one alg ALGGenerated
generate_one chebi CHEBIGenerated
generate_one go GOGenerated
generate_one hpo HPOGenerated
generate_one loinc LOINCGenerated
generate_one part PARTGenerated
generate_one phys PHYSGenerated
generate_one qm QMGenerated
generate_one snomed SNOMEDGenerated

echo "Generated ontology stubs in $OUT_DIR"
