#!/usr/bin/env python3
import json, os, sys

bundles_dir = 'stdlib/data/data/ontology/bundles'
terms = []
for fname in sorted(os.listdir(bundles_dir)):
    if not fname.endswith('.dontology'): continue
    with open(os.path.join(bundles_dir, fname), 'rb') as f:
        data = f.read()
    payload = json.loads(data[12:])
    terms.extend(payload.get('terms', []))

N = len(terms)
print(f"Generating kernel for {N} terms...", file=sys.stderr)

def truncate(s, max_len=100):
    if len(s) <= max_len:
        return s
    return s[:max_len]

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

out = []

def w(line):
    out.append(line)

w("// ============================================================================")
w("// ONTOLOGY RESOLUTION KERNEL (embedded for native CLI)")
w("// ============================================================================")
w("")
w("struct OntologyTerm {")
w("    curie: string,")
w("    label: string,")
w("    definition: string,")
w("    parents: [string; 8],")
w("    parents_len: i64,")
w("    synonyms: [string; 8],")
w("    synonyms_len: i64,")
w("    source_layer: string,")
w("    iri: string,")
w("    mapping_confidence: f64,")
w("    provenance: string,")
w("}")
w("")
w("struct OntologyMapping {")
w("    subject_id: string,")
w("    predicate: string,")
w("    object_id: string,")
w("    confidence: f64,")
w("    justification: string,")
w("}")
w("")
w("struct OntologyMappingList {")
w("    items: [OntologyMapping; 16],")
w("    len: i64,")
w("}")
w("")
w("struct OntologyTermList {")
w("    items: [OntologyTerm; 16],")
w("    len: i64,")
w("}")
w("")

# TUI globals
w("var TUI_TERM_BUF: [i8; 64] = [0; 64]")
w("var TUI_TERM_SAVED: [i8; 64] = [0; 64]")
w("var TUI_INPUT_BUF: [i8; 8] = [0; 8]")
w("")

# Hash index globals
cap = max(N*2, 2048)
w(f"var HASH_KEYS: [i64; {cap}] = [0; {cap}]")
w(f"var HASH_VALS: [i32; {cap}] = [0; {cap}]")
w("var HASH_BUILT: i64 = 0")
w("")

# Batch buffer
w("var BATCH_BUF: [i8; 4096] = [0; 4096]")
w("")

w("fn ontology_term_empty() -> OntologyTerm {")
w("    OntologyTerm {")
w("        curie: \"\",")
w("        label: \"\",")
w("        definition: \"\",")
w("        parents: [\"\"; 8],")
w("        parents_len: 0,")
w("        synonyms: [\"\"; 8],")
w("        synonyms_len: 0,")
w("        source_layer: \"\",")
w("        iri: \"\",")
w("        mapping_confidence: 0.0,")
w("        provenance: \"\",")
w("    }")
w("}")
w("")
w("fn ontology_term_list_new() -> OntologyTermList {")
w("    OntologyTermList {")
w("        items: [ontology_term_empty(); 16],")
w("        len: 0,")
w("    }")
w("}")
w("")
w("fn ontology_term_list_push(lst: OntologyTermList, term: OntologyTerm) -> OntologyTermList {")
w("    var out = lst")
w("    if out.len < 16 {")
w("        out.items[out.len as usize] = term")
w("        out.len = out.len + 1")
w("    }")
w("    out")
w("}")
w("")
w("fn ontology_mapping_empty() -> OntologyMapping {")
w("    OntologyMapping {")
w("        subject_id: \"\",")
w("        predicate: \"\",")
w("        object_id: \"\",")
w("        confidence: 0.0,")
w("        justification: \"\",")
w("    }")
w("}")
w("")
w("fn ontology_mapping_list_new() -> OntologyMappingList {")
w("    OntologyMappingList {")
w("        items: [ontology_mapping_empty(); 16],")
w("        len: 0,")
w("    }")
w("}")
w("")
w("fn ontology_mapping_make(subject_id: string, predicate: string, object_id: string, confidence: f64, justification: string) -> OntologyMapping {")
w("    OntologyMapping {")
w("        subject_id: subject_id,")
w("        predicate: predicate,")
w("        object_id: object_id,")
w("        confidence: confidence,")
w("        justification: justification,")
w("    }")
w("}")
w("")
w("fn ontology_mapping_list_push(lst: OntologyMappingList, mapping: OntologyMapping) -> OntologyMappingList {")
w("    var out = lst")
w("    if out.len < 16 {")
w("        out.items[out.len as usize] = mapping")
w("        out.len = out.len + 1")
w("    }")
w("    out")
w("}")
w("")
w("fn ontology_store_make(curie: string, label: string, definition: string, iri: string, provenance: string) -> OntologyTerm {")
w("    OntologyTerm {")
w("        curie: curie,")
w("        label: label,")
w("        definition: definition,")
w("        parents: [\"\"; 8],")
w("        parents_len: 0,")
w("        synonyms: [\"\"; 8],")
w("        synonyms_len: 0,")
w("        source_layer: \"local\",")
w("        iri: iri,")
w("        mapping_confidence: 1.0,")
w("        provenance: provenance,")
w("    }")
w("}")
w("")
w("fn ontology_term_add_parent(term: OntologyTerm, parent: string) -> OntologyTerm {")
w("    var out = term")
w("    if out.parents_len < 8 {")
w("        out.parents[out.parents_len as usize] = parent")
w("        out.parents_len = out.parents_len + 1")
w("    }")
w("    out")
w("}")
w("")
w("fn ontology_term_add_synonym(term: OntologyTerm, synonym: string) -> OntologyTerm {")
w("    var out = term")
w("    if out.synonyms_len < 8 {")
w("        out.synonyms[out.synonyms_len as usize] = synonym")
w("        out.synonyms_len = out.synonyms_len + 1")
w("    }")
w("    out")
w("}")
w("")
w("fn ontology_term_found(term: OntologyTerm) -> bool {")
w("    str_len(term.curie) > 0")
w("}")
w("")
w("fn str_contains(haystack: string, needle: string) -> bool {")
w("    let hlen = str_len(haystack)")
w("    let nlen = str_len(needle)")
w("    if nlen == 0 { return true }")
w("    if nlen > hlen { return false }")
w("    var i: i64 = 0")
w("    while i <= hlen - nlen {")
w("        var j: i64 = 0")
w("        while j < nlen {")
w("            if haystack[(i + j) as usize] != needle[j as usize] {")
w("                break")
w("            }")
w("            j = j + 1")
w("        }")
w("        if j == nlen {")
w("            return true")
w("        }")
w("        i = i + 1")
w("    }")
w("    false")
w("}")
w("")

# store_get
w(f"fn ontology_store_get(idx: i32) -> OntologyTerm {{")
for i, t in enumerate(terms):
    defn = truncate(t.get('definition', ''), 100)
    w(f"    if idx == {i} {{")
    w(f"        var x = ontology_store_make(\"{esc(t['curie'])}\", \"{esc(t['label'])}\", \"{esc(defn)}\", \"{esc(t.get('iri', ''))}\", \"local\")")
    for p in t.get('parents', []):
        w(f"        x = ontology_term_add_parent(x, \"{esc(p)}\")")
    for s in t.get('synonyms', []):
        w(f"        x = ontology_term_add_synonym(x, \"{esc(s)}\")")
    w("        return x")
    w("    }")
w("    ontology_term_empty()")
w("}")
w("")

# Hash index
w("fn hash_curie(curie: string) -> i64 {")
w("    var h: i64 = 5381")
w("    var i: i64 = 0")
w("    while i < str_len(curie) {")
w("        h = ((h * 33) + curie[i as usize] as i64) & 0x7FFFFFFFFFFFFFFF")
w("        i = i + 1")
w("    }")
w("    h")
w("}")
w("")

w(f"fn ontology_index_build() {{")
w("    if HASH_BUILT != 0 { return }")
w(f"    let cap: i64 = {cap}")
w("    var idx: i64 = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        let h = hash_curie(term.curie)")
w("        var slot = h % cap")
w("        while slot < cap && HASH_KEYS[slot as usize] != 0 {")
w("            slot = slot + 1")
w("            if slot >= cap { slot = 0 }")
w("        }")
w("        HASH_KEYS[slot as usize] = h")
w("        HASH_VALS[slot as usize] = idx as i32")
w("        idx = idx + 1")
w("    }")
w("    HASH_BUILT = 1")
w("}")
w("")

w("fn ontology_store_resolve_fast(curie: string) -> OntologyTerm {")
w("    ontology_index_build()")
w(f"    let cap: i64 = {cap}")
w("    let h = hash_curie(curie)")
w("    var slot = h % cap")
w("    var guard: i64 = 0")
w("    while guard < cap {")
w("        if HASH_KEYS[slot as usize] == 0 { break }")
w("        if HASH_KEYS[slot as usize] == h {")
w("            let vi = HASH_VALS[slot as usize]")
w("            let term = ontology_store_get(vi)")
w("            if term.curie == curie { return term }")
w("        }")
w("        slot = slot + 1")
w("        if slot >= cap { slot = 0 }")
w("        guard = guard + 1")
w("    }")
w("    ontology_term_empty()")
w("}")
w("")

w("fn ontology_store_resolve_local(curie: string) -> OntologyTerm {")
w("    let fast = ontology_store_resolve_fast(curie)")
w("    if ontology_term_found(fast) { return fast }")
w(f"    var idx: i64 = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        if term.curie == curie {")
w("            return term")
w("        }")
w("        idx = idx + 1")
w("    }")
w("    ontology_term_empty()")
w("}")
w("")

w("fn ontology_store_search_local(query: string) -> OntologyTermList {")
w("    var out = ontology_term_list_new()")
w(f"    var idx: i64 = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        if str_contains(term.label, query) || str_contains(term.curie, query) {")
w("            out = ontology_term_list_push(out, term)")
w("        }")
w("        var sidx: i64 = 0")
w("        while sidx < term.synonyms_len {")
w("            if str_contains(term.synonyms[sidx as usize], query) {")
w("                out = ontology_term_list_push(out, term)")
w("            }")
w("            sidx = sidx + 1")
w("        }")
w("        idx = idx + 1")
w("    }")
w("    out")
w("}")
w("")

w("fn tui_score_term(term: OntologyTerm, query: string) -> i64 {")
w("    var score: i64 = 0")
w("    if str_contains(term.curie, query) { score = score + 100 }")
w("    if str_contains(term.label, query) { score = score + 50 }")
w("    var sidx: i64 = 0")
w("    while sidx < term.synonyms_len {")
w("        if str_contains(term.synonyms[sidx as usize], query) { score = score + 30 }")
w("        sidx = sidx + 1")
w("    }")
w("    score")
w("}")
w("")
w("fn ontology_store_fuzzy_local(query: string) -> OntologyTermList {")
w("    var scores: [i64; 16] = [0; 16]")
w("    var indices: [i32; 16] = [0; 16]")
w("    var filled: i64 = 0")
w(f"    var idx: i64 = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        let sc = tui_score_term(term, query)")
w("        if sc > 0 {")
w("            if filled < 16 {")
w("                scores[filled as usize] = sc")
w("                indices[filled as usize] = idx as i32")
w("                filled = filled + 1")
w("            } else {")
w("                var min_i: i64 = 0")
w("                var j: i64 = 1")
w("                while j < 16 {")
w("                    if scores[j as usize] < scores[min_i as usize] { min_i = j }")
w("                    j = j + 1")
w("                }")
w("                if sc > scores[min_i as usize] {")
w("                    scores[min_i as usize] = sc")
w("                    indices[min_i as usize] = idx as i32")
w("                }")
w("            }")
w("        }")
w("        idx = idx + 1")
w("    }")
w("    var swapped = true")
w("    while swapped {")
w("        swapped = false")
w("        var i: i64 = 0")
w("        while i < filled - 1 {")
w("            if scores[i as usize] < scores[(i+1) as usize] {")
w("                let ts = scores[i as usize]")
w("                let ti = indices[i as usize]")
w("                scores[i as usize] = scores[(i+1) as usize]")
w("                indices[i as usize] = indices[(i+1) as usize]")
w("                scores[(i+1) as usize] = ts")
w("                indices[(i+1) as usize] = ti")
w("                swapped = true")
w("            }")
w("            i = i + 1")
w("        }")
w("    }")
w("    var out = ontology_term_list_new()")
w("    var i: i64 = 0")
w("    while i < filled {")
w("        out = ontology_term_list_push(out, ontology_store_get(indices[i as usize]))")
w("        i = i + 1")
w("    }")
w("    out")
w("}")
w("")

w("fn ontology_store_map_local(source_curie: string, target_ontology: string) -> OntologyMappingList {")
w("    var out = ontology_mapping_list_new()")
w("    out")
w("}")
w("")

w("fn ontology_is_subclass(child: string, parent: string) -> bool {")
w("    var current = child")
w("    var depth = 0")
w("    while depth < 8 && str_len(current) > 0 {")
w("        if current == parent { return true }")
w("        let term = ontology_store_resolve_local(current)")
w("        if term.parents_len == 0 { break }")
w("        current = term.parents[0]")
w("        depth = depth + 1")
w("    }")
w("    false")
w("}")
w("")

w("fn ontology_graph_dot(curie: string) -> string {")
w("    var out = \"digraph {\\n\"")
w("    var visited: [string; 8] = [\"\"; 8]")
w("    var visited_len: i64 = 0")
w("    var current = curie")
w("    var depth = 0")
w("    while depth < 8 && str_len(current) > 0 {")
w("        let term = ontology_store_resolve_local(current)")
w("        if !ontology_term_found(term) { break }")
w("        var already = false")
w("        var v: i64 = 0")
w("        while v < visited_len {")
w("            if visited[v as usize] == current { already = true; break }")
w("            v = v + 1")
w("        }")
w("        if already { break }")
w("        if visited_len < 8 {")
w("            visited[visited_len as usize] = current")
w("            visited_len = visited_len + 1")
w("        }")
w("        var p: i64 = 0")
w("        while p < term.parents_len {")
w("            out = out + \"  \\\"\" + current + \"\\\" -> \\\"\" + term.parents[p as usize] + \"\\\";\\n\"")
w("            p = p + 1")
w("        }")
w("        if term.parents_len == 0 { break }")
w("        current = term.parents[0]")
w("        depth = depth + 1")
w("    }")
w("    out + \"}\\n\"")
w("}")
w("")

w("fn ontology_validate() -> i64 with IO, Mut {")
w("    var errors: i64 = 0")
w("    var warnings: i64 = 0")
w("    var idx: i64 = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        var p: i64 = 0")
w("        while p < term.parents_len {")
w("            let parent_term = ontology_store_resolve_local(term.parents[p as usize])")
w("            if !ontology_term_found(parent_term) {")
w("                println(\"ERROR: missing parent \" + term.parents[p as usize] + \" for \" + term.curie)")
w("                errors = errors + 1")
w("            }")
w("            p = p + 1")
w("        }")
w("        idx = idx + 1")
w("    }")
w("    idx = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        var visited: [string; 8] = [\"\"; 8]")
w("        var visited_len: i64 = 0")
w("        var current = term.curie")
w("        var depth = 0")
w("        var cycle = false")
w("        while depth < 8 && str_len(current) > 0 && !cycle {")
w("            var v: i64 = 0")
w("            while v < visited_len {")
w("                if visited[v as usize] == current {")
w("                    println(\"ERROR: cycle detected involving \" + term.curie)")
w("                    errors = errors + 1")
w("                    cycle = true")
w("                    break")
w("                }")
w("                v = v + 1")
w("            }")
w("            if cycle { break }")
w("            if visited_len < 8 {")
w("                visited[visited_len as usize] = current")
w("                visited_len = visited_len + 1")
w("            }")
w("            let t = ontology_store_resolve_local(current)")
w("            if t.parents_len == 0 { break }")
w("            current = t.parents[0]")
w("            depth = depth + 1")
w("        }")
w("        idx = idx + 1")
w("    }")
w("    print_int(errors as i32)")
w("    println(\" errors\")")
w("    print_int(warnings as i32)")
w("    println(\" warnings\")")
w("    if errors == 0 {")
w("        println(\"VALID\")")
w("    }")
w("    errors")
w("}")
w("")

w("fn ontology_count_terms(prefix: string) -> i64 {")
w("    var count: i64 = 0")
w(f"    var idx: i64 = 0")
w(f"    while idx < {N} {{")
w("        let term = ontology_store_get(idx as i32)")
w("        if str_len(prefix) == 0 || starts_with(term.curie, prefix) {")
w("            count = count + 1")
w("        }")
w("        idx = idx + 1")
w("    }")
w("    count")
w("}")
w("")

# TUI functions
w("fn tui_read_byte() -> i64 with IO {")
w("    let n = syscall6(0, 0, &TUI_INPUT_BUF, 1, 0, 0, 0)")
w("    if n > 0 {")
w("        let b = TUI_INPUT_BUF[0 as usize] as i64")
w("        if b < 0 { b + 256 } else { b }")
w("    } else {")
w("        -1")
w("    }")
w("}")
w("")
w("fn tui_save_termios() with IO, Mut {")
w("    syscall6(16, 0, 0x5401, &TUI_TERM_BUF, 0, 0, 0)")
w("    var i: i64 = 0")
w("    while i < 64 {")
w("        TUI_TERM_SAVED[i as usize] = TUI_TERM_BUF[i as usize]")
w("        i = i + 1")
w("    }")
w("}")
w("")
w("fn tui_set_raw_mode() with IO, Mut {")
w("    let old = TUI_TERM_BUF[12 as usize] as i64")
w("    TUI_TERM_BUF[12 as usize] = (old & 245) as i8")
w("    syscall6(16, 0, 0x5402, &TUI_TERM_BUF, 0, 0, 0)")
w("}")
w("")
w("fn tui_restore_termios() with IO, Mut {")
w("    var i: i64 = 0")
w("    while i < 64 {")
w("        TUI_TERM_BUF[i as usize] = TUI_TERM_SAVED[i as usize]")
w("        i = i + 1")
w("    }")
w("    syscall6(16, 0, 0x5402, &TUI_TERM_BUF, 0, 0, 0)")
w("}")
w("")
w("fn tui_clear() with IO {")
w("    print(\"\\x1b[2J\")")
w("    print(\"\\x1b[H\")")
w("}")
w("")
w("fn tui_hide_cursor() with IO {")
w("    print(\"\\x1b[?25l\")")
w("}")
w("")
w("fn tui_show_cursor() with IO {")
w("    print(\"\\x1b[?25h\")")
w("}")
w("")
w("fn tui_pad_label(label: string, width: i64) -> string {")
w("    var result = label")
w("    while str_len(result) < width {")
w("        result = result + \" \"")
w("    }")
w("    result")
w("}")
w("")
w("fn tui_menu_label(idx: i64) -> string {")
w("    if idx == 0 { return \"resolve\" }")
w("    if idx == 1 { return \"search\" }")
w("    if idx == 2 { return \"ancestors\" }")
w("    if idx == 3 { return \"is-subclass\" }")
w("    if idx == 4 { return \"map\" }")
w("    if idx == 5 { return \"list\" }")
w("    if idx == 6 { return \"count\" }")
w("    if idx == 7 { return \"validate\" }")
w("    if idx == 8 { return \"graph\" }")
w("    if idx == 9 { return \"fuzzy\" }")
w("    if idx == 10 { return \"batch\" }")
w("    if idx == 11 { return \"quit\" }")
w("    \"\"")
w("}")
w("")
w("fn tui_read_line() -> string with IO, Mut {")
w("    var result = \"\"")
w("    while true {")
w("        let c = tui_read_byte()")
w("        if c == 13 || c == 10 {")
w("            break")
w("        }")
w("        if c == 127 || c == 8 {")
w("            if str_len(result) > 0 {")
w("                result = str_slice(result, 0, str_len(result) - 1)")
w("                print(\"\\x08 \\x08\")")
w("            }")
w("        } else if c >= 32 && c <= 126 {")
w("            let chars = \" !\\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\"")
w("            let ch = str_slice(chars, c - 32, c - 31)")
w("            result = result + ch")
w("            print(ch)")
w("        }")
w("    }")
w("    result")
w("}")
w("")
w("fn tui_draw_menu(selected: i64) with IO, Mut {")
w("    println(\"\")")
w("    println(\"  SOUNIO ONTOLOGY BROWSER\")")
w("    println(\"  -----------------------\")")
w("    var i: i64 = 0")
w("    while i < 12 {")
w("        let label = tui_menu_label(i)")
w("        let padded = tui_pad_label(label, 18)")
w("        if i == selected {")
w("            println(\"\\x1b[7m > \" + padded + \" \\x1b[0m\")")
w("        } else {")
w("            println(\"   \" + padded)")
w("        }")
w("        i = i + 1")
w("    }")
w("    println(\"  -----------------------\")")
w("    println(\"  Up/Down: navigate | Enter: select | q: quit\")")
w("}")
w("")

for name, title, prompt in [
    ("resolve", "CURIE", "CURIE"),
    ("search", "Query", "Query"),
    ("ancestors", "CURIE", "CURIE"),
    ("is_subclass", "is-subclass", "Child CURIE"),
    ("map", "map", "Source CURIE"),
    ("list", "list", "Prefix"),
    ("count", "count", "Prefix"),
    ("graph", "graph", "CURIE"),
    ("fuzzy", "fuzzy", "Query"),
]:
    w(f"fn tui_action_{name}() with IO, Mut {{")
    if name == "is_subclass":
        w("    print(\"Child CURIE: \")")
        w("    let child = tui_read_line()")
        w("    print(\"Parent CURIE: \")")
        w("    let parent = tui_read_line()")
        w("    println(\"\")")
        w("    let result = ontology_is_subclass(child, parent)")
        w("    println(if result { \"yes\" } else { \"no\" })")
    elif name == "map":
        w("    print(\"Source CURIE: \")")
        w("    let source_curie = tui_read_line()")
        w("    print(\"Target ontology: \")")
        w("    let target_ontology = tui_read_line()")
        w("    println(\"\")")
        w("    let mappings = ontology_store_map_local(source_curie, target_ontology)")
        w("    var i: i64 = 0")
        w("    while i < mappings.len {")
        w("        let m = mappings.items[i as usize]")
        w("        println(m.subject_id + \" -> \" + m.object_id + \" | \" + m.predicate)")
        w("        i = i + 1")
        w("    }")
        w("    if mappings.len == 0 {")
        w("        println(\"no mappings found\")")
        w("    }")
    elif name == "graph":
        w("    print(\"CURIE: \")")
        w("    let curie = tui_read_line()")
        w("    println(\"\")")
        w("    println(ontology_graph_dot(curie))")
    elif name == "fuzzy":
        w("    print(\"Query: \")")
        w("    let query = tui_read_line()")
        w("    println(\"\")")
        w("    let results = ontology_store_fuzzy_local(query)")
        w("    var i: i64 = 0")
        w("    while i < results.len {")
        w("        let term = results.items[i as usize]")
        w("        println(term.curie + \" | \" + term.label)")
        w("        i = i + 1")
        w("    }")
        w("    if results.len == 0 {")
        w("        println(\"no matches\")")
        w("    }")
    elif name == "count":
        w("    print(\"Prefix: \")")
        w("    let prefix = tui_read_line()")
        w("    println(\"\")")
        w("    let count = ontology_count_terms(prefix)")
        w("    print_int(count as i32)")
        w("    if str_len(prefix) > 0 {")
        w("        println(\" terms matching \" + prefix)")
        w("    } else {")
        w("        println(\" total terms\")")
        w("    }")
    elif name == "list":
        w("    print(\"Prefix: \")")
        w("    let prefix = tui_read_line()")
        w("    println(\"\")")
        w("    var count: i64 = 0")
        w("    var idx: i64 = 0")
        w(f"    while idx < {N} {{")
        w("        let term = ontology_store_get(idx as i32)")
        w("        if starts_with(term.curie, prefix) {")
        w("            println(term.curie + \" | \" + term.label)")
        w("            count = count + 1")
        w("        }")
        w("        idx = idx + 1")
        w("    }")
        w("    print_int(count as i32)")
        w("    println(\" terms\")")
    elif name == "search":
        w("    print(\"Query: \")")
        w("    let query = tui_read_line()")
        w("    println(\"\")")
        w("    var idx: i64 = 0")
        w("    var count: i64 = 0")
        w(f"    while idx < {N} {{")
        w("        let term = ontology_store_get(idx as i32)")
        w("        if str_contains(term.label, query) || str_contains(term.curie, query) {")
        w("            println(term.curie + \" | \" + term.label + \" | \" + term.provenance)")
        w("            count = count + 1")
        w("        }")
        w("        var sidx: i64 = 0")
        w("        while sidx < term.synonyms_len {")
        w("            if str_contains(term.synonyms[sidx as usize], query) {")
        w("                println(term.curie + \" | \" + term.label + \" | \" + term.provenance)")
        w("                count = count + 1")
        w("            }")
        w("            sidx = sidx + 1")
        w("        }")
        w("        idx = idx + 1")
        w("    }")
        w("    print_int(count as i32)")
        w("    println(\" results\")")
    elif name == "ancestors":
        w("    print(\"CURIE: \")")
        w("    var current = tui_read_line()")
        w("    println(\"\")")
        w("    var depth = 0")
        w("    while depth < 8 && str_len(current) > 0 {")
        w("        println(current)")
        w("        let term = ontology_store_resolve_local(current)")
        w("        if term.parents_len == 0 { break }")
        w("        current = term.parents[0]")
        w("        depth = depth + 1")
        w("    }")
    elif name == "resolve":
        w("    print(\"CURIE: \")")
        w("    let curie = tui_read_line()")
        w("    println(\"\")")
        w("    let term = ontology_store_resolve_local(curie)")
        w("    if ontology_term_found(term) {")
        w("        println(\"curie: \" + term.curie)")
        w("        println(\"label: \" + term.label)")
        w("        println(\"definition: \" + term.definition)")
        w("        println(\"iri: \" + term.iri)")
        w("        println(\"provenance: \" + term.provenance)")
        w("        print_int(term.parents_len as i32)")
        w("        println(\" parents\")")
        w("        var i: i64 = 0")
        w("        while i < term.parents_len {")
        w("            println(\"  - \" + term.parents[i as usize])")
        w("            i = i + 1")
        w("        }")
        w("        print_int(term.synonyms_len as i32)")
        w("        println(\" synonyms\")")
        w("        i = 0")
        w("        while i < term.synonyms_len {")
        w("            println(\"  - \" + term.synonyms[i as usize])")
        w("            i = i + 1")
        w("        }")
        w("    } else {")
        w("        println(\"unresolved\")")
        w("    }")
    w("}")
    w("")

w("fn tui_action_validate() with IO, Mut {")
w("    ontology_validate()")
w("}")
w("")
w("fn tui_run_action(idx: i64) with IO, Mut {")
w("    tui_clear()")
w("    if idx == 0 { tui_action_resolve() }")
w("    else if idx == 1 { tui_action_search() }")
w("    else if idx == 2 { tui_action_ancestors() }")
w("    else if idx == 3 { tui_action_is_subclass() }")
w("    else if idx == 4 { tui_action_map() }")
w("    else if idx == 5 { tui_action_list() }")
w("    else if idx == 6 { tui_action_count() }")
w("    else if idx == 7 { tui_action_validate() }")
w("    else if idx == 8 { tui_action_graph() }")
w("    else if idx == 9 { tui_action_fuzzy() }")
w("    println(\"\")")
w("    print(\"Press any key to continue...\")")
w("    tui_read_byte()")
w("}")
w("")
w("fn ontology_run_tui() -> i64 with IO, Mut {")
w("    tui_save_termios()")
w("    tui_set_raw_mode()")
w("    tui_hide_cursor()")
w("    var selected: i64 = 0")
w("    var running = true")
w("    while running {")
w("        tui_clear()")
w("        tui_draw_menu(selected)")
w("        let c = tui_read_byte()")
w("        if c == 27 {")
w("            let c2 = tui_read_byte()")
w("            if c2 == 91 {")
w("                let c3 = tui_read_byte()")
w("                if c3 == 65 && selected > 0 {")
w("                    selected = selected - 1")
w("                } else if c3 == 66 && selected < 11 {")
w("                    selected = selected + 1")
w("                }")
w("            }")
w("        } else if c == 113 {")
w("            running = false")
w("        } else if c == 13 || c == 10 {")
w("            if selected == 11 {")
w("                running = false")
w("            } else {")
w("                tui_run_action(selected)")
w("            }")
w("        }")
w("    }")
w("    tui_restore_termios()")
w("    tui_show_cursor()")
w("    tui_clear()")
w("    0")
w("}")
w("")

# Batch
w("fn ontology_run_batch(path: string) -> i64 with IO, Mut {")
w("    let fd = syscall6(2, path, 0, 0, 0, 0, 0)")
w("    if fd < 0 {")
w("        println(\"ERROR: cannot open batch file \" + path)")
w("        return 1")
w("    }")
w("    let n = syscall6(0, fd, &BATCH_BUF, 4095, 0, 0, 0)")
w("    syscall6(3, fd, 0, 0, 0, 0, 0)")
w("    if n <= 0 {")
w("        println(\"ERROR: empty batch file\")")
w("        return 1")
w("    }")
w("    var line = \"\"")
w("    var i: i64 = 0")
w("    while i < n {")
w("        let c = BATCH_BUF[i as usize] as i64")
w("        if c < 0 { c = c + 256 }")
w("        if c == 10 {")
w("            if str_len(line) > 0 {")
w("                ontology_run_batch_line(line)")
w("            }")
w("            line = \"\"")
w("        } else if c >= 32 && c <= 126 {")
w("            let chars = \" !\\\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\"")
w("            line = line + str_slice(chars, c - 32, c - 31)")
w("        }")
w("        i = i + 1")
w("    }")
w("    if str_len(line) > 0 {")
w("        ontology_run_batch_line(line)")
w("    }")
w("    0")
w("}")
w("")
w("fn ontology_run_batch_line(line: string) -> i64 with IO, Mut {")
w("    println(\"# \" + line)")
w("    let spc = str_index_of(line, \" \")")
w("    let cmd = if spc < 0 { line } else { str_slice(line, 0, spc) }")
w("    let rest = if spc < 0 { \"\" } else { str_slice(line, spc + 1, str_len(line)) }")
w("    if cmd == \"resolve\" {")
w("        let term = ontology_store_resolve_local(rest)")
w("        if ontology_term_found(term) {")
w("            println(term.curie + \" | \" + term.label)")
w("        } else {")
w("            println(\"unresolved\")")
w("        }")
w("    } else if cmd == \"count\" {")
w("        let count = ontology_count_terms(rest)")
w("        print_int(count as i32)")
w("        println(\" terms\")")
w("    } else if cmd == \"ancestors\" {")
w("        var current = rest")
w("        var depth = 0")
w("        while depth < 8 && str_len(current) > 0 {")
w("            println(current)")
w("            let term = ontology_store_resolve_local(current)")
w("            if term.parents_len == 0 { break }")
w("            current = term.parents[0]")
w("            depth = depth + 1")
w("        }")
w("    } else {")
w("        println(\"unknown batch command: \" + cmd)")
w("    }")
w("    0")
w("}")
w("")

# JSON helpers
w("fn json_escape(s: string) -> string {")
w("    var out = \"\"")
w("    var i: i64 = 0")
w("    while i < str_len(s) {")
w("        let c = s[i as usize]")
w("        if c == 34 { out = out + \"\\\\\\\"\" }")
w("        else if c == 92 { out = out + \"\\\\\\\\\" }")
w("        else if c == 10 { out = out + \"\\\\n\" }")
w("        else if c == 13 { out = out + \"\\\\r\" }")
w("        else { out = out + str_slice(s, i, i + 1) }")
w("        i = i + 1")
w("    }")
w("    out")
w("}")
w("")

# CLI
w("fn ontology_run_cli() -> i64 with IO, Mut {")
w("    let argc = arg_count()")
w("    if argc < 2 {")
w("        println(\"usage: ontology <resolve|search|ancestors|is-subclass|map|list|count|validate|graph|fuzzy|batch|tui> ...\")")
w("        return 1")
w("    }")
w("    let cmd = get_arg(1)")
w("    var json_mode = false")
w("    var arg_off = 0")
w("    if cmd == \"--json\" {")
w("        json_mode = true")
w("        if argc < 3 { println(\"usage: ontology --json <command> ...\"); return 1 }")
w("        cmd = get_arg(2)")
w("        arg_off = 1")
w("    }")
w("    if cmd == \"resolve\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology resolve <curie>\"); return 1 }")
w("        let term = ontology_store_resolve_local(get_arg(2 + arg_off))")
w("        if ontology_term_found(term) {")
w("            if json_mode {")
w("                println(\"{\\\"curie\\\": \\\"\" + json_escape(term.curie) + \"\\\", \\\"label\\\": \\\"\" + json_escape(term.label) + \"\\\"}\")")
w("            } else {")
w("                println(\"curie: \" + term.curie)")
w("                println(\"label: \" + term.label)")
w("                println(\"definition: \" + term.definition)")
w("                println(\"iri: \" + term.iri)")
w("            }")
w("        } else {")
w("            if json_mode { println(\"{\\\"error\\\": \\\"unresolved\\\"}\") } else { println(\"unresolved\") }")
w("        }")
w("        return 0")
w("    }")
w("    if cmd == \"ancestors\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology ancestors <curie>\"); return 1 }")
w("        var current = get_arg(2 + arg_off)")
w("        var depth = 0")
w("        if json_mode { println(\"[\") }")
w("        while depth < 8 && str_len(current) > 0 {")
w("            if json_mode { println(\"  \\\"\" + json_escape(current) + \"\\\"\") } else { println(current) }")
w("            let term = ontology_store_resolve_local(current)")
w("            if term.parents_len == 0 { break }")
w("            current = term.parents[0]")
w("            depth = depth + 1")
w("        }")
w("        if json_mode { println(\"]\") }")
w("        return 0")
w("    }")
w("    if cmd == \"is-subclass\" {")
w("        if argc < 4 + arg_off { println(\"usage: ontology is-subclass <child> <parent>\"); return 1 }")
w("        let result = ontology_is_subclass(get_arg(2 + arg_off), get_arg(3 + arg_off))")
w("        if json_mode { println(if result { \"{\\\"result\\\": true}\" } else { \"{\\\"result\\\": false}\" }) } else { println(if result { \"yes\" } else { \"no\" }) }")
w("        return 0")
w("    }")
w("    if cmd == \"search\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology search <query>\"); return 1 }")
w("        let query = get_arg(2 + arg_off)")
w("        var idx: i64 = 0")
w("        var count: i64 = 0")
w("        if json_mode { println(\"[\") }")
w(f"        while idx < {N} {{")
w("            let term = ontology_store_get(idx as i32)")
w("            var matched = false")
w("            if str_contains(term.label, query) || str_contains(term.curie, query) { matched = true }")
w("            var sidx: i64 = 0")
w("            while sidx < term.synonyms_len {")
w("                if str_contains(term.synonyms[sidx as usize], query) { matched = true }")
w("                sidx = sidx + 1")
w("            }")
w("            if matched {")
w("                if json_mode { println(\"  {\\\"curie\\\": \\\"\" + json_escape(term.curie) + \"\\\", \\\"label\\\": \\\"\" + json_escape(term.label) + \"\\\"}\") } else { println(term.curie + \" | \" + term.label) }")
w("                count = count + 1")
w("            }")
w("            idx = idx + 1")
w("        }")
w("        if json_mode { println(\"]\") } else { print_int(count as i32); println(\" results\") }")
w("        return 0")
w("    }")
w("    if cmd == \"map\" {")
w("        if argc < 5 + arg_off { println(\"usage: ontology map <curie> --to <ontology>\"); return 1 }")
w("        let source_curie = get_arg(2 + arg_off)")
w("        let target_ontology = get_arg(4 + arg_off)")
w("        let mappings = ontology_store_map_local(source_curie, target_ontology)")
w("        if json_mode { println(\"[\") }")
w("        var i: i64 = 0")
w("        while i < mappings.len {")
w("            let m = mappings.items[i as usize]")
w("            if json_mode { println(\"  {\\\"subject\\\": \\\"\" + m.subject_id + \"\\\", \\\"object\\\": \\\"\" + m.object_id + \"\\\"}\") } else { println(m.subject_id + \" -> \" + m.object_id) }")
w("            i = i + 1")
w("        }")
w("        if json_mode { println(\"]\") } else if mappings.len == 0 { println(\"no mappings found\") }")
w("        return 0")
w("    }")
w("    if cmd == \"list\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology list <prefix>\"); return 1 }")
w("        let prefix = get_arg(2 + arg_off)")
w("        var count: i64 = 0")
w("        if json_mode { println(\"[\") }")
w(f"        var idx: i64 = 0")
w(f"        while idx < {N} {{")
w("            let term = ontology_store_get(idx as i32)")
w("            if starts_with(term.curie, prefix) {")
w("                if json_mode { println(\"  {\\\"curie\\\": \\\"\" + term.curie + \"\\\", \\\"label\\\": \\\"\" + json_escape(term.label) + \"\\\"}\") } else { println(term.curie + \" | \" + term.label) }")
w("                count = count + 1")
w("            }")
w("            idx = idx + 1")
w("        }")
w("        if json_mode { println(\"]\") } else { print_int(count as i32); println(\" terms\") }")
w("        return 0")
w("    }")
w("    if cmd == \"count\" {")
w("        let prefix = if argc >= 3 + arg_off { get_arg(2 + arg_off) } else { \"\" }")
w("        let count = ontology_count_terms(prefix)")
w("        if json_mode { println(\"{\\\"count\\\": \" + (count as str) + \"}\") } else { print_int(count as i32); if str_len(prefix) > 0 { println(\" terms matching \" + prefix) } else { println(\" total terms\") } }")
w("        return 0")
w("    }")
w("    if cmd == \"validate\" {")
w("        let errs = ontology_validate()")
w("        if json_mode { println(\"{\\\"errors\\\": \" + (errs as str) + \"}\") }")
w("        return errs")
w("    }")
w("    if cmd == \"graph\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology graph <curie>\"); return 1 }")
w("        println(ontology_graph_dot(get_arg(2 + arg_off)))")
w("        return 0")
w("    }")
w("    if cmd == \"fuzzy\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology fuzzy <query>\"); return 1 }")
w("        let query = get_arg(2 + arg_off)")
w("        let results = ontology_store_fuzzy_local(query)")
w("        if json_mode { println(\"[\") }")
w("        var i: i64 = 0")
w("        while i < results.len {")
w("            let term = results.items[i as usize]")
w("            if json_mode { println(\"  {\\\"curie\\\": \\\"\" + term.curie + \"\\\", \\\"label\\\": \\\"\" + json_escape(term.label) + \"\\\"}\") } else { println(term.curie + \" | \" + term.label) }")
w("            i = i + 1")
w("        }")
w("        if json_mode { println(\"]\") }")
w("        if results.len == 0 { println(\"no matches\") }")
w("        return 0")
w("    }")
w("    if cmd == \"batch\" {")
w("        if argc < 3 + arg_off { println(\"usage: ontology batch <file>\"); return 1 }")
w("        return ontology_run_batch(get_arg(2 + arg_off))")
w("    }")
w("    if cmd == \"tui\" {")
w("        return ontology_run_tui()")
w("    }")
w("    println(\"unknown ontology subcommand: \" + cmd)")
w("    return 1")
w("}")
w("")
w("// ============================================================================")
w("// END ONTOLOGY KERNEL")
w("// ============================================================================")
w("")

with open('/tmp/ontology_kernel_full.sio', 'w') as f:
    f.write('\n'.join(out) + '\n')

print(f"Generated kernel: {len(out)} lines")
