#!/usr/bin/env bash
# scripts/dev/default_path_fidelity_gate.sh
#
# Permanent regression gate for the default multi-module compile route.
#
# Compiles a 2-module Sounio program (main.sio importing greet.sio) with the
# DEFAULT compiler route (no -O) and verifies that mutating the body of the
# imported function produces the corresponding stdout. Also re-runs every case
# with -O to confirm the optimized route remains correct.
#
# Detects the silent-corruption defect class recorded in
# artifacts/witnesses/module_graph_facade_vertical_20260719T132620Z.json: a
# fast path that emits a hardcoded ELF regardless of imported function bodies.
# That defect manifests as "every mutation prints 42\n" — if you see it again,
# this gate fails.
#
# Verdict: PASS if every case produces exact expected bytes for both default
# and -O routes. BLOCKED otherwise, with the first failing case and exact
# observed bytes.
#
# This gate DOES NOT modify any compiler source. It only:
#   - swaps tests/compiler/default_path_fidelity_gate/greet.sio between
#     fixture variants temporarily (restored in trap)
#   - writes scratch ELFs to a mktemp dir
#   - emits a single PASS/BLOCKED line + per-case details to stdout
#
# Bounded scope: no CI wiring (promotion is a separate decision), no
# ModuleGraph abstractions, no roadmap expansion.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

FIXTURE_DIR="$REPO_ROOT/tests/compiler/default_path_fidelity_gate"
MAIN_SRC="$FIXTURE_DIR/main.sio"
GREET="$FIXTURE_DIR/greet.sio"
GREET_BACKUP="$(mktemp /tmp/default-path-fidelity-greet.XXXXXX.sio)"
SCRATCH_DIR="$(mktemp -d /tmp/default-path-fidelity.XXXXXX)"
trap 'rm -rf "$SCRATCH_DIR"; [[ -s "$GREET_BACKUP" ]] && mv -f "$GREET_BACKUP" "$GREET" 2>/dev/null || true' EXIT

# Save original greet.sio if it exists (it is generated by the gate, so this
# is purely defensive).
if [[ -f "$GREET" ]]; then
  cp -a "$GREET" "$GREET_BACKUP"
fi

log()  { printf '[gate] %s\n' "$*" >&2; }

# Compiler resolution: prefer the locally-built source-fresh Madaros
# (artifacts/self-hosted/madaros), fall back to the checked prebuilt
# (bin/madaros-linux-x86_64), then the wrapper.
RAW=""
for cand in "$REPO_ROOT/artifacts/self-hosted/madaros" "$REPO_ROOT/bin/madaros-linux-x86_64"; do
  if [[ -x "$cand" && "$(head -c2 "$cand" 2>/dev/null)" != '#!' ]]; then
    RAW="$cand"; break
  fi
done

if [[ -z "$RAW" ]]; then
  verdict=BLOCKED
  verdict_reason="no raw Madaros ELF found (run make build-madaros)"
  log "BLOCKED: $verdict_reason"
  emit_summary
  exit 1
fi

RAW_SHA256="$(sha256sum "$RAW" | awk '{print $1}')"
RAW_SIZE="$(stat -c '%s' "$RAW")"
log "raw_elf=$RAW"
log "raw_elf_sha256=$RAW_SHA256"
log "raw_elf_size=$RAW_SIZE"

GIT_SHA="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
log "git_sha=$GIT_SHA"
log "git_branch=$GIT_BRANCH"

# Case matrix: (variant_file, expected_stdout_hex).
# Expected stdout is captured as `od -An -tx1` byte sequence so the gate can
# detect whitespace and newline differences, not just text inequality.
declare -a CASES=(
  "greet_42.sio|34 32 0a"            # "42\n"
  "greet_999.sio|39 39 39 0a"        # "999\n"
  "greet_7.sio|37 0a"                # "7\n"
  "greet_neg7.sio|2d 37 0a"          # "-7\n"
)

run_case() {
  local variant="$1"
  local expected_hex="$2"
  local route="$3"   # "default", "-O", or "compact"
  local label="${variant%.sio}_${route}"
  local out="$SCRATCH_DIR/${label}.elf"
  local stdout_file="$SCRATCH_DIR/${label}.stdout"
  local stderr_file="$SCRATCH_DIR/${label}.stderr"

  cp "$FIXTURE_DIR/$variant" "$GREET"

  local raw_args=("$MAIN_SRC" -o "$out")
  if [[ "$route" == "-O" ]]; then
    raw_args+=("-O")
  fi

  if [[ "$route" == "compact" ]]; then
    SOUNIO_ENABLE_COMPACT_IMPORTED_IR=1 "$RAW" "${raw_args[@]}" >"$stdout_file" 2>"$stderr_file"
  else
    "$RAW" "${raw_args[@]}" >"$stdout_file" 2>"$stderr_file"
  fi
  local cc_rc=$?

  if [[ $cc_rc -ne 0 ]]; then
    printf '%s|compile_fail|cc_rc=%d\n' "$label" "$cc_rc"
    return 1
  fi
  if [[ ! -s "$out" ]]; then
    printf '%s|no_elf\n' "$label"
    return 1
  fi
  chmod +x "$out"
  local run_stdout_file="$SCRATCH_DIR/${label}.run.out"
  "$out" >"$run_stdout_file" 2>/dev/null
  local run_rc=$?
  if [[ $run_rc -ne 0 ]]; then
    printf '%s|run_fail|run_rc=%d\n' "$label" "$run_rc"
    return 1
  fi
  local actual_hex
  actual_hex="$(od -An -tx1 "$run_stdout_file" | tr -s ' \n' ' ' | sed 's/^ //;s/ $//')"
  if [[ "$actual_hex" != "$expected_hex" ]]; then
    printf '%s|stdout_mismatch|expected=%s|observed=%s\n' "$label" "$expected_hex" "$actual_hex"
    return 1
  fi
  printf '%s|pass\n' "$label"
  return 0
}

declare -a RESULTS=()
fail_count=0

# Default route
for case_spec in "${CASES[@]}"; do
  variant="${case_spec%%|*}"
  expected="${case_spec#*|}"
  result_line=$(run_case "$variant" "$expected" "default")
  rc=$?
  RESULTS+=("$result_line")
  if [[ $rc -ne 0 ]]; then fail_count=$((fail_count + 1)); fi
done

# -O route
for case_spec in "${CASES[@]}"; do
  variant="${case_spec%%|*}"
  expected="${case_spec#*|}"
  result_line=$(run_case "$variant" "$expected" "-O")
  rc=$?
  RESULTS+=("$result_line")
  if [[ $rc -ne 0 ]]; then fail_count=$((fail_count + 1)); fi
done

# Compact route (SOUNIO_ENABLE_COMPACT_IMPORTED_IR=1) — verifies the legacy
# emitter, now reachable only behind the opt-in env var, also produces the
# correct per-mutation stdout. Detects regressions in the compact emitter's
# kind=3 / VALUES[fi] handling without changing the default route.
for case_spec in "${CASES[@]}"; do
  variant="${case_spec%%|*}"
  expected="${case_spec#*|}"
  result_line=$(run_case "$variant" "$expected" "compact")
  rc=$?
  RESULTS+=("$result_line")
  if [[ $rc -ne 0 ]]; then fail_count=$((fail_count + 1)); fi
done

# Canonical hello_pkg check (uses original greet=42 from origin/main)
if [[ -f "$REPO_ROOT/examples/projects/hello_pkg/src/main.sio" \
   && -f "$REPO_ROOT/examples/projects/hello_pkg/src/greet.sio" ]]; then
  hello_out="$SCRATCH_DIR/hello_pkg.elf"
  "$RAW" "$REPO_ROOT/examples/projects/hello_pkg/src/main.sio" -o "$hello_out" > /dev/null 2>&1
  if [[ $? -eq 0 && -s "$hello_out" ]]; then
    chmod +x "$hello_out"
    hello_stdout="$SCRATCH_DIR/hello_pkg.run.out"
    "$hello_out" >"$hello_stdout" 2>/dev/null
    hello_hex="$(od -An -tx1 "$hello_stdout" | tr -s ' \n' ' ' | sed 's/^ //;s/ $//')"
    if [[ "$hello_hex" == "34 32 0a" ]]; then
      RESULTS+=("hello_pkg_default|pass")
    else
      RESULTS+=("hello_pkg_default|stdout_mismatch|expected=34 32 0a|observed=$hello_hex")
      fail_count=$((fail_count + 1))
    fi
  else
    RESULTS+=("hello_pkg_default|compile_fail")
    fail_count=$((fail_count + 1))
  fi
fi

emit_summary() {
  printf '\n=== per-case results ===\n'
  for r in "${RESULTS[@]}"; do
    printf '  %s\n' "$r"
  done
  printf '\n'
  if [[ "$fail_count" -eq 0 ]]; then
    printf 'DEFAULT_PATH_FIDELITY_GATE_PASS raw_sha256=%s cases=%d\n' \
      "${RAW_SHA256:0:16}" "${#RESULTS[@]}"
  else
    printf 'DEFAULT_PATH_FIDELITY_GATE_BLOCKED raw_sha256=%s cases=%d failed=%d\n' \
      "${RAW_SHA256:0:16}" "${#RESULTS[@]}" "$fail_count"
  fi
}

emit_summary

if [[ "$fail_count" -eq 0 ]]; then
  exit 0
else
  exit 1
fi
