#!/usr/bin/env python3
"""Emit the Sounio fixture for the pow/tgamma intrinsics from the oracle.

The fixture is generated rather than hand-written for one reason: its expected
values must come from the same model the emitter was transliterated from, and a
hand-copied bit pattern is a transcription error waiting to happen in a place
where the test would then certify the error.

WHY NOT libm. The obvious oracle is the system tgamma, and it is the wrong one.
Measured on this host: glibc's tgamma returns 355687428096000.1 where 17! is the
integer 355687428096000, and is 1 ulp off on 18!, 19!, 21! and 22! as well --
five consecutive exactly-representable factorials. Over the design's bands it
reaches 4.6 ulp. A fixture asserting agreement with libm would fail a correct
implementation on exactly the rows that matter most, the ones with an exact
answer. Expected values therefore come from the oracle, which decides against
mpmath at 60 digits.

Tolerances are per row, taken from the design's own classification: rows with an
exactly representable answer are asserted bit-exact, the rest to the published
bound (pow <= 2 ulp, tgamma <= 5 ulp). Comparison is by integer distance between
bit patterns, which IS the ulp distance for two finite values of the same sign,
and the generator refuses to emit a tolerance row where that assumption fails.
"""
import importlib.util
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ORACLE = os.path.join(ROOT, "scripts", "research", "pow_tgamma_oracle.py")
OUT = os.path.join(ROOT, "tests", "run-pass", "ffi_pow_tgamma_vectors.sio")


def load_oracle():
    spec = importlib.util.spec_from_file_location("oracle", ORACLE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def bits(x):
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def value(b):
    return struct.unpack("<d", struct.pack("<Q", b))[0]


def ulp_distance_is_meaningful(a_bits, b_bits):
    """Integer bit distance equals ulp distance only for same-sign finite values."""
    a, b = value(a_bits), value(b_bits)
    if a != a or b != b:            # NaN
        return False
    if a in (float("inf"), float("-inf")) or b in (float("inf"), float("-inf")):
        return False
    return (a_bits >> 63) == (b_bits >> 63)


def emit_rows(name, rows):
    """rows: list of (x_bits, y_bits_or_None, expected_bits, tol_ulp, note)"""
    lines = []
    for x, y, e, tol, note in rows:
        if tol > 0 and not ulp_distance_is_meaningful(e, e):
            raise SystemExit(f"{name}: row {note} wants a tolerance but its expected value "
                             "is NaN or infinite, where bit distance is not ulp distance")
        lines.append((x, y, e, tol, note))
    return lines



def fmt(b):
    """A 64-bit pattern as a Sounio i64 literal. Values with bit 63 set do not
    fit a positive literal, so they are written as the negative i64 with the
    same bits -- the fixture reads them back through bits_to_f64, which cares
    about the pattern and not the sign of the integer that carried it."""
    return str(b if b < 2**63 else b - 2**64)


HEADER = """//@ run-pass
// pow and tgamma reference vectors. GENERATED by
// scripts/dev/gen_pow_tgamma_fixture.py from scripts/research/pow_tgamma_oracle.py.
// Do not hand-edit: regenerate. A hand-copied bit pattern is a transcription
// error in the one place where the test would certify it rather than catch it.
//
// The reference is the ORACLE, decided against mpmath at 60 digits, and NOT
// libm. glibc's tgamma returns 355687428096000.1 where 17! is the integer
// 355687428096000, and is 1 ulp off on 18!, 19!, 21! and 22! as well -- five
// consecutive exactly-representable factorials, precisely the rows a fixture
// should assert hardest. Asserting agreement with libm would fail a correct
// implementation.
//
// Tolerance is per row, from the design's own classification: rows with an
// exactly representable answer are bit-exact, the rest carry the published
// bound (pow <= 2 ulp, tgamma <= 5 ulp). Comparison is the integer distance
// between bit patterns, which IS the ulp distance for two finite values of the
// same sign; NaN rows assert NaN-ness instead, since IEEE-754 leaves a
// generated NaN's sign and payload unspecified.

extern "C" {
    fn pow(x: f64, y: f64) -> f64;
    fn tgamma(x: f64) -> f64;
}

fn is_nan_bits(b: i64) -> bool {
    let e = (b >> 52) & 2047
    let m = b & 4503599627370495
    e == 2047 && m != 0
}

fn ulp_gap(a: i64, b: i64) -> i64 {
    if a >= b { return a - b }
    b - a
}
"""

MAIN = """
fn main() -> i32 with IO, Panic {
    var bad = 0
    bad = bad + check_pow()
    bad = bad + check_tgamma()
    if bad == 0 {
        println("ffi_pow_tgamma_vectors: PASS")
        return 0
    }
    println("ffi_pow_tgamma_vectors: FAIL")
    return 1
}
"""


def emit_table(name, rows, two_args):
    n = len(rows)
    out = [f"\nfn check_{name}() -> i64 with IO, Panic {{", "    var bad: i64 = 0"]
    for x, y, e, tol, note in rows:
        safe = note.replace("\n", " ")[:70]
        call = f"pow(bits_to_f64({fmt(x)}), bits_to_f64({fmt(y)}))" if two_args \
            else f"tgamma(bits_to_f64({fmt(x)}))"
        out.append(f"    // {safe}")
        if is_nan(e):
            out.append(f"    if !is_nan_bits(f64_to_bits({call})) {{ bad = bad + 1 }}")
        elif tol == 0:
            out.append(f"    if f64_to_bits({call}) != {fmt(e)} {{ bad = bad + 1 }}")
        else:
            out.append(f"    if ulp_gap(f64_to_bits({call}), {fmt(e)}) > {tol} {{ bad = bad + 1 }}")
    out.append("    bad")
    out.append("}")
    return "\n".join(out)


def is_nan(b):
    return ((b >> 52) & 0x7FF) == 0x7FF and (b & 0xFFFFFFFFFFFFF) != 0


def main():
    oracle = load_oracle()
    pow_rows = []
    for _, xb, yb, eb, note in oracle.POW_VECTORS:
        exact = ulp_distance_is_meaningful(eb, eb) and value(eb) == int(value(eb)) \
            if abs(value(eb)) < 2**53 else False
        pow_rows.append((xb, yb, eb, 0 if exact else 2, note))
    tg_rows = []
    for _, xb, eb, note in oracle.TGAMMA_VECTORS:
        exact = "exact" in note.lower() or "MUST be" in note
        tg_rows.append((xb, None, eb, 0 if exact else 5, note))
    lines = [HEADER]
    lines.append(emit_table("pow", pow_rows, two_args=True))
    lines.append(emit_table("tgamma", tg_rows, two_args=False))
    lines.append(MAIN)
    open(OUT, "w").write("\n".join(lines))
    print(f"pow vectors:    {len(pow_rows)}  ({sum(1 for r in pow_rows if r[3]==0)} bit-exact)")
    print(f"tgamma vectors: {len(tg_rows)}  ({sum(1 for r in tg_rows if r[3]==0)} bit-exact)")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
