#!/usr/bin/env bash
# gen_axiom_inventory.sh -- regenerate formal/AXIOM_INVENTORY.md from source.
#
# What it counts, over every tracked `.lean` file under formal/ (excluding the
# vendored formal/lake/packages/ tree):
#
#   * every `axiom` declaration, with its name and line, grouped by file;
#   * `native_decide` uses per file;
#   * `sorry` in code (expected: 0).
#
# Comments (`-- ...`, nested `/- ... -/`, doc comments `/-- -/`, `/-! -/`) and
# string literals are blanked out BEFORE matching, preserving line numbers. A
# raw `grep` over-counts: many files say in their doc comments that they use
# "no sorry" or "no axioms". The method matches the one formal/README.md
# documents (declarations matching `^\s*axiom\s`, optionally preceded by
# `private`/`protected`/`noncomputable` modifiers, which no file currently uses).
#
# What it does NOT do: it does not run Lean. The "#print axioms" section of the
# inventory is not regenerated here; CI produces it (lean-proofs job, step
# "Axiom report for headline theorems", from formal/AxiomReport.lean and
# formal/lean4/AxiomReport.lean). The inventory carries the last reported
# result, explicitly marked as reported.
#
# Usage:
#   scripts/dev/gen_axiom_inventory.sh            # rewrite formal/AXIOM_INVENTORY.md
#   scripts/dev/gen_axiom_inventory.sh --check    # exit 1 if the file is stale
#   scripts/dev/gen_axiom_inventory.sh --stdout   # print, write nothing
set -euo pipefail

ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
OUT="$ROOT/formal/AXIOM_INVENTORY.md"
MODE="${1:-write}"

case "$MODE" in
  write|--check|--stdout) ;;
  *) echo "usage: $0 [--check|--stdout]" >&2; exit 2 ;;
esac

TMP="$(mktemp)"
LIST="$(mktemp)"
trap 'rm -f "$TMP" "$LIST"' EXIT

cd "$ROOT"
git ls-files -z -- 'formal/*.lean' 'formal/**/*.lean' >"$LIST"
python3 - "$TMP" "$LIST" <<'PY'
import re
import sys

out_path = sys.argv[1]
with open(sys.argv[2], encoding="utf-8") as fh:
    listing = fh.read()
paths = sorted({p for p in listing.split("\0")
                if p and not p.startswith("formal/lake/packages/")})


def strip(src: str) -> str:
    """Blank Lean comments and string literals, keeping newlines."""
    out = []
    i, n = 0, len(src)
    depth = 0          # nesting depth of /- -/ block comments
    in_str = False
    while i < n:
        c = src[i]
        nxt = src[i + 1] if i + 1 < n else ""
        if depth > 0:
            if c == "/" and nxt == "-":
                depth += 1
                out.append("  ")
                i += 2
            elif c == "-" and nxt == "/":
                depth -= 1
                out.append("  ")
                i += 2
            else:
                out.append("\n" if c == "\n" else " ")
                i += 1
        elif in_str:
            if c == "\\" and i + 1 < n:
                out.append("\n" if nxt == "\n" else " ")
                out.append(" ")
                i += 2
            elif c == '"':
                in_str = False
                out.append('"')
                i += 1
            else:
                out.append("\n" if c == "\n" else " ")
                i += 1
        else:
            if c == "/" and nxt == "-":
                depth = 1
                out.append("  ")
                i += 2
            elif c == "-" and nxt == "-":
                j = src.find("\n", i)
                if j < 0:
                    j = n
                out.append(" " * (j - i))
                i = j
            elif c == '"':
                in_str = True
                out.append('"')
                i += 1
            else:
                out.append(c)
                i += 1
    return "".join(out)


AX = re.compile(r"^\s*(?:(?:private|protected|noncomputable|unsafe)\s+)*axiom\s+([^\s:({\[]+)")
ND = re.compile(r"\bnative_decide\b")
SORRY = re.compile(r"\bsorry\b")

axioms = {}      # path -> [(line, name)]
nd = {}          # path -> count
sorries = {}     # path -> count
for p in paths:
    with open(p, encoding="utf-8") as fh:
        code = strip(fh.read())
    for ln, line in enumerate(code.split("\n"), 1):
        m = AX.match(line)
        if m:
            axioms.setdefault(p, []).append((ln, m.group(1)))
    k = len(ND.findall(code))
    if k:
        nd[p] = k
    s = len(SORRY.findall(code))
    if s:
        sorries[p] = s

n_ax = sum(len(v) for v in axioms.values())
n_nd = sum(nd.values())
n_sorry = sum(sorries.values())

L = []
w = L.append
w("# Axiom inventory (generated)")
w("")
w("<!-- GENERATED by scripts/dev/gen_axiom_inventory.sh -- do not edit by hand. -->")
w("")
w("Regenerate with `scripts/dev/gen_axiom_inventory.sh`; check freshness with")
w("`scripts/dev/gen_axiom_inventory.sh --check`. Scope: every tracked `.lean` file")
w("under `formal/`, excluding `formal/lake/packages/`. Comments and string")
w("literals are stripped before matching (a raw `grep` over-counts, because many")
w("files say in comments that they use no `sorry` or no axioms).")
w("")
w("| Count | Value |")
w("|---|---:|")
w(f"| `.lean` files scanned | {len(paths)} |")
w(f"| `sorry` in code | {n_sorry} |")
w(f"| `axiom` declarations | {n_ax}, in {len(axioms)} files |")
w(f"| `native_decide` uses | {n_nd}, in {len(nd)} files |")
w("")
w("A theorem that depends on one of these axioms is proved *relative to* it.")
w("`native_decide` adds `Lean.ofReduceBool` to the trusted base: it trusts the")
w("compiled evaluator, not the kernel alone.")
w("")
w("## `axiom` declarations, by file")
w("")
for p in sorted(axioms, key=lambda q: (-len(axioms[q]), q)):
    w(f"### `{p}` ({len(axioms[p])})")
    w("")
    w("| Line | Axiom |")
    w("|---:|---|")
    for ln, name in axioms[p]:
        w(f"| {ln} | `{name}` |")
    w("")
if sorries:
    w("## `sorry` in code")
    w("")
    w("| File | Count |")
    w("|---|---:|")
    for p in sorted(sorries):
        w(f"| `{p}` | {sorries[p]} |")
    w("")
w("## `native_decide` uses, by file")
w("")
w("| File | Count |")
w("|---|---:|")
for p in sorted(nd, key=lambda q: (-nd[q], q)):
    w(f"| `{p}` | {nd[p]} |")
w("")
w("## #print axioms for headline theorems")
w("")
w("**Not regenerated by this script** (no Lean toolchain is required to run it).")
w("The real list is produced by CI: the `lean-proofs` job runs")
w("`scripts/ci/lean_axiom_report.sh`, which builds the modules and runs")
w("`#print axioms` from `formal/AxiomReport.lean` (package `formal/`) and")
w("`formal/lean4/AxiomReport.lean` (package `formal/lean4/`), and prints the")
w("result in the job log. Headline theorems covered:")
w("")
w("| Theorem | Module | Package |")
w("|---|---|---|")
w("| `Sounio.OntologyELPlus.subBPlusC_iff` | `OntologyELPlusClosureComplete` | `formal/` |")
w("| `Sounio.OntologyELPlus.conflictBPlusC_iff` | `OntologyELPlusClosureComplete` | `formal/` |")
w("| ELF linker table of `formal/README.md` (8 theorems) | `ElfLinker` | `formal/` |")
w("| Type checker table of `formal/README.md` (8 theorems) | `TypeChecker` | `formal/` |")
w("| `Sounio.HydrogenPbox.monotone_event_equiv` | `SounioHydrogenPbox` | `formal/lean4/` |")
w("| `SounioGradedModal.egc_graded_soundness` | `SounioGradedModal` | `formal/lean4/` |")
w("")
w("To be filled by CI. **Last known (2026-10-05), reported, not regenerated:**")
w("")
w("- `subBPlusC_iff`: `propext`, `Classical.choice`, `Quot.sound`")
w("- `monotone_event_equiv`: `propext`, `Quot.sound`")
w("")
w("Every other entry in the table above has no recorded result yet; read it")
w("from the CI log.")

with open(out_path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(L) + "\n")
print(f"files={len(paths)} axioms={n_ax} axiom_files={len(axioms)} "
      f"native_decide={n_nd} native_decide_files={len(nd)} sorry={n_sorry}",
      file=sys.stderr)
PY

case "$MODE" in
  --stdout) cat "$TMP" ;;
  --check)
    if ! cmp -s "$TMP" "$OUT"; then
      echo "formal/AXIOM_INVENTORY.md is stale; run scripts/dev/gen_axiom_inventory.sh" >&2
      diff -u "$OUT" "$TMP" | head -40 >&2 || true
      exit 1
    fi
    echo "formal/AXIOM_INVENTORY.md is up to date" ;;
  write) cp "$TMP" "$OUT"; echo "wrote ${OUT#"$ROOT"/}" ;;
esac
