#!/usr/bin/env python3
"""Emit V0-B Sounio probes from MPFR literal_boundary JSONL corpora.

Oracle is tests/vectors/f128_f256/literal_boundary_f{128,256}.jsonl
(generated by gen/literal_boundary_gen.c + MPFR — not Sounio).

Writes:
  tests/run-pass/f128_v0b_literal_smoke.sio
  tests/run-pass/f256_v0b_literal_forms.sio

Rules:
  - Embed every source_literal that does not require unary minus (Sounio has
    no unary `-`; those rows are recorded as limb-oracle-only).
  - MUST embed every double_rounds_differs=true row that is embeddable as
    source (catches widen-via-f64 shortcuts).
  - expected.limbs are emitted as i64 arrays (LSW-first) — external oracle
    constants, never derived from Sounio.
  - Arithmetic corpora f128.jsonl / f256.jsonl are NOT consumed (V0-D).
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VEC = ROOT / "tests" / "vectors" / "f128_f256"

# Receipt hashes (GENERATION_RECEIPT.md Wave 3 section) — gate also checks these.
EXPECTED_SHA256 = {
    "literal_boundary_f128.jsonl": (
        "4b7804f0d70016770fb8bda4b67beb9226be1cebf9dc02f3771a4a7fcdbfa52d"
    ),
    "literal_boundary_f256.jsonl": (
        "574161d42fe10379d42198c03474a7b0b1daa39235111c45c2e8e28a7017a4c3"
    ),
}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def load_rows(name: str) -> list[dict]:
    path = VEC / name
    digest = sha256_file(path)
    expected = EXPECTED_SHA256[name]
    if digest != expected:
        raise SystemExit(
            f"hash mismatch {name}: got {digest} expected {expected} "
            f"(refusing to emit probes against a drifted oracle)"
        )
    rows = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def is_unary_minus(lit: str) -> bool:
    return lit.startswith("-")


def sio_escape_comment(s: str) -> str:
    return s.replace("\n", " ").replace("*/", "* /")


def emit_probe(
    *,
    fmt: str,
    rows: list[dict],
    out_path: Path,
    title: str,
) -> dict:
    """Return consumption report dict."""
    n_limbs = 2 if fmt == "f128" else 4
    ty = fmt

    embedded_src: list[dict] = []
    limb_only: list[dict] = []
    skipped_other: list[dict] = []

    for r in rows:
        lit = r["source_literal"]
        if is_unary_minus(lit):
            limb_only.append(r)
        else:
            embedded_src.append(r)

    lines: list[str] = []
    lines.append("//@ run-pass")
    lines.append("//@ check-only")
    lines.append(
        "//@ known-failure: V0-B not implemented yet — Madaros parser E218 on "
        "f128/f256; contract is scripts/ci/madaros_f128_f256_ladder_gate.sh "
        "--stage v0b (must FAIL until fable-1 lands literals through check). "
        "lean_single does not enforce E218 (see ladder V0-A engine split)."
    )
    lines.append(
        f"//@ description: V0-B — {ty} literals from MPFR literal_boundary corpus "
        "(external oracle, not Sounio)"
    )
    lines.append("//@ ladder-stage: V0-B")
    lines.append("//@ semantic-lane: WS-G-V0B-LITERALS-CHECK")
    lines.append(
        f"//@ oracle: tests/vectors/f128_f256/literal_boundary_{fmt}.jsonl"
    )
    lines.append(
        "//@ oracle-tool: MPFR 4.2.1 RNE via gen/literal_boundary_gen.c "
        "(see GENERATION_RECEIPT.md)"
    )
    lines.append("//")
    lines.append(f"// {title}")
    lines.append("//")
    lines.append(
        "// Generated by scripts/dev/ws_g_v0b_emit_literal_probes.py — do not hand-edit."
    )
    lines.append(
        "// Re-run the emitter after regenerating literal_boundary_*.jsonl."
    )
    lines.append("//")
    lines.append(
        "// Target after V0-B: `souc check` prints `check: OK` and does NOT emit"
    )
    lines.append(
        "// error[E218]. Expected limbs below are the MPFR bit patterns; a"
    )
    lines.append(
        "// widen-via-f64 implementation matches via_f64 limbs and fails every"
    )
    lines.append(
        "// double_rounds_differs=true row once limb identity is asserted."
    )
    lines.append("//")
    lines.append(
        "// Gate: scripts/ci/madaros_f128_f256_ladder_gate.sh --stage v0b"
    )
    lines.append("")

    # Oracle limb tables (always present — external ground truth).
    lines.append(
        f"// --- MPFR expected.limbs (LSW-first i64 × {n_limbs}) — external oracle ---"
    )
    for r in rows:
        lit = r["source_literal"]
        limbs = r["expected"]["limbs"]
        via = r["via_f64"]["limbs"]
        dr = bool(r.get("double_rounds_differs"))
        rid = r["id"]
        fam = r["family"]
        lines.append(
            f"// {rid} family={fam} double_rounds_differs={dr} "
            f"source={sio_escape_comment(lit)!r}"
        )
        limb_lit = ", ".join(str(int(x)) for x in limbs)
        via_lit = ", ".join(str(int(x)) for x in via)
        lines.append(
            f"let ORACLE_{rid}_EXPECTED: [i64; {n_limbs}] = [{limb_lit}]"
        )
        lines.append(
            f"let ORACLE_{rid}_VIA_F64: [i64; {n_limbs}] = [{via_lit}]"
        )
    lines.append("")

    # Identity helper keeps types in the surface without arithmetic.
    lines.append(f"fn identity_{ty}(x: {ty}) -> {ty} {{")
    lines.append("    x")
    lines.append("}")
    lines.append("")

    lines.append("fn main() -> i32 {")
    lines.append(
        "    // Touch oracle tables so they are not dead under aggressive DCE"
    )
    lines.append(
        "    // once V0-B lands (today the whole file fails at E218 on types)."
    )
    if rows:
        first = rows[0]["id"]
        lines.append(f"    let _oracle_anchor = ORACLE_{first}_EXPECTED[0]")
        lines.append(f"    let _via_anchor = ORACLE_{first}_VIA_F64[0]")

    lines.append("")
    lines.append(
        "    // --- Source literals from MPFR corpus (embeddable spellings) ---"
    )
    for i, r in enumerate(embedded_src):
        lit = r["source_literal"]
        rid = r["id"]
        dr = "DR" if r.get("double_rounds_differs") else "ok"
        lines.append(
            f"    // {rid} [{r['family']}] double_rounds_differs="
            f"{bool(r.get('double_rounds_differs'))} tag={dr}"
        )
        # Bind with explicit type — the V0-B surface under test.
        lines.append(f"    let v_{i}: {ty} = {lit}")
        lines.append(f"    let _id_{i} = identity_{ty}(v_{i})")

    lines.append("")
    lines.append(
        "    // Unary-minus corpus rows cannot be spelled as source literals"
    )
    lines.append(
        "    // (Sounio has no unary minus). Oracle limb tables above still"
    )
    lines.append(
        "    // carry expected/via_f64 for those ids — payload path only."
    )
    for r in limb_only:
        lines.append(
            f"    // LIMB_ONLY {r['id']} source={r['source_literal']!r} "
            f"family={r['family']} double_rounds_differs="
            f"{bool(r.get('double_rounds_differs'))}"
        )

    lines.append("    0")
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines))

    dr_embedded = [r for r in embedded_src if r.get("double_rounds_differs")]
    dr_limb_only = [r for r in limb_only if r.get("double_rounds_differs")]
    return {
        "format": fmt,
        "out": str(out_path.relative_to(ROOT)),
        "corpus_rows": len(rows),
        "embedded_source": len(embedded_src),
        "limb_only_unary_minus": len(limb_only),
        "skipped_other": len(skipped_other),
        "double_rounds_total": sum(
            1 for r in rows if r.get("double_rounds_differs")
        ),
        "double_rounds_embedded_source": len(dr_embedded),
        "double_rounds_limb_only": len(dr_limb_only),
        "embedded_ids": [r["id"] for r in embedded_src],
        "double_round_embedded_ids": [r["id"] for r in dr_embedded],
        "limb_only_ids": [r["id"] for r in limb_only],
        "embedded_literals": [r["source_literal"] for r in embedded_src],
        "double_round_literals": [r["source_literal"] for r in dr_embedded],
    }


def main() -> int:
    f128 = load_rows("literal_boundary_f128.jsonl")
    f256 = load_rows("literal_boundary_f256.jsonl")

    reports = [
        emit_probe(
            fmt="f128",
            rows=f128,
            out_path=ROOT / "tests/run-pass/f128_v0b_literal_smoke.sio",
            title="binary128 source literals + MPFR expected limb oracles",
        ),
        emit_probe(
            fmt="f256",
            rows=f256,
            out_path=ROOT / "tests/run-pass/f256_v0b_literal_forms.sio",
            title="binary256 source literals + MPFR expected limb oracles",
        ),
    ]

    report_path = VEC / "V0B_PROBE_CONSUMPTION.json"
    report_path.write_text(json.dumps(reports, indent=2) + "\n")
    print(json.dumps(reports, indent=2))
    print(f"wrote {report_path.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
