#!/usr/bin/env bash
# Worker for SAN large architecture training on a Slurm gpu-orangefs node.
# Called by the sbatch submission generated by submit.sh.
set -euo pipefail

PAYLOAD_DIR="${SAN_LARGE_PAYLOAD_DIR:-/orangefs/training/sounio/san-large-source}"
DATASET="${SAN_LARGE_DATASET:-cifar10}"
if [[ "$DATASET" == "cifar100" ]]; then
  DATA_SRC="${SAN_LARGE_DATA_SRC:-/orangefs/training/sounio/datasets/cifar-100-python}"
  DATA_DIR_NAME="cifar-100-python"
else
  DATA_SRC="${SAN_LARGE_DATA_SRC:-/orangefs/training/sounio/datasets/cifar-10-batches-py}"
  DATA_DIR_NAME="cifar-10-batches-py"
fi
OUT_ROOT="${SAN_LARGE_OUT:-/orangefs/training/sounio/kimi-runs/san-large-gpu}"
LEG="${SAN_LARGE_ONLY:-resnet50}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)-$(hostname)}"
OUT_DIR="$OUT_ROOT/$RUN_ID"

mkdir -p "$OUT_DIR"
TMPDIR=$(mktemp -d /tmp/san-large-gpu.XXXXXX)
trap 'rm -rf "$TMPDIR"' EXIT

mkdir -p "$TMPDIR/work"
cp "$PAYLOAD_DIR/suffering_aware_large_architecture.py" "$TMPDIR/work/"
cp -r "$DATA_SRC" "$TMPDIR/work/$DATA_DIR_NAME"
if [[ -f "$PAYLOAD_DIR/corpus_snapshot_v2000.npz" ]]; then
  cp "$PAYLOAD_DIR/corpus_snapshot_v2000.npz" "$TMPDIR/work/"
  export SAN_LARGE_CORPUS="$TMPDIR/work/corpus_snapshot_v2000.npz"
fi
cd "$TMPDIR/work"

export PYTHONUNBUFFERED=1
export LD_LIBRARY_PATH="/host-nvidia:${LD_LIBRARY_PATH:-}"

# Ensure torch + vision + tqdm are available. Some worker images lack pip or
# a CUDA torch; bootstrap into a temp user base when needed.
PYUSR_TMP="$(mktemp -d /tmp/san-large-gpu-pyusr.XXXXXX)"
export PYTHONUSERBASE="$PYUSR_TMP"
export PATH="$PYUSR_TMP/bin:${PATH:-}"
export PYTHONPATH="$(python3 -c 'import site; print(site.getusersitepackages())' 2>/dev/null):${PYTHONPATH:-}"

if ! python3 -m pip --version >/dev/null 2>&1; then
  echo "[worker] bootstrapping pip..."
  python3 - "$TMPDIR/get-pip.py" <<'PY'
import pathlib, ssl, sys, urllib.request
target = pathlib.Path(sys.argv[1])
context = ssl._create_unverified_context()
with urllib.request.urlopen("https://bootstrap.pypa.io/get-pip.py", context=context) as response:
    target.write_bytes(response.read())
PY
  python3 "$TMPDIR/get-pip.py" --user --break-system-packages >/dev/null
fi

if ! python3 -c "import torch" >/dev/null 2>&1; then
  echo "[worker] installing torch..."
  python3 -m pip install --user --no-cache-dir --break-system-packages \
    --trusted-host download.pytorch.org \
    torch==2.6.0 --index-url https://download.pytorch.org/whl/cu124 >/dev/null
fi
if ! python3 -c "import torchvision, tqdm" >/dev/null 2>&1; then
  echo "[worker] installing torchvision + tqdm..."
  python3 -m pip install --user --no-cache-dir --break-system-packages \
    torchvision tqdm >/dev/null
fi

if python3 -c "import torch; print(torch.cuda.is_available())" 2>/dev/null | grep -q True; then
  echo "[worker] CUDA available: $(python3 -c 'import torch; print(torch.cuda.get_device_name(0))' 2>/dev/null)"
else
  echo "[worker] WARNING: CUDA not available; falling back to CPU"
fi

export SAN_LARGE_DEVICE=cuda
export SAN_LARGE_ONLY="$LEG"
export SAN_LARGE_DATASET="$DATASET"
export SAN_LARGE_DATA="$TMPDIR/work/$DATA_DIR_NAME"
export SAN_LARGE_THREADS="${SAN_LARGE_THREADS:-8}"
export SAN_LARGE_DELTA_RESNET="${SAN_LARGE_DELTA_RESNET:-0.55}"
export SAN_LARGE_DELTA_VIT="${SAN_LARGE_DELTA_VIT:-0.45}"
export SAN_LARGE_DELTA_GPT="${SAN_LARGE_DELTA_GPT:-0.31}"
export SAN_LARGE_TAU_RESNET="${SAN_LARGE_TAU_RESNET:-0.34}"
export SAN_LARGE_TAU_VIT="${SAN_LARGE_TAU_VIT:-0.251}"
export SAN_LARGE_TAU_GPT="${SAN_LARGE_TAU_GPT:-0.165}"

LOG="$OUT_DIR/${LEG}.log"
python3 suffering_aware_large_architecture.py 2>&1 | tee "$LOG"

# Copy any artifacts written under /tmp/artifacts back to OrangeFS.
# The script computes REPO_ROOT as dirname^3 of its own path; since the
# payload is extracted under /tmp/.../work, artifacts land at /tmp/artifacts.
if [[ -d "/tmp/artifacts/san_large" ]]; then
  cp -r "/tmp/artifacts/san_large" "$OUT_DIR/" 2>/dev/null || true
fi

echo "DONE $RUN_ID" > "$OUT_DIR/status.txt"
echo "[worker] artifacts: $OUT_DIR"
