#!/usr/bin/env bash
# Worker for SAN large architecture training on a Slurm gpu-orangefs node.
# Called by the sbatch submission generated by submit.sh.
set -euo pipefail

PAYLOAD_DIR="${SAN_LARGE_PAYLOAD_DIR:-/orangefs/training/sounio/san-large-source}"
DATA_SRC="${SAN_LARGE_DATA_SRC:-/orangefs/training/sounio/datasets/cifar-10-batches-py}"
OUT_ROOT="${SAN_LARGE_OUT:-/orangefs/training/sounio/kimi-runs/san-large-gpu}"
LEG="${SAN_LARGE_ONLY:-resnet50}"
RUN_ID="${RUN_ID:-$(date +%Y%m%d-%H%M%S)-$(hostname)}"
OUT_DIR="$OUT_ROOT/$RUN_ID"

mkdir -p "$OUT_DIR"
TMPDIR=$(mktemp -d /tmp/san-large-gpu.XXXXXX)
trap 'rm -rf "$TMPDIR"' EXIT

mkdir -p "$TMPDIR/work"
cp "$PAYLOAD_DIR/suffering_aware_large_architecture.py" "$TMPDIR/work/"
cp -r "$DATA_SRC" "$TMPDIR/work/cifar-10-batches-py"
cd "$TMPDIR/work"

export PYTHONUNBUFFERED=1
export LD_LIBRARY_PATH="/host-nvidia:${LD_LIBRARY_PATH:-}"

# Ensure torch + vision + tqdm are available. The worker image may already
# have them; if not, install into a temp user base.
if ! python3 -c "import torch" >/dev/null 2>&1; then
  echo "[worker] installing torch..."
  python3 -m pip install --user --no-cache-dir --break-system-packages \
    --trusted-host download.pytorch.org \
    torch==2.6.0 --index-url https://download.pytorch.org/whl/cu124 >/dev/null
fi
if ! python3 -c "import torchvision, tqdm" >/dev/null 2>&1; then
  echo "[worker] installing torchvision + tqdm..."
  python3 -m pip install --user --no-cache-dir --break-system-packages \
    torchvision tqdm >/dev/null
fi

if python3 -c "import torch; print(torch.cuda.is_available())" 2>/dev/null | grep -q True; then
  echo "[worker] CUDA available: $(python3 -c 'import torch; print(torch.cuda.get_device_name(0))' 2>/dev/null)"
else
  echo "[worker] WARNING: CUDA not available; falling back to CPU"
fi

export SAN_LARGE_DEVICE=cuda
export SAN_LARGE_ONLY="$LEG"
export SAN_LARGE_DATA="$TMPDIR/work/cifar-10-batches-py"
export SAN_LARGE_THREADS="${SAN_LARGE_THREADS:-8}"

LOG="$OUT_DIR/${LEG}.log"
python3 suffering_aware_large_architecture.py 2>&1 | tee "$LOG"

# Copy any artifacts written under /tmp/artifacts back to OrangeFS.
# The script computes REPO_ROOT as dirname^3 of its own path; since the
# payload is extracted under /tmp/.../work, artifacts land at /tmp/artifacts.
if [[ -d "/tmp/artifacts/san_large" ]]; then
  cp -r "/tmp/artifacts/san_large" "$OUT_DIR/" 2>/dev/null || true
fi

echo "DONE $RUN_ID" > "$OUT_DIR/status.txt"
echo "[worker] artifacts: $OUT_DIR"
