#!/usr/bin/env python3
"""
Functor F — the E8 capstone: phi is the octonion form-datum of the whole exceptional tower.

Honest about E8's structure: E8 is NOT like E6/E7. It has no small (minuscule) representation
-- its smallest nontrivial irrep is the 248-dim adjoint -- so there is no small-rep polynomial
invariant to build phi against, the way the E6 cubic (on the 27) and the E7 quartic (on the 56)
were. This rung therefore does NOT construct an E8 invariant; it establishes the structural
capstone with a concrete verified anchor and honest bounds.

  G1  dim der(O) = 14 = g2 (VERIFIED by solving the derivation condition): the base summand
      of e8's Tits construction is exactly Aut(O)'s Lie algebra -- functor-F's own symmetry.
  G2  Tits / Freudenthal magic square: e8 = der(O) + (Im(O) tensor J3(O)_0) + der(J3(O))
      = 14 + 7*26 + 52 = 248 = dim E8. The octonionic tower G2(14) < F4(52) < E6(78) <
      E7(133) < E8(248) is built from O and Jordan algebras over O.
  G3  psi = *phi (recap of the E7 result): the octonion G2 form-content is generated by
      {metric g, phi}. So whatever octonion form-data the tower's constructions use, it is
      {g, phi}.
  G4  CAPSTONE: E8 has no minuscule rep => no small-rep polynomial invariant => the clean
      'phi = octonion cross-term of the invariant' phenomenon (E6 cubic) TOPS OUT below E8.
      But E8 is built FROM the octonions (G1/G2), whose form-content is {g, phi} (G3), so phi
      is the octonion FORM-DATUM of the whole tower G2->E8; its clean invariant-cross-term
      home is E6.

Verdict E8_NO_SMALL_REP_PHI_IS_TOWER_FORM_DATUM. Honest structural capstone (der(O)=14
verified; magic-square dims; psi=*phi); NO E8 construction, NO new invariant, NO semantic
claim (D3-quarantined). Self-contained (octonions).
"""
import numpy as np

np.seterr(all='ignore')
TOL = 1e-9


def cds(a, b, bits=3):
    s = 1
    while bits > 0:
        if a == 0 or b == 0:
            return s
        if bits == 1:
            return -s
        h = 1 << (bits - 1)
        ah, bh = a >= h, b >= h
        al, bl = a & (h - 1), b & (h - 1)
        if not ah and not bh:
            a, b = al, bl
        elif not ah and bh:
            a, b = bl, al
        elif ah and not bh:
            a, b, s = ((al, 0, s) if bl == 0 else (al, bl, -s))
        else:
            a, b, s = ((0, al, -s) if bl == 0 else (bl, al, s))
        bits -= 1
    return s


def o(A, B):
    C = np.zeros(8)
    for i in range(8):
        if A[i] == 0.0:
            continue
        for j in range(8):
            if B[j] == 0.0:
                continue
            C[i ^ j] += cds(i, j) * A[i] * B[j]
    return C


def e(i):
    v = np.zeros(8); v[i] = 1.0; return v


def main():
    print("=" * 70)
    print("FUNCTOR F — E8 capstone: phi is the octonion form-datum of the whole tower")
    print("=" * 70)
    core = all(np.allclose(o(e(i), e(i)), -e(0)) for i in range(1, 8))
    print(f"G0_CORE_AUDIT octonion sq=-1 {'PASS' if core else 'FAIL'}")

    # G1 — dim der(O) = 14 = g2, by solving D(e_i e_j) = D(e_i)e_j + e_i D(e_j)
    rows = []
    for i in range(8):
        for j in range(8):
            eiej = o(e(i), e(j))
            for out in range(8):
                row = np.zeros((8, 8))
                for k in range(8):
                    row[out, k] += eiej[k]
                for a in range(8):
                    row[a, i] -= o(e(a), e(j))[out]
                for b in range(8):
                    row[b, j] -= o(e(i), e(b))[out]
                rows.append(row.ravel())
    dim_der = 64 - np.linalg.matrix_rank(np.array(rows), tol=TOL)
    g1 = (dim_der == 14)
    print(f"G1_DER_O_IS_G2 dim der(O) = {dim_der} (= g2 = Aut(O) tangent, e8's base summand) "
          f"{'PASS' if g1 else 'FAIL'}")

    # G2 — Tits / magic-square dimensions
    g2d, ImO, J0, f4 = 14, 7, 26, 52
    e8d = g2d + ImO * J0 + f4
    dims = {'G2': 14, 'F4': 52, 'E6': 78, 'E7': 133, 'E8': 248}
    g2 = (e8d == 248 and dims['E8'] == 248)
    print(f"G2_TITS_DIMS e8 = der(O)({g2d}) + Im(O)xJ3(O)_0 ({ImO}x{J0}={ImO*J0}) + f4({f4}) = {e8d} "
          f"(=dim E8); tower {dims} {'PASS' if g2 else 'FAIL'}")

    # G3 — psi = *phi (recap): octonion G2 form-content is {g, phi}
    import itertools
    phi = np.zeros((8, 8, 8)); psi = np.zeros((8, 8, 8, 8))
    for a in range(1, 8):
        for b in range(1, 8):
            for c in range(1, 8):
                phi[a, b, c] = float(np.dot(o(e(a), e(b)), e(c)))
                A = o(o(e(a), e(b)), e(c)) - o(e(a), o(e(b), e(c)))
                for d in range(1, 8):
                    psi[a, b, c, d] = -0.5 * float(np.dot(A, e(d)))

    def lev(p):
        s = 1
        for i in range(len(p)):
            for j in range(i + 1, len(p)):
                if p[i] > p[j]:
                    s = -s
        return s
    idx = list(range(1, 8)); star = np.zeros((8, 8, 8, 8))
    for a, b, c, d in itertools.permutations(idx, 4):
        rem = [x for x in idx if x not in (a, b, c, d)]
        star[a, b, c, d] = sum(lev((a, b, c, d, ee, ff, gg)) * phi[ee, ff, gg]
                               for ee, ff, gg in itertools.permutations(rem, 3)) / 6.0
    g3 = np.max(np.abs(psi - star)) < 1e-9
    print(f"G3_FORM_CONTENT psi==*phi (dev {np.max(np.abs(psi - star)):.1e}) => octonion G2 form-content "
          f"generated by {{g, phi}} {'PASS' if g3 else 'FAIL'}")

    # G4 — capstone (structural conclusion, bounded)
    g4 = g1 and g2 and g3
    print(f"G4_CAPSTONE E8 min nontrivial irrep = 248 (adjoint), no small rep => no small-rep invariant "
          f"=> clean phi=cross-term phenomenon tops out below E8; but E8 is octonion-built (Tits) with "
          f"form-content {{g,phi}} => phi is the tower's octonion form-datum {'PASS' if g4 else 'FAIL'}")

    print("=" * 70)
    if core and g1 and g2 and g3 and g4:
        print("FUNCTOR_F_E8_VERDICT E8_NO_SMALL_REP_PHI_IS_TOWER_FORM_DATUM")
        print("FUNCTOR_F_E8_NOTE E8 is structurally unlike E6/E7: no minuscule rep (smallest nontrivial = "
              "248 adjoint), so NO small-rep polynomial invariant to build phi against -- the clean "
              "'phi = octonion cross-term of the invariant' phenomenon (E6 cubic on the 27) TOPS OUT below "
              "E8. What persists: dim der(O)=14=g2 (verified, e8's Tits base summand); e8 = g2 + 7x26 + f4 "
              "= 248; psi=*phi so the octonion G2 form-content is {g,phi}; hence phi is the octonion "
              "FORM-DATUM of the whole tower G2<F4<E6<E7<E8, with its clean invariant-cross-term home at E6. "
              "NO E8 construction, NO new invariant, NO semantic claim (D3-quarantined)")
        return 0
    print("FUNCTOR_F_E8_VERDICT INCOMPLETE")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
