#!/usr/bin/env python3
"""Self-falsifying compilation, rung R21 — the lemma, proved.

Spec: docs/research/self_falsifying_compilation_line_r21_2026-07-28.md

R16 measured that the count-preserving flip preserves the classification and
inferred it without proof. R19 derived the locality half and reduced the rest to
one statement: why is Llo |-> {h, h ^ Llo} equivariant with the block structure?

It is, and the reason is two lines of bit arithmetic once the right objects are
in view -- objects that were unavailable until R20 restored them.

THE ARGUMENT.

(1) R19-L3, derived: in the Z2 signed double-cover presentation (each
    annihilation graph is the double cover of a "lo-graph" (R, eps); see
    cd_tower_collapse_isomorphism.py), the flip does exactly one thing: it adds
    the edge {h, h ^ Llo} to the lo-graph with eps = -1. Note h XOR (h ^ Llo)
    = Llo: the added edge is the unique edge whose endpoint-XOR is the fiber's
    own label, anchored at h.

(2) The blocks are generated by exactly two relations (both prior in-repo
    results, and re-verified here against the measured spectra):
      * the frozen PSL(2,7) = GL(3,2) orbit action, and
      * the parity-collapse map Phi for even-weight seams.

(3) BOTH ARE F2-LINEAR AND FIX h.
      * Orbit action: A = g (+) Id -- GL(3,2) on the octonion bits {0,1,2},
        IDENTITY on every seam bit {3..n-2}. And h = 2^(n-2) IS a seam bit.
      * Collapse: tau = swap(bit 0, bit lsb(Y)), a coordinate transposition,
        hence linear. And lsb(Y) != n-2, because Y has EVEN weight with bits
        confined to {3..n-2}: lsb(Y) = n-2 would force Y = 2^(n-2), of weight 1,
        which is odd. So tau fixes h.

(4) Hence for any g relating same-block fibers: g linear, g(h) = h,
    g(Llo) = Llo' give
        g({h, h ^ Llo}) = {g(h), g(h) ^ g(Llo)} = {h, h ^ Llo'},
    the added edge of the image fiber. So g, already an isomorphism of the
    unperturbed graphs, is an isomorphism of the PERTURBED ones.

Therefore same-block fibers stay same-block. R16's inference is a theorem.

CLAUSES:
  V1_H_IS_A_SEAM_BIT        h = 2^(n-2) lies in {8,...,2^(n-2)}, arithmetic.
  V2_TAU_FIXES_H            lsb(Y) != n-2 for every even-weight seam, and Phi
                            carries the added edge to the added edge, checked
                            against the restored Phi at n = 6, 7, 8.
  V3_BLOCKS_ARE_ORBITS_PLUS_COLLAPSE
                            the measured spectrum-blocks are exactly Fano
                            orbits, seam fixed points, and orbits with
                            EVEN-weight seams collapsed in -- verified
                            independently of the orbit contract, which cannot
                            run in this tree (R20: its oracle was never
                            committed).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]


def _load(name, rel):
    sp = importlib.util.spec_from_file_location(name, REPO / rel)
    m = importlib.util.module_from_spec(sp)
    sp.loader.exec_module(m)
    return m


r15 = _load("r15", "scripts/research/self_falsifying_compilation_line_r15_contract.py")
phi = _load("phi", "scripts/research/cd_tower_collapse_isomorphism.py")


def main() -> int:
    print("R21 — the lemma, proved")
    print("=" * 72)

    # ---- V1 -----------------------------------------------------------------
    ok1 = True
    print("V1_H_IS_A_SEAM_BIT   (seam bits are {3..n-2}; the orbit action is the")
    print("                      identity on all of them)")
    for n in range(5, 13):
        h = 1 << (n - 2)
        good = (h & ~7) != 0 and (h.bit_length() - 1) <= n - 2
        ok1 &= good
        if n <= 8:
            print(f"    n={n:2}: h = 2^(n-2) = {h:4} = bit {h.bit_length()-1}, "
                  f"seam bit: {'yes' if good else 'NO'}")
    print(f"    ... holds for n = 5..12")
    print(f"V1_H_IS_A_SEAM_BIT {'PASS' if ok1 else 'FAIL'}")
    print()

    # ---- V2 -----------------------------------------------------------------
    print("V2_TAU_FIXES_H   (even weight forbids lsb(Y) = n-2, so tau(h) = h)")
    ok2 = True
    total = 0
    for n in (6, 7, 8):
        H = 1 << (n - 1)
        h = H // 2
        for Y in phi.even_weight_seams(n):
            j = (Y & -Y).bit_length() - 1
            tau = lambda x: phi._swap0j(x, j)
            # the parity argument: lsb = n-2 would force Y = 2^(n-2), odd weight
            parity_ok = j != n - 2
            fixes = tau(h) == h
            Ls, Lf = Y, (Y & (Y - 1)) | 1
            carried = {tau(h), tau(h ^ Ls)} == {h, h ^ Lf}
            ok2 &= parity_ok and fixes and carried
            total += 1
        print(f"    n={n}: {len(phi.even_weight_seams(n))} even-weight seams, "
              f"lsb never n-2, tau(h)=h, added edge carried")
    print(f"    {total} collapse pairs checked against the restored Phi")
    print(f"V2_TAU_FIXES_H {'PASS' if ok2 else 'FAIL'}")
    print()

    # ---- V3 -----------------------------------------------------------------
    print("V3_BLOCKS_ARE_ORBITS_PLUS_COLLAPSE")
    ok3 = True
    for n in (5, 6, 7):
        H = 1 << (n - 1)
        by = {}
        for L in range(1, H):
            by.setdefault(r15.fiber_spectrum(n, L, None, n), []).append(L)
        shapes = []
        for b in sorted(sorted(v) for v in by.values()):
            seams = {x & ~7 for x in b}
            lows = {x & 7 for x in b}
            collapsed = [x for x in b if (x & 7) == 0]
            if len(b) == 1 and lows == {0}:
                shapes.append("seam")
            elif len(b) == 7 and lows == set(range(1, 8)):
                shapes.append("orbit")
            elif collapsed and lows >= set(range(1, 8)):
                # every collapsed seam must have EVEN seam-weight
                for y in collapsed:
                    if bin(y >> 3).count("1") % 2 != 0:
                        ok3 = False
                shapes.append(f"orbit+{len(collapsed)}collapse")
            else:
                ok3 = False
                shapes.append("UNEXPLAINED")
        from collections import Counter
        print(f"    n={n}: {dict(Counter(shapes))}")
    print("    Verified independently of the orbit contract, which cannot run")
    print("    here: R20 found its oracle was never committed to any branch.")
    print(f"V3_BLOCKS_ARE_ORBITS_PLUS_COLLAPSE {'PASS' if ok3 else 'FAIL'}")
    print()

    ok = ok1 and ok2 and ok3
    verdict = ("EQUIVARIANCE_PROVED__R16_INFERENCE_IS_A_THEOREM"
               if ok else "INCONCLUSIVE")
    print("-" * 72)
    print("Both relations that generate the blocks are F2-linear and fix h, so")
    print("each carries the added edge {h, h^Llo} to the added edge of the image")
    print("fiber. An isomorphism of the unperturbed graphs is therefore an")
    print("isomorphism of the perturbed ones, and the partition is preserved.")
    print()
    print(f"SELF_FALSIFYING_R21_VERDICT {verdict}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
