#!/usr/bin/env bash
# examples/erdos/gen_lean_sat_reflect.sh
#
# "souc_check" codegen — file-loaded-style reflection. Turns a souc_sat graph
# colouring UNSAT certificate (DIMACS CNF + its drat-trim LRAT) into a Lean 4
# file that proves, with NO Mathlib:
#
#   <name>_unsat          : <name>_cnf.Unsat            (Lean core verified LRAT checker)
#   <name>_not_colourable : ¬ proper k-colouring (Fin)  (SounioSatColouring bridge)
#
# Unlike gen_lean_sat.sh (which embeds the certificate as an `Array IntAction`
# term and hits a term-size wall past a few thousand actions), this embeds the
# LRAT as a single *String literal* and parses it with `SounioSatReflect.parseLRAT`
# inside the `native_decide` computation. The string atom elaborates in ms, and
# parse+check run as compiled native code — scaling to 100 k+ actions (G₅₂₉: ~11 s).
#
# The parser is unverified but soundness-irrelevant (check_sound only trusts the
# verified checker's verdict on whatever actions it is fed).
#
# Two modes:
#   plain  : <cnf> <lrat> <out> <name> <Module> <n> <k> <edgefile>
#   SB-tri : <cnf> <lrat> <out> <name> <Module> <n> <4|5> <edgefile> <a> <b> <c>
#            (souc_sat triangle-precolour: vertices a,b,c fixed to colours 0,1,2;
#             requires a,b,c pairwise adjacent; yields an unconditional no-k-colouring
#             theorem via the matching WLOG leg in SounioSatColouringSB).
set -euo pipefail

CNF="$1"; LRAT="$2"; OUT="$3"; NAME="$4"; MODULE="$5"; N="$6"; K="$7"; EDGEFILE="$8"
TA="${9:-}"; TB="${10:-}"; TC="${11:-}"

[[ -s "$CNF"  ]] || { echo "error: missing/empty CNF  $CNF"  >&2; exit 1; }
[[ -s "$LRAT" ]] || { echo "error: missing/empty LRAT $LRAT" >&2; exit 1; }
[[ -s "$EDGEFILE" ]] || { echo "error: missing/empty edge file $EDGEFILE" >&2; exit 1; }

NCLS=$(awk '/^p cnf/ {print $4; exit}' "$CNF")
SBMODE=0
SB_CNF_FUNC=""
SB_NOT_THEOREM=""
if [[ -n "$TA" ]]; then
  case "$K" in
    4)
      SB_CNF_FUNC="colourCNFsb"
      SB_NOT_THEOREM="not_colourable_of_unsat_tri"
      ;;
    5)
      SB_CNF_FUNC="colourCNFsb5"
      SB_NOT_THEOREM="not_colourable5_of_unsat_tri"
      ;;
    *)
      echo "error: SB-triangle mode requires k=4 or k=5" >&2
      exit 1
      ;;
  esac
  SBMODE=1
fi

RENUM="$(mktemp)"
trap 'rm -f "$RENUM"' EXIT
# renumber LRAT addition ids to contiguous M+1,M+2,… and remap hints/deletions
awk -v M="$NCLS" '
  /^[ \t]*$/ {next}
  function remap(old,  nw){nw=map[old]; return (nw=="")?old:nw}
  {
    if ($2=="d"){ printf "%s d", remap($1); for(i=3;i<=NF;i++){if($i+0==0)break; printf " %s", remap($i+0)} printf " 0\n"; next }
    oldid=$1+0; newid=M+(++ac); map[oldid]=newid
    printf "%s", newid
    i=2; while(i<=NF && $i+0!=0){printf " %s",$i; i++}; printf " 0"; i++
    while(i<=NF && $i+0!=0){printf " %s", remap($i+0); i++}; printf " 0\n"
  }
' "$LRAT" > "$RENUM"

NEDGES=$(awk '/^e /' "$EDGEFILE" | wc -l)

{
cat <<EOF
/-
$MODULE — autogenerated by examples/erdos/gen_lean_sat_reflect.sh. DO NOT EDIT BY HAND.

File-loaded-style reflection ("souc_check") of a souc_sat (Sounio CDCL) graph
colouring refutation, Mathlib-free:

  * \`${NAME}_unsat\`          — the colouring CNF is UNSAT, machine-checked by Lean
    core's verified LRAT checker on souc_sat's certificate (embedded as a String
    literal, parsed + checked under native_decide — no term-size wall);
  * \`${NAME}_not_colourable\` — therefore no proper $K-colouring exists.

  source CNF : $(basename "$CNF")  ($(awk '/^p cnf/{print $3" vars"; exit}' "$CNF"), $NCLS clauses)
  source LRAT: $(basename "$LRAT")  ($(wc -l < "$RENUM") actions, renumbered contiguous)
  graph      : n=$N, k=$K, edges=$NEDGES (from $(basename "$EDGEFILE"))$( [[ $SBMODE == 1 ]] && echo ", SB triangle $TA,$TB,$TC → 0,1,2" )
-/
import SounioSatColouringBridge
import SounioSatReflect
EOF
[[ $SBMODE == 1 ]] && echo "import SounioSatColouringSB"
cat <<EOF
open Std.Sat
open Std.Tactic.BVDecide.LRAT
open SounioSatColouring
open SounioSatReflect
EOF
[[ $SBMODE == 1 ]] && echo "open SounioSatColouringSB"
cat <<EOF

set_option maxHeartbeats 0
set_option maxRecDepth 1000000

/-- Edge list (0-based), in souc_sat's emission order. -/
def ${NAME}_edges : List (Nat × Nat) := [
EOF

awk '/^e /{print "  (" ($2-1) ", " ($3-1) "),"}' "$EDGEFILE"

if [[ $SBMODE == 1 ]]; then
cat <<EOF
]

/-- Colouring CNF + souc_sat triangle-precolour SB units ($TA,$TB,$TC → 0,1,2). -/
def ${NAME}_cnf : CNF Nat := $SB_CNF_FUNC $TA $TB $TC $N ${NAME}_edges

def ${NAME}_lrat : String := "
EOF
else
cat <<EOF
]

/-- The canonical colouring CNF (matches souc_sat's emitter). -/
def ${NAME}_cnf : CNF Nat := colourCNF $N $K ${NAME}_edges

def ${NAME}_lrat : String := "
EOF
fi

cat "$RENUM"

cat <<EOF
"

/-- souc_sat's LRAT certificate re-checked inside Lean (reflective, file-loaded). -/
theorem ${NAME}_check : check (parseLRAT ${NAME}_lrat) ${NAME}_cnf = true := by native_decide

/-- Hence the colouring CNF is genuinely UNSAT. -/
theorem ${NAME}_unsat : ${NAME}_cnf.Unsat := check_sound _ ${NAME}_cnf ${NAME}_check
EOF

if [[ $SBMODE == 1 ]]; then
cat <<EOF

/-- **Finite graph lower bound.** Triangle $TA,$TB,$TC is pairwise adjacent, so its
precolour is WLOG; hence no proper $K-colouring \`Fin $N → Fin $K\` exists. -/
theorem ${NAME}_not_colourable :
    ¬ ∃ f : Fin $N → Fin $K,
        ∀ e ∈ ${NAME}_edges, ∀ (h1 : e.1 < $N) (h2 : e.2 < $N),
          f ⟨e.1, h1⟩ ≠ f ⟨e.2, h2⟩ :=
  $SB_NOT_THEOREM
    (by decide) (by decide) (by decide)
    (by native_decide) (by native_decide) (by native_decide)
    (by native_decide) ${NAME}_unsat
EOF
else
cat <<EOF

/-- **Finite graph lower bound.** No proper $K-colouring \`Fin $N → Fin $K\` exists. -/
theorem ${NAME}_not_colourable :
    ¬ ∃ c : Fin $N → Fin $K,
        ∀ e ∈ ${NAME}_edges, ∀ (h1 : e.1 < $N) (h2 : e.2 < $N), c ⟨e.1, h1⟩ ≠ c ⟨e.2, h2⟩ :=
  not_colourable_of_unsat (by decide) (by native_decide) ${NAME}_unsat
EOF
fi

cat <<EOF

#print axioms ${NAME}_unsat
#print axioms ${NAME}_not_colourable
EOF
} > "$OUT"

echo "wrote $OUT  ($N verts, k=$K, $NEDGES edges, $(wc -l < "$RENUM") LRAT actions$( [[ $SBMODE == 1 ]] && echo ", SB triangle $TA,$TB,$TC" ))"
