#!/usr/bin/env bash
# Regenerate formal/lean4/SounioDeGreyUnitDistance.lean — the GEOMETRY LEG of
# chi(R^2) >= 5, machine-checked in Lean 4.
#
# The 529 vertex coordinates and 2670 edges are EMITTED by the Sounio source of
# truth (examples/erdos/degrey_geometry.sio, which parses data/degrey_529.vtx),
# wrapped by a static exact-field kernel + theorem, and re-checked by native_decide.
#
# Usage:  bash examples/erdos/gen_lean_geometry.sh [--check]
set -euo pipefail
cd "$(dirname "$0")/../.."          # repo root
ROOT="$PWD"
SOUC="${SOUNIO_SOUC_BIN:-$ROOT/artifacts/self-hosted/souc-self-hosted-x86_64}"
OUT="formal/lean4/SounioDeGreyUnitDistance.lean"
TMP="$(mktemp -d)"

# 1. compile + run the Sounio emitter -> data section
"$SOUC" examples/erdos/degrey_geometry.sio "$TMP/geo.elf" >/dev/null
chmod +x "$TMP/geo.elf"
"$TMP/geo.elf" lean > "$TMP/data.lean"

# 2. static kernel (head) + theorem (foot)
cat > "$TMP/head.lean" <<'LEAN'
set_option maxHeartbeats 0
set_option maxRecDepth 100000

/-
  SounioDeGreyUnitDistance.lean   (AUTO-GENERATED by examples/erdos/gen_lean_geometry.sh —
  do not hand-edit the data section).

  GEOMETRY LEG of chi(R^2) >= 5.  Every edge of Heule's 529-vertex de Grey core
  (G_529, github.com/marijnheule/CNP-SAT) has squared Euclidean distance EXACTLY 1,
  over the exact field Q(sqrt3,sqrt5,sqrt7,sqrt11) as integer 16-tuples with a
  common denominator (basis b_mask = sqrt of product of primes selected by mask
  bits 0=3,1=5,2=7,3=11; multiplication is XOR on masks with rational coefficient
  = product of shared primes).  Coordinates parsed by the Sounio source of truth
  degrey_geometry.sio; Lean re-checks all 2670 edges by native_decide in exact
  bignum Int (no floating point, no overflow).

  With the SAT leg (souc_sat refutes the 4-colouring CNF; drat-trim/LRAT
  s VERIFIED): G_529 is a unit-distance graph that is not 4-colourable, so
  chi(R^2) >= 5.
-/

namespace DeGrey529

abbrev QF := List Int × Int      -- (16 coeffs over basis b_mask, positive denominator)
abbrev VPair := Nat × Nat

def bcoeff (m : Nat) : Int :=
  (if m % 2 = 1 then 3 else 1)
  * (if (m / 2) % 2 = 1 then 5 else 1)
  * (if (m / 4) % 2 = 1 then 7 else 1)
  * (if (m / 8) % 2 = 1 then 11 else 1)

def gi (l : List Int) (i : Nat) : Int := l.getD i 0

def qsub (x y : QF) : QF :=
  ((List.range 16).map (fun i => gi x.1 i * y.2 - gi y.1 i * x.2), x.2 * y.2)

def qadd (x y : QF) : QF :=
  ((List.range 16).map (fun i => gi x.1 i * y.2 + gi y.1 i * x.2), x.2 * y.2)

def qmul (x y : QF) : QF :=
  ((List.range 16).map (fun idx =>
      (List.range 16).foldl (fun acc i =>
          acc + gi x.1 i * gi y.1 (Nat.xor i idx) * bcoeff (Nat.land i (Nat.xor i idx))) 0),
   x.2 * y.2)

LEAN

cat > "$TMP/foot.lean" <<'LEAN'

-- value == 1 iff rational part equals the denominator and all surd components
-- vanish (basis monomials are linearly independent over Q).
def isOne (x : QF) : Bool :=
  (List.range 16).all (fun i => if i = 0 then gi x.1 0 == x.2 else gi x.1 i == 0)

def dist2 (a b : Nat) : QF :=
  let dx := qsub (X.getD a ([], 1)) (X.getD b ([], 1))
  let dy := qsub (Y.getD a ([], 1)) (Y.getD b ([], 1))
  qadd (qmul dx dx) (qmul dy dy)

def edgeUnit (e : VPair) : Bool := isOne (dist2 e.1 e.2)

/-- Shape sanity: 529 vertices, 2670 edges. -/
theorem g529_vertex_count : X.size = 529 ∧ Y.size = 529 := by native_decide
theorem g529_edge_count   : edges.size = 2670 := by native_decide

/-- GEOMETRY LEG (exact algebraic identity, no floats): every one of the 2670 edges
    of G_529 has squared distance exactly 1 in the field Q(sqrt3,sqrt5,sqrt7,sqrt11)
    (16-tuple model). Under the standard embedding of this field into R
    (b_mask ↦ the corresponding real radical) this is the Euclidean squared
    distance, so G_529 is a unit-distance graph. SCOPE (math-review, Grok 4.1):
    the R-embedding, and the XOR ring-homomorphism (qmul/bcoeff) and Q-linear-
    independence (isOne) facts, are standard true multiquadratic-field properties
    discharged here by construction/native_decide, not yet re-proved as Lean lemmas. -/
theorem g529_all_edges_unit_distance : edges.all edgeUnit = true := by native_decide

end DeGrey529
LEAN

# 3. assemble
cat "$TMP/head.lean" "$TMP/data.lean" "$TMP/foot.lean" > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"

# 4. optional verification (heavy: ~3 min, big literals + native_decide)
if [[ "${1:-}" == "--check" ]]; then
  echo "checking with lean (this takes a few minutes)..."
  lean "$OUT" && echo "LEAN OK: g529_all_edges_unit_distance proved (native_decide)"
fi
rm -rf "$TMP"
