#!/usr/bin/env bash
# examples/erdos/gen_lean_sat.sh
#
# Codegen: turn a souc_sat graph-colouring UNSAT certificate (DIMACS CNF + its
# drat-trim LRAT) into a self-contained Lean 4 file that proves, end-to-end and
# with NO Mathlib:
#
#   <name>_unsat         : <name>_cnf.Unsat          -- via Lean core verified LRAT checker
#   <name>_not_colourable: ¬ ∃ proper k-colouring    -- via SounioSatColouring bridge
#
# The CNF is expressed as `SounioSatColouring.colourCNF n k edges` (the canonical
# colouring encoding), which is clause-for-clause identical to souc_sat's emitter,
# so the souc_sat LRAT validates against it directly (the LRAT checker treats each
# clause as a set, so intra-clause literal order is irrelevant). This lets the
# generic, scale-independent soundness bridge convert the reflective `Unsat` into
# a chromatic lower bound.
#
# LRAT id handling: Lean's DefaultFormula.insert *pushes* added clauses, so the
# verified checker needs contiguous addition ids. drat-trim ids may have gaps, so
# we renumber additions to M+1, M+2, … and remap every hint/deletion reference.
#
# Usage:
#   gen_lean_sat.sh <cnf> <lrat> <out.lean> <name> <ModuleName> <n> <k> [edgefile]
#     edgefile : DIMACS `e u v` edges (1-based). Omit for a complete graph K_n.
set -euo pipefail

CNF="$1"; LRAT="$2"; OUT="$3"; NAME="$4"; MODULE="$5"; N="$6"; K="$7"; EDGEFILE="${8:-}"

[[ -s "$CNF"  ]] || { echo "error: missing/empty CNF  $CNF"  >&2; exit 1; }
[[ -s "$LRAT" ]] || { echo "error: missing/empty LRAT $LRAT" >&2; exit 1; }

NVARS=$(awk '/^p cnf/ {print $3; exit}' "$CNF")
NCLS=$(awk '/^p cnf/ {print $4; exit}' "$CNF")

# --- edge list (0-based), in souc_sat's emission order ------------------------
edges_lean() {
  if [[ -n "$EDGEFILE" ]]; then
    awk '/^e /{print "  (" ($2-1) ", " ($3-1) ")," }' "$EDGEFILE"
  else
    awk -v n="$N" 'BEGIN{ for(a=0;a<n;a++)for(b=a+1;b<n;b++) print "  (" a ", " b ")," }'
  fi
}
NEDGES=$(edges_lean | wc -l)

{
cat <<EOF
/-
$MODULE — autogenerated by examples/erdos/gen_lean_sat.sh. DO NOT EDIT BY HAND.

End-to-end, Mathlib-free internalisation of a souc_sat (Sounio CDCL) graph
colouring refutation:

  * \`${NAME}_unsat\`          — the colouring CNF is UNSAT, machine-checked by
    Lean core's *formally verified* LRAT checker (\`check_sound\`, reflected by
    \`native_decide\`) on souc_sat's own LRAT certificate;
  * \`${NAME}_not_colourable\` — therefore the graph has no proper $K-colouring,
    via the scale-independent encoding-soundness bridge \`SounioSatColouring\`.

  source CNF : $(basename "$CNF")  ($NVARS vars, $NCLS clauses)
  source LRAT: $(basename "$LRAT")  (renumbered to contiguous ids)
  graph      : n=$N, k=$K, edges=$NEDGES $( [[ -n "$EDGEFILE" ]] && echo "(from $(basename "$EDGEFILE"))" || echo "(complete graph K_$N)")
-/
import SounioSatColouringBridge

open Std.Sat
open Std.Tactic.BVDecide.LRAT
open SounioSatColouring

set_option maxHeartbeats 0
set_option maxRecDepth 100000

/-- Edge list of the graph (0-based), in souc_sat's emission order. -/
def ${NAME}_edges : List (Nat × Nat) := [
EOF

edges_lean

cat <<EOF
]

/-- The colouring CNF — the canonical encoding, identical (as a clause multiset
with the same clause order) to souc_sat's emitted DIMACS. -/
def ${NAME}_cnf : CNF Nat := colourCNF $N $K ${NAME}_edges

/-- souc_sat's LRAT refutation as verified-checker actions (RUP / del / empty). -/
def ${NAME}_prf : Array IntAction := #[
EOF

# --- LRAT actions (with contiguous-id renumbering) ----------------------------
awk -v M="$NCLS" '
  /^[ \t]*$/ { next }
  function remap(old,   nw) { nw = map[old]; return (nw == "") ? old : nw }
  {
    if ($2=="d") {
      ids=""; n=0
      for (i=3; i<=NF; i++) { if ($i+0==0) break; if (n++) ids=ids ", "; ids=ids remap($i+0) }
      print "  Action.del #[" ids "],"
      next
    }
    oldid=$1+0
    newid = M + (++addcount)
    map[oldid] = newid
    i=2
    lits=""; nl=0
    while (i<=NF && $i+0!=0) { if (nl++) lits=lits ", "; lits=lits $i; i++ }
    i++
    hints=""; nh=0; rat=0
    while (i<=NF && $i+0!=0) { if ($i+0<0) rat=1; if (nh++) hints=hints ", "; hints=hints remap($i+0); i++ }
    if (rat==1) { print "RAT_NOT_SUPPORTED line " oldid > "/dev/stderr"; exit 3 }
    if (nl==0) print "  Action.addEmpty " newid " #[" hints "],"
    else       print "  Action.addRup " newid " #[" lits "] #[" hints "],"
  }
' "$LRAT"

cat <<EOF
]

/-- The verified LRAT checker accepts souc_sat's certificate (reflective eval). -/
theorem ${NAME}_check : check ${NAME}_prf ${NAME}_cnf = true := by native_decide

/-- Hence the colouring CNF is genuinely unsatisfiable — machine-checked in Lean. -/
theorem ${NAME}_unsat : ${NAME}_cnf.Unsat :=
  check_sound ${NAME}_prf ${NAME}_cnf ${NAME}_check

/-- **Chromatic corollary.** The graph admits no proper $K-colouring
\`Fin $N → Fin $K\` (i.e. its chromatic number is ≥ $((K+1))). -/
theorem ${NAME}_not_colourable :
    ¬ ∃ c : Fin $N → Fin $K,
        ∀ e ∈ ${NAME}_edges, ∀ (h1 : e.1 < $N) (h2 : e.2 < $N), c ⟨e.1, h1⟩ ≠ c ⟨e.2, h2⟩ :=
  not_colourable_of_unsat (by decide) (by decide) ${NAME}_unsat

#print axioms ${NAME}_not_colourable
EOF
} > "$OUT"

echo "wrote $OUT  ($NVARS vars, $NCLS clauses, $NEDGES edges, $(wc -l < "$LRAT") LRAT lines)"
