#!/usr/bin/env python3
"""Emit a disk-safe RTX 8000 Kubernetes job for the chi6 frontier sweep.

The generated job is a launcher, not a proof artifact.  It runs the existing
non-promotable search ledger under OrangeFS scratch and preserves the contract
that GPU output is untrusted until DRAT/LRAT/Lean verification succeeds.
"""

from __future__ import annotations

import argparse
import re
import shlex
import sys
from pathlib import Path


GPU_UUID = "GPU-1a84782e-5b22-def2-2575-0abf3f971016"
RUN_DIR_SWEEP_TOKEN = "__RUN_DIR_SWEEP__"
IMAGE_REGISTRY_RE = re.compile(r"^[a-z0-9]+(?:[._-][a-z0-9]+)*(?::[0-9]+)?$")
IMAGE_REST_RE = re.compile(r"^[a-z0-9]+(?:[._/-][a-z0-9]+)*:[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$")


def dns_label(raw: str, name: str) -> str:
    if not re.fullmatch(r"[a-z0-9]([-a-z0-9]*[a-z0-9])?", raw):
        raise ValueError(f"{name} must be a Kubernetes DNS label: {raw!r}")
    if len(raw) > 63:
        raise ValueError(f"{name} must be <= 63 characters")
    return raw


def safe_csv_ints(raw: str, name: str) -> str:
    if not re.fullmatch(r"[0-9]+(,[0-9]+)*", raw):
        raise ValueError(f"{name} must be a comma-separated positive integer list")
    if any(int(tok) <= 0 for tok in raw.split(",")):
        raise ValueError(f"{name} values must be positive")
    return raw


def safe_int(raw: int, name: str) -> int:
    if raw <= 0:
        raise ValueError(f"{name} must be positive")
    return raw


def image_ref(raw: str) -> str:
    if any(ch.isspace() for ch in raw):
        raise ValueError("--image must not contain whitespace")
    if "/" not in raw:
        raise ValueError("--image must include a registry host and image path")
    registry, rest = raw.split("/", 1)
    if not IMAGE_REGISTRY_RE.fullmatch(registry):
        raise ValueError(f"--image has an invalid registry host: {registry!r}")
    if ":" not in rest.rsplit("/", 1)[-1]:
        raise ValueError("--image must include an explicit tag")
    if not IMAGE_REST_RE.fullmatch(rest):
        raise ValueError("--image must be a tagged registry image reference")
    return raw


def shell_quote(value: str | Path | int) -> str:
    return shlex.quote(str(value))


def quote_sweep_arg(value: str | Path | int) -> str:
    if value == RUN_DIR_SWEEP_TOKEN:
        return "$RUN_DIR/sweep"
    return shell_quote(value)


def render_command(args: argparse.Namespace) -> str:
    run_dir_expr = f"{args.scratch_root.rstrip('/')}/$(date +%Y%m%dT%H%M%SZ)-{args.candidate_prefix}"
    sweep_cmd = [
        "python3",
        "examples/erdos/chi6_frontier_refute_sweep.py",
        RUN_DIR_SWEEP_TOKEN,
        "--candidate-prefix",
        args.candidate_prefix,
        "--max-den-list",
        args.max_den_list,
        "--layers-list",
        args.layers_list,
        "--max-points-list",
        args.max_points_list,
        "--split-depth-list",
        args.split_depth_list,
        "--min-split-degree-list",
        args.min_split_degree_list,
        "--dsatur-node-limit-list",
        args.dsatur_node_limit_list,
        "--preflight-limit",
        str(args.preflight_limit),
        "--max-cubes",
        str(args.max_cubes),
        "--sample-hard-cubes",
        str(args.sample_hard_cubes),
        "--refute-limit",
        str(args.refute_limit),
        "--timeout-seconds",
        str(args.timeout_seconds),
    ]
    if args.stop_after_first_success:
        sweep_cmd.append("--stop-after-first-success")
    quoted_sweep = " ".join(quote_sweep_arg(x) for x in sweep_cmd)
    return f"""set -euo pipefail
echo "chi6_rtx8000_job: start $(date -u +%Y-%m-%dT%H:%M:%SZ)"
nvidia-smi --query-gpu=name,compute_cap,memory.total,uuid --format=csv,noheader
SOUNIO_REPO="${{SOUNIO_REPO:-{args.repo_path}}}"
if [[ ! -d "$SOUNIO_REPO/examples/erdos" ]]; then
  echo "error: SOUNIO_REPO does not contain examples/erdos: $SOUNIO_REPO" >&2
  exit 2
fi
cd "$SOUNIO_REPO"
RUN_DIR="{run_dir_expr}"
mkdir -p "$RUN_DIR"
echo "run_dir=$RUN_DIR"
echo "trust_boundary=backend_untrusted__drat_lrat_lean_verified_required" | tee "$RUN_DIR/TRUST_BOUNDARY.txt"
{quoted_sweep} 2>&1 | tee "$RUN_DIR/sweep.out"
echo "chi6_rtx8000_job: done $(date -u +%Y-%m-%dT%H:%M:%SZ)"
"""


def render_yaml(args: argparse.Namespace) -> str:
    command = render_command(args)
    indented_command = "\n".join(f"          {line}" for line in command.splitlines())
    return f"""# Generated by examples/erdos/make_chi6_rtx8000_gpu_job.py
# Search-only chi6 RTX 8000 job. GPU output is untrusted; promotion still
# requires exact geometry plus DRAT/LRAT/Lean verification.
# Cluster contract: Darwin r740-proxmox RTX 8000 lane with OrangeFS scratch.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {args.pvc_name}
  namespace: {args.namespace}
spec:
  storageClassName: orangefs-memory-lab
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: {args.scratch_size}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {args.job_name}
  namespace: {args.namespace}
  labels:
    app: chi6-rtx8000-sweep
    sounio.dev/claim-scope: search-only
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: r740-proxmox
      tolerations:
      - {{ effect: NoSchedule, key: sounio.dev/pool, operator: Exists }}
      - {{ effect: NoSchedule, key: sounio.dev/compute, operator: Exists }}
      containers:
      - name: chi6-sweep
        image: {args.image}
        command: [bash, -lc]
        args:
        - |
{indented_command}
        env:
        - {{ name: NVIDIA_VISIBLE_DEVICES, value: "{GPU_UUID}" }}
        - {{ name: NVIDIA_DRIVER_CAPABILITIES, value: "compute,utility" }}
        - {{ name: SOUNIO_REPO, value: "{args.repo_path}" }}
        securityContext:
          appArmorProfile: {{ type: Unconfined }}
          capabilities: {{ add: [IPC_LOCK] }}
        resources:
          requests: {{ cpu: "8", memory: "32Gi", nvidia.com/gpu: 1 }}
          limits:   {{ cpu: "16", memory: "48Gi", nvidia.com/gpu: 1 }}
        volumeMounts:
        - {{ name: scratch, mountPath: /scratch }}
        - {{ name: dshm, mountPath: /dev/shm }}
      volumes:
      - {{ name: scratch, persistentVolumeClaim: {{ claimName: {args.pvc_name} }} }}
      - {{ name: dshm, emptyDir: {{ medium: Memory, sizeLimit: 8Gi }} }}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--namespace", default="beagle")
    parser.add_argument("--job-name", default="chi6-rtx8000-sweep")
    parser.add_argument("--pvc-name", default="solver-scratch")
    parser.add_argument("--scratch-size", default="200Gi")
    parser.add_argument(
        "--image",
        required=True,
        help="cluster image built from infra/beagle-sounio/Dockerfile, for example ttl.sh/beagle-sounio-<tag>:24h",
    )
    parser.add_argument("--repo-path", default="/app")
    parser.add_argument("--scratch-root", default="/scratch/chi6")
    parser.add_argument("--candidate-prefix", default="rtxchi6")
    parser.add_argument("--max-den-list", default="1,5")
    parser.add_argument("--layers-list", default="1")
    parser.add_argument("--max-points-list", default="16")
    parser.add_argument("--split-depth-list", default="1")
    parser.add_argument("--min-split-degree-list", default="2")
    parser.add_argument("--dsatur-node-limit-list", default="1")
    parser.add_argument("--preflight-limit", type=int, default=1)
    parser.add_argument("--max-cubes", type=int, default=64)
    parser.add_argument("--sample-hard-cubes", type=int, default=4)
    parser.add_argument("--refute-limit", type=int, default=1)
    parser.add_argument("--timeout-seconds", type=int, default=180)
    parser.add_argument("--stop-after-first-success", action="store_true")
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()

    try:
        args.namespace = dns_label(args.namespace, "namespace")
        args.job_name = dns_label(args.job_name, "job-name")
        args.pvc_name = dns_label(args.pvc_name, "pvc-name")
        args.candidate_prefix = dns_label(args.candidate_prefix, "candidate-prefix")
        args.image = image_ref(args.image)
        for field in (
            "max_den_list",
            "layers_list",
            "max_points_list",
            "split_depth_list",
            "min_split_degree_list",
            "dsatur_node_limit_list",
        ):
            setattr(args, field, safe_csv_ints(getattr(args, field), f"--{field.replace('_', '-')}"))
        for field in ("preflight_limit", "max_cubes", "sample_hard_cubes", "refute_limit", "timeout_seconds"):
            safe_int(getattr(args, field), f"--{field.replace('_', '-')}")
        if args.sample_hard_cubes > args.max_cubes:
            raise ValueError("--sample-hard-cubes cannot exceed --max-cubes")
        if not re.fullmatch(r"[0-9]+Gi", args.scratch_size):
            raise ValueError("--scratch-size must look like 200Gi")
        if not args.repo_path.startswith("/"):
            raise ValueError("--repo-path must be absolute")
        if not args.scratch_root.startswith("/scratch/"):
            raise ValueError("--scratch-root must live under /scratch")
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    text = render_yaml(args)
    if args.output is None:
        print(text, end="")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="ascii")
        print(f"chi6_rtx8000_gpu_job_yaml={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
